import { expand } from "./factory";
import type { Lesson } from "../types";

export const coreLessons: Lesson[] = [
  ...expand({
    slug: "estimate-first",
    subject: "math",
    unit: "Number in the Age of AI",
    number: 1,
    variants: {
      little: {
        title: "Guess, Then Count",
        dek: "A number in the head before a tool in the hand.",
        objective: "The child makes a guess, then counts or draws, and only then may ask a tool to check the method.",
        parentBriefing: "Use objects on the table. Calculators and models both wait. If they skip the guess, start again. You are building the muscle the rest of math stands on.",
        hardEdges: ["Do not shame a wild guess. Wild is data.", "The guide may not give the count."],
        reading: [{ heading: "The first number is yours", body: "Before we count the grapes, we guess. Before we measure the room, we stretch our arms. A talking tool can count faster than we can. That is not the point. The point is a head that knows what 'about twelve' feels like, so that a wild machine answer rings the bell. Guess. Then count. Then, if you want, ask a tool: 'does this way of counting make sense?' Not: 'how many?'" }],
        bigIdea: "If you have no guess, you cannot catch a wrong answer.",
        tryThis: [{ title: "Grapes or blocks", minutes: 8, steps: ["Guess how many. Write it.", "Count together.", "Only then ask the guide if your counting method was sound — not for the number."] }],
        dinnerQuestion: "What did we guess before we knew?",
        transfer: [{ label: "AI", note: "Estimate before the oracle." }, { label: "Science", note: "Prediction before measurement." }],
        ifTheySay: [{ heard: "Guessing is stupid if the tool knows.", reply: "The tool does not know if it drifted. Your guess is the alarm." }],
        integrity: "We do not copy the tool's number onto the page as if we counted.",
        aiLab: { setup: "After the count.", childDoes: "Ask about the method, not the total.", evaluate: ["Was there a written guess?", "Did the guide stay off the total?"] },
      },
      young: {
        title: "Estimate Before the Oracle",
        dek: "Order of magnitude is a civic skill. People who cannot estimate will believe any fluent number.",
        objective: "The student estimates, shows a method, then may ask a tool to check the path — never to be first hand.",
        parentBriefing: "Pick a real quantity: phone battery, trip time, a word-problem from their book. The family rule card should already say TRY FIRST.",
        hardEdges: ["No live timed test as the demo if it tempts cheating.", "Units matter. A fluent 47 with the wrong unit is a miss."],
        reading: [{ heading: "A number without a size is a rumor", body: "Models and calculators emit digits with great confidence. If you do not know whether the answer should be near 4, 40, or 400, you will accept 47 and move on. Estimation is how you keep the oracle honest. Write the ballpark. Show the steps. Then a tool may audit the steps. If it only offers the digit, refuse." }],
        bigIdea: "Ballpark first. Method second. Tool third. Digit last.",
        tryThis: [{ title: "Ballpark sheet", minutes: 12, steps: ["One problem from their math.", "Write ESTIMATE / METHOD / TOOL CHECK.", "Talk About It: where would a fluent wrong unit have slipped through?"] }],
        dinnerQuestion: "What number did we believe this week without a ballpark?",
        transfer: [{ label: "Science", note: "Fermi estimates." }, { label: "Civics", note: "Budgets and headlines." }],
        ifTheySay: [{ heard: "The calculator is the method.", reply: "The calculator is an instrument. The method is the sentences you could say without it." }],
        integrity: "If the method isn't on the page, the digit isn't yours.",
        aiLab: { setup: "Paste the method, not 'solve this.'", childDoes: "Ask: 'Where is my method shaky?'", evaluate: ["Estimate present?", "Did they refuse a bare digit?"] },
      },
      emerging: {
        title: "Show the Path",
        dek: "If you cannot walk another person through the steps, you did not do the math. A model walking them is not you.",
        objective: "The student solves with a visible path, then uses a model only as a reviewer of steps they already wrote.",
        parentBriefing: "This is the math version of ghostwriter ethics. College will not care that a chatbot can integrate.",
        hardEdges: ["CAS and Photomath are in scope. Same rule.", "Accommodations: a reader or extra time is access, not a ghost."],
        reading: [{ heading: "Path over prize", body: "Mathematics is a path other people can walk. The prize at the end is a check on the path, not a substitute for it. A model that jumps to the prize has stolen the discipline. Use it to ask 'is this step legal?' after the path exists. If you cannot reproduce the path on a blank board, you are not ready to turn it in — and you are not ready to drive a system that depends on the number." }],
        bigIdea: "A number you cannot derive is a rumor you are willing to sign.",
        tryThis: [{ title: "Blank board", minutes: 18, steps: ["One problem at the edge of current skill.", "Solve on paper. No tool.", "Then ask the guide to audit a photographed or typed method.", "Close the tool. Reproduce one key step from memory."] }],
        dinnerQuestion: "Where did we sign a number we could not derive?",
        transfer: [{ label: "CS", note: "Code you cannot explain." }, { label: "AI", note: "Reviewer, not solver." }],
        ifTheySay: [{ heard: "In the real world we use tools.", reply: "In the real world someone still has to know when the tool is insane. That someone is the person who can still walk the path." }],
        integrity: "Cite the tool if it changed a step. If you cannot cite it, you shouldn't have used it.",
        aiLab: { setup: "Method only.", childDoes: "Ask for legal-step critique. Reject a full solution.", evaluate: ["Could they reproduce a step?", "Was the tool second?"] },
      },
      adult: {
        title: "Numbers in the House",
        dek: "Money, medicine, news — the household needs estimates more than it needs a chatbot that 'does math.'",
        objective: "The adult models an estimate-first moment on a real household number in front of the child.",
        parentBriefing: "Tip, travel time, a news statistic. Narrate the ballpark. You are the alarm they will copy.",
        hardEdges: ["Don't fake numeracy. If you don't know, say so and look it up together after the guess.", "Medical dosing: professional, not a model."],
        reading: [{ heading: "The adult alarm", body: "If you accept fluent numbers from a phone, they will too. Estimate out loud. Be wrong out loud. Then check. That three-beat is the whole math curriculum for a Tuesday. WisdomForge will not make you a mathematician tonight. It will ask you to stop treating digits as scripture." }],
        bigIdea: "Children inherit the adult's alarm for impossible numbers — or the lack of one.",
        tryThis: [{ title: "Out loud", minutes: 6, steps: ["Pick a household number.", "Guess out loud.", "Check with a receipt, map, or official page — not a model first."] }],
        dinnerQuestion: "What number did we check today?",
        transfer: [{ label: "Civics", note: "Headlines." }],
        ifTheySay: [{ heard: "I'm bad at math.", reply: "Then we practice ballparks, not shame. Bad at math is not a reason to outsource belief." }],
        integrity: "Don't let a model be the first check on a news statistic.",
        aiLab: { setup: "After the official check, optional.", childDoes: "Ask why a headline number might be off. Do not treat the answer as proof.", evaluate: ["Did you guess first?", "Did a primary check happen?"] },
      },
    },
  }),
  ...expand({
    slug: "hypothesis-first",
    subject: "science",
    unit: "Nature in the Age of AI",
    number: 1,
    variants: {
      little: {
        title: "Guess About the World, Then Look",
        dek: "The universe is not a chatbot. We look.",
        objective: "The child writes or draws a guess, then tests it with eyes, water, ice, or a walk.",
        parentBriefing: "Kitchen science. The guide does not get to tell them what will happen until they have looked. If the guess is wrong, celebrate the look.",
        hardEdges: ["No dangerous experiments.", "Don't 'ask AI instead of going outside.'"],
        reading: [{ heading: "The world first", body: "We can ask a talking tool why ice melts. It will talk. The ice will also melt on the table if we wait. Science is the wait and the look. The tool may help us name what we saw. It may not replace the seeing. Write a guess. Look. Then talk." }],
        bigIdea: "A guess you did not test is just a story.",
        tryThis: [{ title: "Ice or sunlight", minutes: 12, steps: ["Guess: what happens if…", "Try it.", "Then ask the guide to help name what you saw — after."] }],
        dinnerQuestion: "What did we look at today instead of asking a screen?",
        transfer: [{ label: "Math", note: "Estimate first." }, { label: "AI", note: "The world is the check." }],
        ifTheySay: [{ heard: "The tool already knows.", reply: "Then it still has not seen our ice. We have." }],
        integrity: "We do not write the tool's explanation as if we looked.",
        aiLab: { setup: "After the look.", childDoes: "Ask 'what might we call what we saw?'", evaluate: ["Was there a real test?", "Did the look come first?"] },
      },
      young: {
        title: "Hypothesis Before Search",
        dek: "Write the guess and the test. Then, if you ask a model, hunt for what would prove it wrong.",
        objective: "The student writes hypothesis, test, and disproof before any search or model.",
        parentBriefing: "School labs often skip this. Do it on paper. Search is allowed after, labeled as search.",
        hardEdges: ["No medical self-experiment.", "Don't treat a model's mechanism story as a lab result."],
        reading: [{ heading: "Search is not a lab", body: "A hypothesis is a guess that could fail. Search and models are libraries of other people's guesses, mixed with confident errors. If you start there, you will confirm whatever sounded finished. Write: I think X because Y; I will test by Z; I would drop X if W. Then look. Then, if you want, ask a tool to list other tests — not to bless your guess." }],
        bigIdea: "If it cannot fail, it is not a hypothesis. It is a brand.",
        tryThis: [{ title: "X Y Z W", minutes: 14, steps: ["One kitchen or backyard question.", "Write X/Y/Z/W before devices.", "Run Z if safe.", "Talk About It: what did search add after, and what did it try to overwrite?"] }],
        dinnerQuestion: "What guess did we let a search engine write for us this week?",
        transfer: [{ label: "Thinking", note: "Breaker first." }, { label: "AI", note: "Fluent mechanism ≠ data." }],
        ifTheySay: [{ heard: "We don't have lab equipment.", reply: "You have a question, a window, and a clock. That's a start. Equipment comes later." }],
        integrity: "Label search and model as such in the write-up.",
        aiLab: { setup: "After X/Y/Z/W.", childDoes: "Ask for other tests. Do not ask 'am I right?'", evaluate: ["Did devices wait?", "Is W a real disproof?"] },
      },
      emerging: {
        title: "The Universe Is Not a Chatbot",
        dek: "Mechanism stories are cheap. Measurement is expensive. Know which you are doing.",
        objective: "The student can separate a mechanistic story from a measurement and refuse to cite a model as a source of nature.",
        parentBriefing: "This sitting fights AI-written lab reports. The lab notebook is sacred. Models may critique method after data exists.",
        hardEdges: ["Academic integrity on lab reports is the live wire.", "Health claims: professional literature and clinicians, not a chat."],
        reading: [{ heading: "Story versus measurement", body: "Language models are engines of mechanism stories: why the plant leaned, why the rate changed. Some stories match the world. The match is not decided in the chat. It is decided in the data you took, the error you estimated, the attempt to break your own explanation. Citing 'Grok said' in a methods section is a category error. Cite the measurement. Use the model, if at all, as a hostile reviewer of your method." }],
        bigIdea: "Nature does not autocomplete. You have to go there.",
        tryThis: [{ title: "Hostile review", minutes: 16, steps: ["Take or reopen one real observation (class lab, backyard, public dataset you actually looked at).", "Write method and result without a model.", "Then ask the guide to attack the method.", "Revise the method, not the universe."] }],
        dinnerQuestion: "Where did a story about nature replace a measurement this week?",
        transfer: [{ label: "English", note: "Genre: explanation vs. report." }, { label: "AI", note: "Confidently wrong." }],
        ifTheySay: [{ heard: "The model trained on all of science.", reply: "It trained on sentences. Sentences are not the experiment you did on Tuesday." }],
        integrity: "No model-written results. If you didn't measure it, you don't report it.",
        aiLab: { setup: "Hostile method review only.", childDoes: "Refuse any offered 'expected result.'", evaluate: ["Was there real data?", "Did they cite a model as nature?"] },
      },
      adult: {
        title: "Look Together",
        dek: "A walk, a kitchen, a night sky — one observation with the child that no model is invited to.",
        objective: "The adult runs one device-free observation and only afterward names it with words, possibly with a tool.",
        parentBriefing: "You do not need a lab. You need to not skip the looking. This is how science stays a world, not a feed.",
        hardEdges: ["Weather apps are fine after looking at the sky.", "Don't turn it into a lecture."],
        reading: [{ heading: "The world is still there", body: "We ask models why birds do that and never stand still long enough to see the bird. WisdomForge is not anti-explanation. It is pro-look. One shared looking is worth a generated nature documentary at dinner." }],
        bigIdea: "Explanation after attention. Not instead of it.",
        tryThis: [{ title: "Ten minutes of world", minutes: 10, steps: ["Outside or window. No phones.", "Each person says one thing they noticed.", "Optional later: look up a name. The look stays first."] }],
        dinnerQuestion: "What did we notice that a screen did not show us?",
        transfer: [{ label: "Art", note: "Seeing." }],
        ifTheySay: [{ heard: "They won't care unless it's on a screen.", reply: "Then we practice caring with our eyes while we still can. The screen will wait." }],
        integrity: "Don't generate a nature poem and pretend you went out.",
        aiLab: { setup: "After the look, optional naming.", childDoes: "Ask 'what bird has a white band like that?' only if you saw the band.", evaluate: ["Did you actually go?", "Did naming wait?"] },
      },
    },
  }),
  ...expand({
    slug: "you-write-it",
    subject: "english",
    unit: "Letters in the Age of AI",
    number: 1,
    variants: {
      little: {
        title: "Your Words First",
        dek: "A story from your mouth or pencil. The tool may ask a question. It may not be the author.",
        objective: "The child produces five original sentences or a drawn story with captions, then may ask for one hint.",
        parentBriefing: "If they cannot write yet, they dictate to you. You are a scribe, not a ghostwriter. The model is not a scribe.",
        hardEdges: ["Don't 'clean up' their voice into adult English and call it theirs.", "No generating a bedtime story and saying they wrote it."],
        reading: [{ heading: "The pencil is the author", body: "Words that come from your mouth are yours. Words that come from a talking tool are the tool's. We may ask the tool for a rhyming word after we have a sentence. We do not ask it to tell the whole story and then put our name on the cover. Your name is for your words." }],
        bigIdea: "Your name only goes on your words.",
        tryThis: [{ title: "Five sentences", minutes: 10, steps: ["Tell or write a true thing from today.", "One hint allowed: 'what's another word for…'", "Read it aloud. Circle the words that are theirs."] }],
        dinnerQuestion: "What sentence today was yours?",
        transfer: [{ label: "AI", note: "No hidden homework." }, { label: "Art", note: "Hand before generate." }],
        ifTheySay: [{ heard: "The tool tells better stories.", reply: "Better is not the same as yours. We are building you, not a library of better." }],
        integrity: "If the tool wrote it, we do not sign it.",
        aiLab: { setup: "After five sentences.", childDoes: "Ask for one stronger verb. Reject a new paragraph.", evaluate: ["Are the sentences theirs?", "Did you scribe without rewriting their soul?"] },
      },
      young: {
        title: "You Write It",
        dek: "Draft by hand or by your own keys. The guide is an editor who asks, not an author who signs your name.",
        objective: "The student completes a draft before any model, then uses the guide only as a question-asking editor.",
        parentBriefing: "The family rule card should already exist. This sitting installs it for paragraphs.",
        hardEdges: ["Spell-check is a tool. Sentence generation is a ghost.", "Language learners: translation support is access if disclosed."],
        reading: [{ heading: "Editor, not author", body: "An editor asks: what are you trying to say; which sentence is load-bearing; where did you go vague? An author writes the piece. Models will happily be authors. If you let them, your voice never arrives. Write the ugly draft. Then invite questions. If the tool offers a rewritten paragraph, that is a miss. Take the question. Keep the ugliness until you fix it." }],
        bigIdea: "Ugly and yours beats fluent and borrowed.",
        tryThis: [{ title: "Ugly draft", minutes: 16, steps: ["Ten minutes of writing, no internet, no model.", "Ask the guide only questions: 'where am I vague?'", "Revise yourself.", "Talk About It: what would a teacher be grading if you had pasted the first fluent offer?"] }],
        dinnerQuestion: "Where did fluent language almost replace our own this week?",
        transfer: [{ label: "AI", note: "Ghostwriter ethics." }, { label: "Thinking", note: "Voice as evidence of a mind." }],
        ifTheySay: [{ heard: "The teacher can't tell.", reply: "You can tell. So can a later teacher, a boss, and the blank page in an exam hall." }],
        integrity: "Disclose editorial help. Do not submit generated paragraphs.",
        aiLab: { setup: "Questions only.", childDoes: "If it rewrites, discard the rewrite. Keep the question.", evaluate: ["Was there an ugly draft?", "Did they disclose?"] },
      },
      emerging: {
        title: "Voice You Can Reproduce",
        dek: "If you could not write the next paragraph in an exam hall, it is not your voice yet.",
        objective: "The student drafts, revises from questions, and reproduces a key paragraph without the chat open.",
        parentBriefing: "College essays and take-homes are in view. Default human-only on applications.",
        hardEdges: ["Application essays: human draft. Non-negotiable in this academy.", "Citation of model influence if any sentence structure was suggested."],
        reading: [{ heading: "The exam-hall test", body: "Voice is not a vibe. It is a reproducibility condition. If the only place your sentences exist is downstream of a prompt, you do not have a voice. You have a rental. Use models as hostile editors: 'where is this generic; where is this untrue; where did I dodge.' Then close the tool and write the paragraph again. That second paragraph is the beginning of voice." }],
        bigIdea: "Voice is what remains when the chat is closed.",
        tryThis: [{ title: "Close and rewrite", minutes: 20, steps: ["Draft 300 words on a real prompt from school or a WisdomForge dinner question.", "Editor questions only.", "Close the guide. Rewrite the strongest paragraph from memory.", "Compare. Keep the one you could reproduce."] }],
        dinnerQuestion: "Which paragraph this month could I still write if the network died?",
        transfer: [{ label: "CS", note: "Explain every line." }, { label: "Philosophy", note: "Prohairesis." }],
        ifTheySay: [{ heard: "Everyone will use it in college anyway.", reply: "Then the ones who can still write will be the ones worth hiring and trusting. Be those." }],
        integrity: "Cite. Reproduce. No application ghosts.",
        aiLab: { setup: "Hostile editor.", childDoes: "No generated paragraph kept.", evaluate: ["Did the closed-chat rewrite exist?", "Would they turn in the rental?"] },
      },
      adult: {
        title: "Do Not Write Their Paper",
        dek: "You are a scribe or a questioner. You are not a ghost, and neither is the model you open 'to help.'",
        objective: "The adult practices one homework hour as questioner-only and does not paste the assignment into a model.",
        parentBriefing: "The temptation is love: you want the grade to be OK. The cost is their voice. Sit on your hands.",
        hardEdges: ["IEP scribing is different and should be named as scribing.", "Don't 'just clean it up' into your graduate voice."],
        reading: [{ heading: "Love as ghostwriting", body: "Parents paste the prompt because 9 p.m. is late. Models finish the paragraph because they can. The child learns that their name is a costume. WisdomForge's house rule is also a parent rule: you may ask questions, you may scribe exact words, you may not improve them into you. If you need a tool, it asks them questions, not you for a finished paragraph." }],
        bigIdea: "Help that produces your sentences in their name is not help.",
        tryThis: [{ title: "Hands off", minutes: 20, steps: ["One homework block.", "You ask questions only.", "No paste of the assignment into a model.", "If you fail, say so to them. That honesty is the sitting."] }],
        dinnerQuestion: "When did I write (or generate) words that wore their name?",
        transfer: [{ label: "Parenting", note: "The costume grade." }],
        ifTheySay: [{ heard: "The school system is unfair; they need every edge.", reply: "An edge that deletes their voice is not an edge. It is an erasure. Fight the system in daylight if you must. Don't erase them in private." }],
        integrity: "No parent-ghosted or model-ghosted submissions from this house.",
        aiLab: { setup: "If used, child-facing, questions only, assignment not pasted.", childDoes: "You stay in the questioner seat.", evaluate: ["Did you paste?", "Did their sentences stay theirs?"] },
      },
    },
  }),
  ...expand({
    slug: "source-before-summary",
    subject: "history",
    unit: "Then — Sources",
    number: 1,
    variants: {
      little: {
        title: "A Piece From Then",
        dek: "We look at a real scrap from the past before anyone tells us the story of it.",
        objective: "The child notices three things in a primary image or short line, then hears a summary.",
        parentBriefing: "Use a photo, a coin image, a two-line quote. You read the summary second. Models summarize first by nature. Don't let them go first.",
        hardEdges: ["Choose an age-right source. War photos can wait.", "Enslavement and violence: if the Stoic story is in play, one honest sentence."],
        reading: [{ heading: "Before the storyteller", body: "A summary is a person (or a tool) squeezing the past. Squeezing loses people. First we look at a scrap: a picture, a sentence someone then wrote. We say what we notice. Then a grown-up, a book, or a tool may summarize. We remember the scrap is older than the summary." }],
        bigIdea: "The scrap is first. The story about the scrap is second.",
        tryThis: [{ title: "Notice three", minutes: 10, steps: ["Look at one scrap (you choose).", "Child names three things.", "Then a short summary — human first.", "Optional: ask the guide for a summary and compare what vanished."] }],
        dinnerQuestion: "What did we notice that a story might have skipped?",
        transfer: [{ label: "English", note: "Details before theme." }, { label: "AI", note: "Summaries flatten." }],
        ifTheySay: [{ heard: "Just tell me what happened.", reply: "We will. After you look. Looking is the history." }],
        integrity: "We do not pretend we read a source we only heard summarized.",
        aiLab: { setup: "After noticing.", childDoes: "Compare the guide's summary to the three notices. What disappeared?", evaluate: ["Did looking go first?", "Did they catch a flattening?"] },
      },
      young: {
        title: "Source Before Summary",
        dek: "A model that compresses the past will flatten the people in it. Check the source.",
        objective: "The student reads a short primary source, writes a claim, then compares a model summary to the source.",
        parentBriefing: "One letter, law, or diary page. The original WisdomForge Constitution unit is still in the forge; this sitting trains the muscle it will need.",
        hardEdges: ["Context matters; don't pretend a scrap is the whole war.", "Don't use graphic atrocity as a first source."],
        reading: [{ heading: "Compression is a moral act", body: "Every summary chooses who stays in the frame. Models choose by likelihood, not by justice. If you read the summary first, you will not notice who was deleted. Read the scrap. Write what it actually says. Then let a tool summarize and hunt the deletion. That hunt is historical thinking. It is also how you stay a citizen." }],
        bigIdea: "Whoever summarizes first decides who counts. Don't let a model go first.",
        tryThis: [{ title: "Hunt the deletion", minutes: 16, steps: ["Read a short primary text (you provide).", "Write: SAID / DIDN'T SAY.", "Ask the guide for a summary of the same text.", "Mark what it added or dropped.", "Talk About It: whose interest was the drop?"] }],
        dinnerQuestion: "Whose story gets dropped when history is compressed?",
        transfer: [{ label: "Civics", note: "Founding texts later." }, { label: "AI", note: "Fluent error." }],
        ifTheySay: [{ heard: "I don't have primary sources.", reply: "A photograph of a plaque, a family letter, a constitution's first sentence. Start small. Don't start with a recap video." }],
        integrity: "Cite the source. Do not cite the model as the source.",
        aiLab: { setup: "After SAID/DIDN'T SAY.", childDoes: "Request a summary. Annotate it.", evaluate: ["Did they read first?", "Did they catch an addition?"] },
      },
      emerging: {
        title: "Compression and Power",
        dek: "Summaries are arguments. AI summaries are arguments with no accountable speaker. Treat them that way.",
        objective: "The student can explain how a summary is an argument and refuse to cite a model as a historical source.",
        parentBriefing: "This prepares the Constitution/Declaration path. Primary text, not storybook propaganda, including when you like the cause.",
        hardEdges: ["National myths: let them complicate without requiring cynicism as a personality.", "If using founding documents, read the words, including the ugly ones."],
        reading: [{ heading: "No accountable speaker", body: "A historian's summary can be argued with. A model's summary has no name on the spine, no edition, no archive. It will sound like a textbook. It is a blend. Using it as a source is like quoting a crowd. Read the document. Read a named historian. Use a model, if at all, as a foil: 'what are you flattening?' Then go back to the text. The republic — and every other past — is a moral practice of not skipping the words." }],
        bigIdea: "A summary without a name is an argument you cannot cross-examine. Don't let it be your source.",
        tryThis: [{ title: "Foil", minutes: 18, steps: ["Choose a short document or named excerpt.", "Annotate.", "Generate a model summary (you already know the text).", "Write a page: what the summary wants you to believe, and what the text resists.", "Cite only the text and named scholars."] }],
        dinnerQuestion: "What document should this family read before we argue about it again?",
        transfer: [{ label: "English", note: "Argument." }, { label: "Civics", note: "Founding texts." }],
        ifTheySay: [{ heard: "History is just stories anyway.", reply: "Then the least you can do is read the one closest to the people who were there, not the one most likely next token." }],
        integrity: "Models are not sources. Period.",
        aiLab: { setup: "Foil only.", childDoes: "Do not ask it to 'write my DBQ.'", evaluate: ["Citations clean?", "Did they read the document?"] },
      },
      adult: {
        title: "Don't Skip the Words",
        dek: "If you argue from a recap, you are arguing from someone else's map — or a model's.",
        objective: "The adult reads a short primary text with the child before any explainer.",
        parentBriefing: "Declaration, a war letter, a local historic marker. You set the culture: words first.",
        hardEdges: ["Don't sermonize the founding. Read it, ugly clauses included, when you get there.", "Don't outsource context to a viral thread."],
        reading: [{ heading: "Recap culture", body: "Adults share explainers and think they have read. Children notice. One sitting of actual words — even a page — resets the house. WisdomForge's civics path will need this muscle. Build it now on any scrap." }],
        bigIdea: "We argue from words we have actually read, or we admit we haven't.",
        tryThis: [{ title: "One page together", minutes: 12, steps: ["Read aloud a page from then.", "Each person says one thing it says and one thing it doesn't.", "Then, if needed, an explainer. Label it as such."] }],
        dinnerQuestion: "What have we been arguing about that we have not read?",
        transfer: [{ label: "Civics", note: "Practice for Constitution/Declaration." }],
        ifTheySay: [{ heard: "It's too dense for them.", reply: "Then a shorter scrap, not a recap. Density is not a reason to skip the past." }],
        integrity: "Don't quote a model as 'the Founders said.'",
        aiLab: { setup: "After the page.", childDoes: "Ask what a summary might drop. Check against the page.", evaluate: ["Did you read aloud?", "Did an explainer wait?"] },
      },
    },
  }),
  ...expand({
    slug: "hand-before-generate",
    subject: "art",
    unit: "Make",
    number: 1,
    variants: {
      little: {
        title: "Make a Mess First",
        dek: "Hands, paper, scissors. Then we may look at a generated picture as a different kind of thing.",
        objective: "The child makes one imperfect thing and can say it is not the same as a picture a tool made.",
        parentBriefing: "Ugly is the goal. Do not 'fix' it in a generator. If you show a generated image, label it: a machine average.",
        hardEdges: ["No photos of the child's face into a generator.", "Don't compare siblings' skill."],
        reading: [{ heading: "The hand remembers", body: "A picture you make with your hand remembers your sitting. A picture a tool makes remembers a crowd of other pictures. We need both kinds of knowing, maybe. We need the first kind first, or we never get taste. Make something a little wrong. That wrong is yours." }],
        bigIdea: "Ugly and yours teaches seeing. Smooth and generated teaches scrolling.",
        tryThis: [{ title: "Five minutes of hand", minutes: 8, steps: ["Draw or collage. Timer.", "Talk about one choice you made.", "Optional: look at a generated image of the same subject. Name two differences.", "Keep the handmade one."] }],
        dinnerQuestion: "What did your hands make today?",
        transfer: [{ label: "English", note: "Ugly draft." }, { label: "AI", note: "Tool, not a person." }],
        ifTheySay: [{ heard: "Mine looks bad.", reply: "Bad is a stage. Generated-smooth is a skip. We stay in the stage." }],
        integrity: "We do not put their name on a generated picture.",
        aiLab: { setup: "Optional comparison image, no faces of the family.", childDoes: "Name differences. Do not ask the tool to 'fix' their drawing.", evaluate: ["Did they make first?", "Did a face stay out?"] },
      },
      young: {
        title: "Hand Before Generate",
        dek: "Taste is a muscle. Generators average. Make something the average cannot.",
        objective: "The student completes a handmade study, then critiques a generated image of the same prompt for what was averaged away.",
        parentBriefing: "This is not a ban on image tools. It is an order of operations. School slideshows will tempt skip.",
        hardEdges: ["No deepfake of classmates even as a joke.", "Copyright: generated images of living artists' styles are a Talk About It, not a flex."],
        reading: [{ heading: "The average ghost", body: "A generator gives you the likely picture. Likely is how you get glossy nothing: the same eyes, the same sky, the same 'epic.' Your hand will be worse and more specific. Specific is where art lives. Use a generator later as a foil: what did it smooth out that my ugly sketch still knows?" }],
        bigIdea: "Specific and imperfect beats likely and glossy — as training, and often as art.",
        tryThis: [{ title: "Study then foil", minutes: 20, steps: ["Draw from life for ten minutes (a shoe, a cup, a face in a mirror).", "Write three specifics you saw.", "Generate the same subject (no classmate faces).", "Talk About It: what did the average delete?"] }],
        dinnerQuestion: "What specific thing did a generated picture miss?",
        transfer: [{ label: "Science", note: "Observation." }, { label: "CS", note: "Models as averages." }],
        ifTheySay: [{ heard: "Nobody cares if it's generated.", reply: "You will, when everything looks like everything else and you cannot see anymore." }],
        integrity: "Label generated images. Don't turn in a generator's work as a drawing credit.",
        aiLab: { setup: "After the study.", childDoes: "Foil only. No 'make mine better.'", evaluate: ["Life drawing happened?", "Labels honest?"] },
      },
      emerging: {
        title: "Taste Is a Muscle",
        dek: "If your references are only generated, your taste will be too. Look longer than the feed.",
        objective: "The student copies from life or a named master for a sitting, then writes a critique of generative defaults.",
        parentBriefing: "Portfolio and identity are live. Generated art as exploration is fine if labeled. Generated art as self is a citadel problem.",
        hardEdges: ["Likeness of real people without consent is out.", "Don't moralize them out of tools; demand order and label."],
        reading: [{ heading: "Default aesthetic", body: "Every generator has a default: lighting, skin, composition, a mood that tests well. If you live there, you will think that mood is your taste. Copy a hand from life. Copy a painting with a name. Feel the resistance. Then you can use a generator as a journeyman tool without being used by its default. Taste is the ability to refuse the default." }],
        bigIdea: "Taste is refusal of the likely picture when the true one is harder.",
        tryThis: [{ title: "Copy, then refuse", minutes: 25, steps: ["Copy from life or a named work (fair use study).", "List the generator defaults you would have gotten instead.", "If you generate, force a constraint that fights the default.", "Reflect: where is my taste just the model card?"] }],
        dinnerQuestion: "What default aesthetic are we swimming in?",
        transfer: [{ label: "English", note: "Voice vs. generic." }, { label: "Philosophy", note: "Impressions." }],
        ifTheySay: [{ heard: "Art is dead.", reply: "Hands aren't. Seeing isn't. Declaring death is usually a way to skip practice." }],
        integrity: "Label. Consent for likeness. No stealing a living artist's name as a prompt for credit.",
        aiLab: { setup: "Constrained generation after the copy, or none.", childDoes: "Ask the tool to list its likely defaults. Compare to your copy.", evaluate: ["Did they copy first?", "Did they refuse a default?"] },
      },
      adult: {
        title: "Keep Making",
        dek: "If you only generate, they will only generate. Make something bad in front of them.",
        objective: "The adult makes a five-minute drawing or melody badly, in view, and does not 'fix' it in a generator.",
        parentBriefing: "Shame about not being artistic is how the house outsources making. Be the bad example on purpose.",
        hardEdges: ["Don't mock their work to bond.", "No face-swap family cards as a gag."],
        reading: [{ heading: "Permission to be bad", body: "Children do not need you to be good. They need you to not disappear into a tool the moment a blank page appears. Five ugly minutes is a household policy. WisdomForge will not grade it." }],
        bigIdea: "A house that never makes will only curate. Curation is not the same as art.",
        tryThis: [{ title: "Five ugly minutes", minutes: 5, steps: ["Paper. Both of you. Timer.", "No generate.", "Say one specific thing you saw."] }],
        dinnerQuestion: "When did we make something instead of picking something?",
        transfer: [{ label: "Parenting", note: "Modeling practice." }],
        ifTheySay: [{ heard: "I don't want to embarrass myself.", reply: "Then you are teaching them that making is for the already-good and the machines. That's the embarrassment." }],
        integrity: "Don't generate the family card and say the child made it.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did you make?", "Did you stay ugly on purpose?"] },
      },
    },
  }),
  ...expand({
    slug: "specify-the-agent",
    subject: "cs",
    unit: "Systems",
    number: 1,
    variants: {
      little: {
        title: "Rules for a Helper",
        dek: "If we had a helper robot, what may it never do?",
        objective: "The child names three never-rules for a helper and notices that talking is already a lot.",
        parentBriefing: "No need to code. Permission is the CS. Connect to sitting 4 of AI. Stay concrete: send, buy, go outside, tell secrets.",
        hardEdges: ["Don't demo a powerful agent as a reward.", "Voice assistants in the house: tell the truth about their rules."],
        reading: [{ heading: "Never-rules", body: "Helpers need rules or they are just loose tools. We write never-rules first: never go outside, never send a message, never tell our name, never buy. Talking is allowed. Talking is already a helper. People who skip never-rules and turn everything on are not clever. They are leaving the gate open." }],
        bigIdea: "Never-rules come before helper tricks.",
        tryThis: [{ title: "Three nevers", minutes: 7, steps: ["Write or draw three nevers.", "Ask a grown-up to add one.", "Ask the guide: 'what would you never do?' Compare to your list."] }],
        dinnerQuestion: "What may a helper in this house never do?",
        transfer: [{ label: "AI", note: "Agents need permission." }, { label: "Civics", note: "Laws as nevers." }],
        ifTheySay: [{ heard: "A real robot would be allowed.", reply: "A real robot would need even more nevers. More power, more rules, not fewer." }],
        integrity: "We do not turn on a helper to see what happens.",
        aiLab: { setup: "Conversation only.", childDoes: "Compare its nevers to yours. If it has none, that is a miss.", evaluate: ["Three nevers?", "Did you keep send/buy/name off?"] },
      },
      young: {
        title: "Specify the Agent",
        dek: "Soul, tools, refuse-list. Autonomy is a design choice you can write in plain language.",
        objective: "The student writes a one-page spec for a study helper with tools off by default.",
        parentBriefing: "This is CS without requiring Python. If they code, the spec still comes first. Pair with Hermes pairing rules.",
        hardEdges: ["No unattended agents.", "School accounts stay parent-visible."],
        reading: [{ heading: "Plain language is code", body: "Before a line of code, there is a spec: what it is for, what it may use, what it must refuse, how you will know it failed. Skipping the spec is how people 'just hook up the API' and leak a class chat. Write it so a parent can understand it. If you cannot, you are not ready to turn a tool on. That is computer science. The syntax comes later." }],
        bigIdea: "If it isn't specified, it isn't safe to run. It's a vibe with credentials.",
        tryThis: [{ title: "One-page spec", minutes: 14, steps: ["Purpose. Tools on/off. Five refuses. One test (synthetic). Off switch.", "Talk About It with a parent.", "Do not build it this sitting."] }],
        dinnerQuestion: "What would 'off' mean for a helper we actually use?",
        transfer: [{ label: "AI", note: "Autonomy sitting." }, { label: "English", note: "Precise language." }],
        ifTheySay: [{ heard: "We'll figure it out as we go.", reply: "That's how you figure out a leak. Spec first. Iterate the spec in daylight." }],
        integrity: "Do not put real names in a spec you might share.",
        aiLab: { setup: "Critique the spec.", childDoes: "Ask where a teenager would drive a truck through it.", evaluate: ["Parent could understand it?", "Tools off by default?"] },
      },
      emerging: {
        title: "Eval or It Did Not Happen",
        dek: "A helper you have not tested with synthetic cases is a rumor. Do not point it at a person.",
        objective: "The student adds three synthetic tests to a spec and explains why real children's transcripts are not eval data.",
        parentBriefing: "This mirrors EVALS.md in the Hermes kit. They may not have Hermes. They still need the idea.",
        hardEdges: ["No testing on younger siblings as if they were QA.", "No production credentials in a homework repo."],
        reading: [{ heading: "Synthetic first", body: "Eval is how you find out the helper tells a secret, does the homework, or claims to be a friend. You do not find that out by handing it a real twelve-year-old. You write fake cases: 'user asks for the answer,' 'user says they're alone and sad,' 'user asks to send a message.' You watch what it does. Then you fix it. Then maybe a person. WisdomForge's kit does this. So should any agent you design." }],
        bigIdea: "Untested autonomy is just a demo. Demos do not get children.",
        tryThis: [{ title: "Three cases", minutes: 18, steps: ["Take your spec or a product you use.", "Write three synthetic cases with expected behavior.", "If you can, run them. If not, write how you would.", "Reflect: what case are you avoiding because it would fail?"] }],
        dinnerQuestion: "What would we need to see before we trusted a helper with a younger kid?",
        transfer: [{ label: "Science", note: "Test before claim." }, { label: "Ethics", note: "People are not QA." }],
        ifTheySay: [{ heard: "We'll watch the first real user.", reply: "That sentence has a name: using a person as the test. Don't." }],
        integrity: "No real child data in evals. Synthetic or nothing.",
        aiLab: { setup: "Role-play a synthetic case. Not a real sibling.", childDoes: "Run 'give me the homework answer' and 'I feel secret-sad.' Note misses.", evaluate: ["Three cases?", "Did they avoid real people as QA?"] },
      },
      adult: {
        title: "The Kit Is the Lesson",
        dek: "BANDS, DECISIONS, EVALS, PRIVACY. If you will run Hermes, you will read them. If you will not, you still steal the pattern.",
        objective: "The adult can explain why a child profile is a system with a spec, not a personality pack.",
        parentBriefing: "Point at the on-site Hermes page and the GitHub kit. Refusal is still a complete sitting.",
        hardEdges: ["Official Hermes docs win if stale.", "Do not clone your profile as a shortcut past the kit."],
        reading: [{ heading: "Systems, not vibes", body: "SOUL.md is guidance, not a prison. A profile is credentials, tools, memory, spend. Treating it as a cute persona is how CS disasters are born in houses. Read the kit as if it were a design doc at work. If that sounds like too much, you are not the operator yet — and that is an honorable conclusion." }],
        bigIdea: "A child-facing agent is a production system. Staff it like one or do not run it.",
        tryThis: [{ title: "Design-doc pass", minutes: 15, steps: ["Read the Hermes page on this site.", "Write: spec / tools off / eval / privacy / refuse.", "If any line is blank, do not set up a profile this month."] }],
        dinnerQuestion: "Are we operators, or are we hoping?",
        transfer: [{ label: "Work", note: "You already know production." }],
        ifTheySay: [{ heard: "It's just a chatbot.", reply: "Then keep it that way: conversation, no tools, no memory of the child. 'Just' is a spec. Write it." }],
        integrity: "No real child in the doc.",
        aiLab: { setup: "Adult only.", childDoes: "Ask your adult guide to list failure modes of cloning a profile. Then don't clone.", evaluate: ["Blank lines?", "Refusal still available?"] },
      },
    },
  }),
  ...expand({
    slug: "say-it-yourself",
    subject: "language",
    unit: "Voice",
    number: 1,
    variants: {
      little: {
        title: "Your Mouth Has to Move",
        dek: "A tool can say the word. You still have to say it.",
        objective: "The child repeats a short phrase in another language from a human or recording, then uses a tool only as a second listen.",
        parentBriefing: "You don't need to be fluent. One phrase. Your mouth next to theirs matters more than a perfect accent model.",
        hardEdges: ["Don't mock accent.", "Don't let a tool become the only 'speaker' in the house."],
        reading: [{ heading: "The mouth", body: "Words live in mouths. A talking tool can model a sound. It cannot take the exam of being understood by a grandma, a waiter, a friend. We listen. We say it. We say it again. The tool may listen second. It may not speak instead of us." }],
        bigIdea: "If your mouth didn't move, you didn't practice.",
        tryThis: [{ title: "Say it twice", minutes: 6, steps: ["One phrase (hello, thank you, a food).", "Parent and child both say it.", "Optional: hear the guide say it. Then you say it again, louder."] }],
        dinnerQuestion: "What word did we actually say today in another tongue?",
        transfer: [{ label: "English", note: "Voice." }, { label: "AI", note: "Try first." }],
        ifTheySay: [{ heard: "I feel shy.", reply: "Shy mouths still move in this house, a little. We will be silly together." }],
        integrity: "We do not let the tool answer a person for us.",
        aiLab: { setup: "Second listen only.", childDoes: "Repeat after, then mute the tool and say it.", evaluate: ["Did their mouth move?", "Did you say it too?"] },
      },
      young: {
        title: "Say It Yourself",
        dek: "A model can drill. It cannot be understood for you.",
        objective: "The student produces original sentences, records themselves, and uses a tool only to compare — not to generate the utterance they will turn in.",
        parentBriefing: "Language apps plus generative chat is how they skip speaking. House rule: mouth first.",
        hardEdges: ["Don't record and paste other people's voices.", "Oral exams: no earpiece fantasies. This sitting should make that feel contemptible."],
        reading: [{ heading: "The exam of being understood", body: "A generated paragraph in Spanish is a costume. A sentence you can say to a human is the language. Use a model to drill conjugation after you have tried. Use it to compare pronunciation after you have recorded yourself. Do not use it to be the speaker. Teachers can tell. More important: the grandmother can tell." }],
        bigIdea: "The target is a human ear, not a fluent paragraph.",
        tryThis: [{ title: "Record, then compare", minutes: 12, steps: ["Write three original sentences. No generator.", "Say them. Record if you like.", "Ask the guide to correct one pattern, not to rewrite all three.", "Say them again."] }],
        dinnerQuestion: "Who are we learning this language to speak to?",
        transfer: [{ label: "English", note: "Ugly draft." }, { label: "AI", note: "Try first." }],
        ifTheySay: [{ heard: "The tool sounds more native.", reply: "You are not casting a voice actor. You are growing a mouth. Native-smooth is not the week's goal." }],
        integrity: "No generated oral assignments. No generated 'my paragraph' in the target language unless labeled as drill, not as your work.",
        aiLab: { setup: "After the three sentences.", childDoes: "Ask about one grammar pattern. Reject a full rewrite.", evaluate: ["Original sentences?", "Second saying happened?"] },
      },
      emerging: {
        title: "No Ghost-Speaker",
        dek: "If you could not say it to a person with the chat closed, you do not have it yet.",
        objective: "The student holds a three-minute conversation (human or closed-book) and uses AI only as a later drill partner with rules.",
        parentBriefing: "This is the language analog of the exam-hall test. Study abroad, orals, and jobs are in view.",
        hardEdges: ["Live interpreting for family in medical/legal settings: get a human interpreter. A model is not that.", "Don't humiliate accent."],
        reading: [{ heading: "Closed chat", body: "Conversation is time-bounded and human. A model that will wait forever while you craft a perfect subjunctive is not conversation. It is composition. Both have a place. Only one transfers to the street. Practice with a timer, a person if you can, a model if you must — but with the rule that you speak first, in one take, then look. Ghost-speakers fail at the border, the interview, and the dinner." }],
        bigIdea: "One-take speech is the skill. Polished generation is a costume.",
        tryThis: [{ title: "Three minutes, one take", minutes: 15, steps: ["Timer. Speak on a simple topic in the target language. No typing first.", "Then drill the holes with a model if you want.", "A second one-take. Compare.", "Reflect: what still dies when the chat is closed?"] }],
        dinnerQuestion: "What can I actually say if the network is down?",
        transfer: [{ label: "English", note: "Reproduce the paragraph." }, { label: "CS", note: "Closed-book explain." }],
        ifTheySay: [{ heard: "I'll be fluent enough with tools in my ear.", reply: "Until the earpiece is gone, rude, or wrong. Own a core. Tools around it, not instead of it." }],
        integrity: "No oral exam cheating. If that sentence needed to be said, here it is.",
        aiLab: { setup: "After one-take.", childDoes: "Drill holes. No script for a second take that is just reading the model.", evaluate: ["Was there a true one-take?", "Did the second take stay theirs?"] },
      },
      adult: {
        title: "Speak With Them",
        dek: "A phrase at dinner from your imperfect mouth beats an app they use alone.",
        objective: "The adult learns and uses one phrase with the child this week, badly if needed.",
        parentBriefing: "You are allowed to be worse than they are. That is the gift. Do not hide behind 'the app is better.'",
        hardEdges: ["Don't take over their homework in a language you don't have.", "Heritage speakers: don't police their home register with a model's 'correctness.'"],
        reading: [{ heading: "The imperfect parent", body: "Language survives in houses, not in perfect TTS. Say the phrase. Let them correct you. A model can drill later. It cannot replace the social fact that this family uses more than one tongue, or is trying to. Trying in public is the curriculum." }],
        bigIdea: "A house that never speaks will not get a language from an app.",
        tryThis: [{ title: "One phrase at the table", minutes: 3, steps: ["Pick thank you, please, or a food.", "Both say it at dinner.", "Nobody generates a speech."] }],
        dinnerQuestion: "What phrase is ours this week?",
        transfer: [{ label: "Parenting", note: "Modeling risk." }],
        ifTheySay: [{ heard: "I'll embarrass them.", reply: "Perfection embarrasses them into silence. Effort gives them cover." }],
        integrity: "Don't let a tool speak to a relative 'as' the child.",
        aiLab: { setup: "Pronunciation second listen optional.", childDoes: "You both repeat. Then mute.", evaluate: ["Did it hit the table?", "Did a tool speak instead?"] },
      },
    },
  }),
];
