import { expand } from "./factory";
import type { Lesson } from "../types";

export const fathersLessons: Lesson[] = [
  ...expand({
    slug: "faith-seeking-understanding",
    subject: "philosophy",
    unit: "Faith & Reason",
    number: 1,
    bands: ["emerging", "adult"],
    variants: {
      emerging: {
        title: "The Restless Heart",
        dek: "Augustine said we were made for something the world cannot give. The hunger is not weakness — it is a compass. But is that philosophy or apologetics?",
        objective: "The student can state Augustine's cor inquietum claim, distinguish evidence from proof, and evaluate one objection from non-belief.",
        parentBriefing: "This is intellectual history, not catechism. Augustine's argument: human beings want something they cannot name, and nothing they get satisfies permanently. He called that God. A secular student can engage the phenomenology (the restlessness is real) without accepting the theology (the restlessness points at God). Teach both layers. The discipline is honesty about the difference.",
        hardEdges: ["Augustine is not arguing 'believe because you're hungry.' He is arguing that the hunger is evidence — not proof. The distinction matters.", "This is a Christian claim about a Christian God. It is also a phenomenological claim about human experience. Teach both. Don't pretend it's only one."],
        reading: [{ heading: "The hunger as compass", body: "Augustine's Confessions opens with one of the most quoted lines in Western thought: 'You have made us for yourself, and our heart is restless until it rests in you.' The claim is not 'God exists because you feel empty.' It is subtler: the restlessness itself is evidence. You didn't invent the hunger. You didn't choose it. It came with you. Augustine says that hunger is not random — it is a compass pointing at something real. The question is what. Augustine says God. A secular philosopher says: maybe meaning, maybe connection, maybe something we haven't named yet. But you can't say the restlessness isn't real. That is Augustine's move: start with desire, not with proof. Let the hunger ask the question. The answer is a separate conversation." }],
        bigIdea: "Faith does not replace reason. Faith gives reason its starting point — the conviction that the desire for truth is not arbitrary.",
        tryThis: [{ title: "Map the restlessness", minutes: 16, steps: ["Name one thing you wanted badly, got, and then found yourself wanting something else. What was the pattern?", "Augustine says the pattern is evidence — not proof — that what you're looking for is not in the things you get. Do you agree?", "What would 'proof' look like for this kind of claim? Is proof even the right standard?", "Practice/Reflect: is the restlessness a compass or just an appetite? How would you tell the difference?"] }],
        dinnerQuestion: "Is there something you want that nothing you've gotten has satisfied — and is that a compass or just an appetite?",
        transfer: [{ label: "AI", note: "A model has no restlessness. It has no hunger. The question of whether hunger is evidence of something is a question only a being with hunger can ask." }, { label: "Greeks", note: "Augustine's restless heart echoes Socrates' unexamined life — both start with desire, not with proof." }],
        ifTheySay: [
          { heard: "Faith is just believing without evidence.", reply: "Augustine would say faith is responding to evidence — the evidence of your own desire. You didn't invent the hunger. The question is what it points at. That is not 'believing without evidence.' It is taking your own experience seriously enough to ask where it leads." },
          { heard: "I don't believe in God, so this doesn't apply to me.", reply: "The restless heart is not a theological claim you have to accept. It is a phenomenological observation: human beings want something they cannot name, and nothing satisfies permanently. Augustine says that's God. You can say it's something else. But you can't say the restlessness isn't real." },
        ],
        integrity: "Do not ask the model to generate devotional content, prayers, or personal testimonies. Ask it to explain arguments. The model explains; the human prays (or doesn't). That boundary is the sitting.",
        aiLab: { setup: "After reading.", childDoes: "Ask the model to state Augustine's argument in three sentences. Then ask: 'What is the strongest objection to this argument?' Evaluate both. The model does not get the last word.", evaluate: ["Can they distinguish evidence from proof?", "Did they engage the non-belief objection honestly?"] },
      },
      adult: {
        title: "Belief That Can Think",
        dek: "Augustine said faith is the beginning of thinking, not the end. But how do you teach that to a child without recruiting them to your theology?",
        objective: "The adult can distinguish the philosophical argument from the theological conclusion and identify how to teach the argument without proselytizing.",
        parentBriefing: "This is the parent's theological humility sitting. Augustine's cor inquietum is a Christian claim about God. It is also a phenomenological claim about human experience that a secular philosopher can engage. Your job is to teach both layers — the argument and the conclusion — without forcing the conclusion. Whether you accept the theology is your business. Whether your child can understand the argument is the academy's business.",
        hardEdges: ["Don't present Augustine's conclusion as the only option. The restlessness is real; what it points at is contested. Let your child contest it.", "If you are a secular parent, don't dismiss the argument because you reject the conclusion. The phenomenology of desire is real regardless of what you think it points at."],
        reading: [{ heading: "Teaching the argument, not the answer", body: "Augustine's Confessions: 'Our heart is restless until it rests in you.' The adult version of this sitting is about pedagogy, not philosophy. How do you teach a child that desire is epistemologically significant — that wanting something you can't name might be evidence — without telling them what the evidence proves? The answer: teach the argument, not the conclusion. The argument: human beings have a hunger that nothing in the world permanently satisfies. That hunger is not random — it is structured, persistent, and universal. Augustine says it points at God. A secular philosopher says it points at meaning, purpose, or something unnamed. The argument is the same. The conclusions differ. Your child needs to understand the argument so they can evaluate the conclusions — including yours. The parent theological humility note: this is intellectual history, not catechism. The academy teaches how Augustine reasoned. Whether you accept his conclusion is your own work — and your child's." }],
        bigIdea: "Teach the argument, not the answer. The restlessness is real. What it points at is the conversation — and your child deserves to be in it.",
        tryThis: [{ title: "The humility audit", minutes: 10, steps: ["Ask: when I teach my child about meaning, am I teaching an argument or an answer?", "Augustine's argument (desire is evidence) vs. his conclusion (desire points at God). Can I teach the first without forcing the second?", "One conversation to have this week: ask your child what they want that nothing has satisfied. Listen. Don't answer for them.", "The discipline: let the question stand without rushing to fill it."] }],
        dinnerQuestion: "What do we want that nothing we've gotten has satisfied — and are we comfortable letting that question stay open?",
        transfer: [{ label: "Parenting", note: "Your child's spiritual life is theirs, not yours. Your job is to give them the questions, not the answers." }],
        ifTheySay: [
          { heard: "This is just religious apologetics dressed as philosophy.", reply: "It is both, and the distinction matters. The Confessions is a prayer and a philosophical argument. The academy teaches the argument: that desire is epistemologically significant, that the hunger for truth suggests truth is real. Whether you accept the conclusion is your business. The argument is worth understanding either way." },
        ],
        integrity: "If the theological conclusion is generated by the model, you've outsourced the one judgment that is yours: what does the restlessness mean? The model can explain Augustine. Only you can decide what you believe.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they distinguish argument from conclusion?", "Is their pedagogy humble or prescriptive?"] },
      },
    },
  }),
  ...expand({
    slug: "evil-as-privation",
    subject: "philosophy",
    unit: "Faith & Reason",
    number: 2,
    bands: ["emerging", "adult"],
    variants: {
      emerging: {
        title: "The Darkness That Isn't a Thing",
        dek: "Augustine said evil is not a substance — it is the absence of good, like darkness is the absence of light. Elegant. But does it survive genocide?",
        objective: "The student can state Augustine's privation theory, distinguish moral evil from natural evil, and evaluate one objection.",
        parentBriefing: "This is intellectual history, not catechism. Augustine's privation theory: evil is not a thing, it is the absence of good where good should be. The will chooses a lesser good over the highest good, and that choice is the origin of moral evil. Teach the argument. Whether it solves the problem of evil is contested — 1,600 years of debate.",
        hardEdges: ["The privation theory has a hard edge: if evil is 'less good,' is genocide just 'much less good'? No — Augustine distinguishes moral evil (the will's distortion) from natural privation (blindness, disease). The student must grapple with whether this distinction holds.", "This is a Christian theodicy. It is also a serious philosophical argument. Teach both layers."],
        reading: [{ heading: "The absence, not the substance", body: "Augustine's answer to the problem of evil: evil is not a thing. It is an absence. Darkness is not a substance — it is the absence of light. Cold is not a substance — it is the absence of heat. Evil is not a substance — it is the absence of good. God did not create evil. Evil is what happens when the will, which was made for the highest good, turns toward a lesser good as if it were the highest. The corrupt official who chooses power over justice is not choosing 'evil' — he is choosing a real good (power) in the wrong way, at the wrong time, for the wrong reason. The evil is in the distortion, not in the thing chosen. This is elegant. It also has a hard edge: if evil is just 'less good,' then genocide is 'much less good.' Augustine's response: moral evil is not a lesser quantity of good — it is a distortion of the will. The distinction between 'less' and 'distorted' is the argument. Whether it holds is 1,600 years of debate." }],
        bigIdea: "Evil is not a thing. It is goodness gone wrong — the will choosing a lesser good as if it were the highest. The distinction between 'less good' and 'distorted' is the argument.",
        tryThis: [{ title: "Test the privation", minutes: 16, steps: ["State Augustine's privation theory: evil is the absence of good, not a substance.", "Apply it to a moral evil (someone betraying a friend for money). Is the betrayal 'less good' or 'distorted will'?", "Apply it to a natural evil (an earthquake). Does the theory work here? Where does it struggle?", "Practice/Reflect: does the privation theory solve the problem of evil, or just reframe it?"] }],
        dinnerQuestion: "Is evil a thing — or is it the absence of a thing? What changes depending on your answer?",
        transfer: [{ label: "AI", note: "Is a model's hallucination an 'evil' or an 'absence of truth'? The privation structure applies: the error is not a substance, it is the lack of grounding." }, { label: "Thinking", note: "The privation theory is the foundation of Western thought about evil — 1,600 years of debate start here." }],
        ifTheySay: [
          { heard: "If evil is just the absence of good, then nothing is really evil — it's just less good.", reply: "Augustine distinguishes between something being less good (weak eyesight) and something being morally evil (choosing to harm). Moral evil is not a lesser quantity of good; it is a distortion of the will. The will was made for the highest good, and when it chooses a lesser good as if it were the highest, that choice is evil. The distinction between 'less' and 'distorted' is the argument." },
          { heard: "This doesn't explain natural disasters — earthquakes aren't caused by anyone's will.", reply: "Correct. The privation theory addresses moral evil, not natural evil. Augustine's account of natural evil is different: the fallen state of creation. Whether you accept that account is a separate question. The privation theory's strength is in moral evil; its weakness is in natural evil. Both are worth seeing." },
        ],
        integrity: "Do not ask the model to resolve the problem of evil. That is the oldest unsolved question in philosophy of religion. The model can explain arguments. It cannot solve them.",
        aiLab: { setup: "After the test.", childDoes: "Ask the model: 'What is the strongest objection to Augustine's privation theory?' Evaluate the objection. Then ask: 'What is the strongest defense?' Evaluate that too.", evaluate: ["Did they distinguish moral from natural evil?", "Can they see both the elegance and the hard edge?"] },
      },
      adult: {
        title: "The Problem of Evil",
        dek: "Augustine said evil is the absence of good. 1,600 years later, the argument is still contested. How do you teach it to a child who has experienced real suffering?",
        objective: "The adult can state the privation theory, evaluate whether it accounts for real suffering, and identify how to teach it without minimizing their child's pain.",
        parentBriefing: "This is the hardest sitting for parents. The problem of evil is not abstract for a child who has lost someone, experienced illness, or witnessed cruelty. Augustine's theory — evil is the absence of good — is a philosophical argument. It is not a pastoral response. Do not use philosophy to comfort a child in real pain. Use presence. The philosophy is for when the pain has a name and the child is ready to think about it.",
        hardEdges: ["Do not use the privation theory to minimize your child's suffering. 'It's just the absence of good' is not comfort — it is abstraction applied to a wound.", "This is a Christian theodicy. It is also a serious philosophical argument. If your family has experienced real loss, the argument may feel insufficient. That is a fair response. Let it be insufficient."],
        reading: [{ heading: "When philosophy meets pain", body: "Augustine's privation theory: evil is not a substance; it is the absence of good. The will chooses a lesser good over the highest, and that distortion is the origin of moral evil. The adult question: how do you teach this to a child who has experienced real suffering? The answer: carefully, and not too early. The privation theory is a philosophical framework for thinking about evil — not a pastoral response to experiencing it. If your child is in pain, they need presence, not philosophy. When the pain has a name and the child is ready to think, the framework is useful: it says evil is not a force equal to good, it is a distortion, a going-wrong. That matters because it means evil is not ultimate — it is parasitic on good. It cannot exist on its own. Whether that is comfort or cold abstraction is your judgment — and your child's. The parent theological humility note: this is one theodicy among many. Augustine's answer is not the only answer. It is the most influential one in Western thought. Understanding it is intellectual history. Living with the problem is human experience. Both matter." }],
        bigIdea: "The privation theory is a framework for thinking about evil — not a pastoral response to experiencing it. Don't confuse the two.",
        tryThis: [{ title: "Hold both", minutes: 10, steps: ["Name one real suffering in your family's life (loss, illness, cruelty).", "Augustine's theory: evil is the absence of good, not a substance. Does this framework help with the suffering — or feel like abstraction?", "The discipline: hold the philosophy and the pain in the same hand. Don't let one erase the other.", "One question: is your child ready for the framework, or do they need presence first?"] }],
        dinnerQuestion: "When suffering is real, is philosophy a help or a distraction — and how do we know which our child needs?",
        transfer: [{ label: "Parenting", note: "Philosophy is for when the pain has a name. Presence is for when it doesn't. Knowing the difference is parenting wisdom." }],
        ifTheySay: [
          { heard: "The privation theory is a word game — calling evil 'less good' doesn't make it less real.", reply: "It is a word game if it stops at the definition. Augustine doesn't stop there — he builds an entire account of the will, of freedom, of the fall. The question is whether that account holds. The privation theory is the entry point, not the argument. The argument is about what the will is and how it goes wrong. That argument is not a word game." },
        ],
        integrity: "If the theodicy is generated, you've let the model answer the problem of evil. That question is 1,600 years old and unsolved. The model can explain. It cannot resolve.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they distinguish framework from comfort?", "Is the suffering named real, not abstract?"] },
      },
    },
  }),
  ...expand({
    slug: "the-two-cities",
    subject: "philosophy",
    unit: "Faith & Reason",
    number: 3,
    bands: ["emerging", "adult"],
    variants: {
      emerging: {
        title: "What Does Your City Love?",
        dek: "Augustine said every society is built on what it loves most. The question is not 'is this society good?' but 'what does this society love?'",
        objective: "The student can state Augustine's two-cities framework and apply it to one institution in their own life.",
        parentBriefing: "This is intellectual history, not catechism. Augustine's two cities: the City of God (love of God) and the City of Man (love of self). These are not geographical — they are spiritual realities running through every society. The framework is theological but the political analysis is portable: what does this institution love most?",
        hardEdges: ["Don't reduce this to 'religion vs. secularism.' Augustine is saying politics is always theological — always shaped by what the society loves most. The question is which love, not whether love is involved.", "Augustine wrote this after the fall of Rome. He is not abstract — he is watching an empire collapse and asking why."],
        reading: [{ heading: "Two loves, two cities", body: "Augustine wrote The City of God after the fall of Rome in 410. People asked: was Christianity to blame? Augustine's answer: empires fall because they are built on self-love. Two loves create two cities: the love of God (even to contempt of self) creates the heavenly city; the love of self (even to contempt of God) creates the earthly city. These are not places on a map. They are spiritual realities that run through every society, every institution, every person. The question is not 'is this society good?' but 'what does this society love most?' A corporation that loves profit serves profit. A school that loves ranking serves ranking. A government that loves power serves power. The framework is theological, but the political analysis works without the theology: every institution is shaped by what it loves most, and that love determines whether it serves people or uses them." }],
        bigIdea: "Every political order is shaped by what it loves most. The question is not 'is this good?' but 'what does this love?'",
        tryThis: [{ title: "Audit the city", minutes: 16, steps: ["Pick an institution you're part of (school, team, government, company).", "Ask: what does this institution love most? (Winning? Profit? Reputation? People?)", "Does that love serve people — or use them?", "Practice/Reflect: which city is this institution building?"] }],
        dinnerQuestion: "What does our school (or team, or country) love most — and does that love serve people or use them?",
        transfer: [{ label: "Civics", note: "Augustine's two cities is the foundation of Western political theology. The question 'what does the state love?' is still live." }, { label: "AI", note: "What does the AI company love? Engagement? Truth? Profit? The answer determines what the model serves." }],
        ifTheySay: [
          { heard: "So we should just give up on politics because the earthly city doesn't matter?", reply: "Augustine didn't give up — he was a bishop working inside the collapse. He is saying the earthly city matters, but it is not ultimate. It is worth working for; it is not worth worshipping. The difference is everything." },
        ],
        integrity: "Do not ask the model what your city should love. That is a political and theological judgment. The model can analyze institutions. It cannot choose your loyalties.",
        aiLab: { setup: "After the audit.", childDoes: "Ask the model: 'What does [institution] love most, based on its behavior?' Compare its analysis to yours.", evaluate: ["Did they apply the framework to a real institution?", "Is the analysis honest or defensive?"] },
      },
      adult: {
        title: "The Parent's City",
        dek: "Your family is a city. What does it love most? Augustine's question, applied to the smallest institution you run.",
        objective: "The adult can apply Augustine's two-cities framework to their own family and evaluate what their family loves most.",
        parentBriefing: "This sitting applies Augustine to the family. Your household is a city. It is shaped by what it loves most. If it loves achievement, it serves achievement. If it loves comfort, it serves comfort. If it loves people, it serves people. The question is honest and uncomfortable. The theological frame is optional; the political analysis is not.",
        hardEdges: ["Don't reduce this to 'family values' politics. Augustine is asking what your household actually serves — not what it says it serves.", "The gap between what you say your family loves and what it actually loves is the sitting. That gap is where the earthly city hides."],
        reading: [{ heading: "The smallest city", body: "Augustine's two cities run through every institution — including the family. Your household is a city. It has a love that shapes it. If it loves achievement above all, your children learn they are their grades. If it loves comfort, they learn that discomfort is the enemy. If it loves reputation, they learn that image matters more than truth. If it loves people — their actual flourishing, not their performance — they learn that they are worth something regardless of what they produce. The question Augustine asks of empires, you can ask of your dinner table: what does this city love most? Not what does it say it loves. What does it actually serve — shown by where the time goes, where the money goes, what gets praised, what gets punished. The parent theological humility note: this is a theological frame (love of God vs. love of self) applied to domestic life. A secular parent can translate: what does your family actually serve — and is it what you want to serve? The question is portable. The answer is yours." }],
        bigIdea: "Your family is a city. What it loves most is what it serves. The gap between what you say and what you actually serve is where the work is.",
        tryThis: [{ title: "Audit your city", minutes: 10, steps: ["Ask: what does our family actually love most? (Look at where time, money, praise, and punishment go — not what we say.)", "Is what we love serving our children — or using them?", "The gap between what we say we love and what we actually love: name it.", "One adjustment: move one thing from 'what we say' to 'what we actually serve.'"] }],
        dinnerQuestion: "What does our family actually love most — and is it what we want to love most?",
        transfer: [{ label: "Parenting", note: "Your children learn what to love by watching what you serve, not by hearing what you preach." }],
        ifTheySay: [
          { heard: "This is just 'render unto Caesar' — keep religion out of politics.", reply: "It is the opposite. Augustine is saying politics is always theological — it is always shaped by what the society loves most. The question is not whether religion is in politics but which love is driving it. A secular state that loves power is not neutral; it is the earthly city in different clothes." },
        ],
        integrity: "If the family audit is generated, you've outsourced the most uncomfortable domestic question: what do we actually serve?",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they name the gap between stated and actual love?", "Is the adjustment specific?"] },
      },
    },
  }),
  ...expand({
    slug: "the-five-ways",
    subject: "philosophy",
    unit: "Faith & Reason",
    number: 4,
    bands: ["emerging", "adult"],
    variants: {
      emerging: {
        title: "Five Questions About Reality",
        dek: "Aquinas's Five Ways are not 'prove God or admit defeat.' They are: look at the world carefully and ask — is it self-explanatory, or does it point beyond itself?",
        objective: "The student can state one of the Five Ways and evaluate whether it establishes that reality points beyond itself.",
        parentBriefing: "This is intellectual history, not catechism. The Five Ways are the most misunderstood passage in Aquinas. They are not five independent proofs you check off. They are five starting points that converge on a single question: is the world self-explanatory, or does it require a ground beyond itself? Teach the question, not the conclusion.",
        hardEdges: ["Do not teach the Five Ways as 'five proofs for God.' That is a caricature. Teach them as five questions about whether reality is self-explanatory.", "The Ways are philosophically contested. Hume and Kant challenged them. Modern physics has reframed them. They are not settled — and studying unsettled arguments is the discipline."],
        reading: [{ heading: "The five questions", body: "Aquinas's Five Ways, from the Summa Theologiae: (1) Motion — things move, and nothing moves itself; there must be an unmoved mover. (2) Causation — everything is caused by something else; there must be a first cause. (3) Contingency — things exist but need not; there must be something that exists necessarily. (4) Gradation — things are more or less good, true, beautiful; there must be a maximum. (5) Teleology — things act for ends, even without awareness; there must be an intelligence directing them. These are not five proofs you check off. They are five questions: is motion self-explanatory? Is causation? Is existence? Is value? Is purpose? Each starts with something obvious (things move, things exist) and asks: what would have to be true for this to be possible? Whether the answers work is 750 years of debate. The questions are worth asking either way." }],
        bigIdea: "The Five Ways are not 'prove God exists.' They are 'is the world self-explanatory, or does it point beyond itself?' Five angles on one question.",
        tryThis: [{ title: "Test one Way", minutes: 16, steps: ["Pick one of the Five Ways (the Third — contingency — is the most accessible: things exist but need not).", "State it: things exist but could not have. Why is there something rather than nothing?", "Aquinas says: there must be something that exists necessarily. Is that a logical requirement or a leap?", "Practice/Reflect: does this establish that reality points beyond itself — or just that we don't know the answer?"] }],
        dinnerQuestion: "Why is there something rather than nothing — and is 'we don't know' a better answer than 'God'?",
        transfer: [{ label: "Science", note: "The Third Way (contingency) is the cosmological argument — why is there something rather than nothing? Physics addresses mechanism, not ground." }, { label: "Greeks", note: "The First Way (motion) is Aristotle's unmoved mover in Christian dress. Aquinas baptized Aristotle." }],
        ifTheySay: [
          { heard: "Science explains motion and causation — we don't need God for that.", reply: "Aquinas is not saying 'science can't explain this, so God did it.' He is saying: science explains how things move and are caused, but it does not explain why there is motion or causation at all. Why is there something rather than nothing? Science studies the mechanism; Aquinas asks about the ground of the mechanism. Whether his answer works is a separate question." },
          { heard: "These are just the cosmological argument with extra steps.", reply: "They are related, but each starts from a different feature of reality. The Third Way (contingency) is closest to the modern cosmological argument; the Fifth (teleology) is furthest. They are not redundant — they are five angles on a single question." },
        ],
        integrity: "Do not ask the model to prove or disprove God. The model can explain arguments. The judgment — does reality point beyond itself? — is yours.",
        aiLab: { setup: "After testing one Way.", childDoes: "Ask the model: 'What is the strongest objection to the Third Way?' Evaluate it. Then ask: 'What is the strongest defense?' Evaluate that too.", evaluate: ["Can they state one Way accurately?", "Did they distinguish question from conclusion?"] },
      },
      adult: {
        title: "Aquinas's Questions for Adults",
        dek: "The Five Ways are 750 years old and still debated. How do you teach them to a child in a post-Darwinian world without pretending they're settled?",
        objective: "The adult can state one of the Five Ways, evaluate a post-Darwinian objection, and identify how to teach the argument without presenting it as proof.",
        parentBriefing: "The parent theological humility note: the Five Ways are philosophically contested. Hume and Kant challenged the causal and cosmological arguments. Darwin challenged the Fifth Way (teleology). They are not settled. They are worth studying because they are among the most careful arguments ever made for the claim that reality points beyond itself. Whether they succeed is a live question. Teach the question, not the answer.",
        hardEdges: ["Don't present the Five Ways as 'proofs that God exists.' They are arguments that reality points beyond itself. The conclusion (that the ground is God) is a theological add-on, not the philosophical argument.", "Darwin challenged the Fifth Way specifically. The first three (motion, causation, contingency) are untouched by Darwin. Don't let the student think Darwin refuted all five."],
        reading: [{ heading: "The post-Darwinian parent", body: "Aquinas's Five Ways: five questions about whether reality is self-explanatory. The adult question: how do you teach these in a world where Darwin challenged the design argument (Fifth Way) and modern physics reframed motion and causation? The answer: honestly. The Fifth Way (teleology — things act for ends) was challenged by Darwin's natural selection, which explains apparent design without a designer. But the first three Ways (motion, causation, contingency) are about the existence of the universe, not its design. Darwin does not address why there is something rather than nothing. The Fifth Way is weakened; the first three are not. Whether that matters is the student's judgment. The parent's job: teach the arguments, teach the objections, let the child evaluate. The model can explain both sides. The judgment — does reality point beyond itself? — is the child's, not the model's, not yours." }],
        bigIdea: "Teach the questions, not the answers. The Five Ways are 750 years old and still debated. That's not a failure — that's philosophy working.",
        tryThis: [{ title: "Teach one Way honestly", minutes: 10, steps: ["Pick one Way (the Third — contingency — is the strongest for a post-Darwinian world).", "State the argument: things exist but need not. Why is there something rather than nothing?", "State the strongest objection. State the strongest defense.", "Ask your child: which is more convincing — and why? Listen. Don't correct."] }],
        dinnerQuestion: "Why is there something rather than nothing — and is 'I don't know' an honest answer or an avoidance?",
        transfer: [{ label: "Parenting", note: "Teaching your child to hold a 750-year-old question without resolving it is the practice of intellectual humility." }],
        ifTheySay: [
          { heard: "Aquinas's arguments don't work in a post-Darwinian world.", reply: "Darwin challenged the Fifth Way (teleology) specifically — natural selection explains apparent design without a designer. But the first three Ways (motion, causation, contingency) are about the existence of the universe, not its design. Darwin does not address why there is something rather than nothing. The Fifth Way is weakened; the first three are untouched. Whether that matters is the student's judgment." },
        ],
        integrity: "If the proof or disproof is generated, you've let the model settle a 750-year-old debate. The model can explain. It cannot settle.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they distinguish question from conclusion?", "Is the objection honest, not dismissive?"] },
      },
    },
  }),
  ...expand({
    slug: "two-wings",
    subject: "philosophy",
    unit: "Faith & Reason",
    number: 5,
    bands: ["emerging", "adult"],
    variants: {
      emerging: {
        title: "Two Wings of One Flight",
        dek: "Aquinas said faith and reason are two wings of the same bird. Truth cannot contradict truth. But what happens when they seem to?",
        objective: "The student can state Aquinas's faith-reason synthesis, explain the principle 'truth cannot contradict truth,' and evaluate one case of apparent conflict.",
        parentBriefing: "This is intellectual history, not catechism. Aquinas's principle: truth cannot contradict truth. If reason and faith seem to conflict, something has been misunderstood — in the reasoning, in the interpretation of faith, or both. This is a methodological rule, not a guarantee. Teach it as a discipline, not a solution.",
        hardEdges: ["'Truth cannot contradict truth' is a methodological rule, not a guarantee. It says: when there is conflict, look for the error. It does not say 'there will never be conflicts.'", "Aquinas's synthesis is a Catholic achievement. Other traditions have different accounts. Teach it as the most systematic attempt — not the only one."],
        reading: [{ heading: "The discipline of holding both", body: "Aquinas's principle: faith and reason are two wings of a single flight. Truth cannot contradict truth. If reason discovers something and faith reveals something, and both are true, they cannot conflict. Apparent conflicts mean one or both have been misunderstood. Reason can demonstrate some truths faith also reveals (God's existence). Reason cannot demonstrate other truths faith reveals (Trinity, Incarnation) — but these are above reason, not against it. The discipline: when faith and reason seem to conflict, don't collapse one into the other. Look for the misunderstanding — in the reasoning, in the interpretation, or both. This is harder than it sounds. It requires holding two sources of truth in tension without dismissing either. The warfare thesis (faith vs. reason) is easier. Aquinas offers the harder path: hold both, and when they conflict, assume the error is in the understanding, not in the truth." }],
        bigIdea: "The warfare thesis (faith vs. reason) is not the only option. Aquinas offers a third: hold both, and when they conflict, look for the error in the understanding.",
        tryThis: [{ title: "Find the conflict", minutes: 16, steps: ["Name one case where faith (or belief) and reason seem to conflict (evolution and Genesis, suffering and a loving God, free will and omniscience).", "Aquinas's rule: if both are true, the conflict is in the understanding. Where is the misunderstanding?", "Can you find it — or does the conflict seem real?", "Practice/Reflect: is Aquinas's rule a discipline or a dodge? When does 'look for the error' become honest work, and when does it become avoidance?"] }],
        dinnerQuestion: "When faith and reason seem to conflict, is 'look for the misunderstanding' honest discipline or avoidance?",
        transfer: [{ label: "AI", note: "A model can present both sides. Holding them in tension without collapsing one is the human discipline." }, { label: "Thinking", note: "The warfare thesis is the easy version. The synthesis is the hard version. Both are live." }],
        ifTheySay: [
          { heard: "If faith and reason can't contradict, then faith is just reason with extra steps.", reply: "No. Aquinas says some truths are accessible to reason (God exists), and some are accessible only to faith (God is triune). The first group can be reached without faith; the second cannot. The two wings overlap but are not identical. Reason gets you to the door; faith opens it." },
          { heard: "This only works if you already believe.", reply: "The principle 'truth cannot contradict truth' works whether or not you believe. It is a logical claim: if two truths conflict, one is not true. The application to faith and reason requires believing that faith reveals truth — but the principle itself is available to anyone. You can study Aquinas's method without accepting his premises. That is what intellectual history is." },
        ],
        integrity: "Do not ask the model to resolve the faith-reason conflict. The model can explain both sides. Holding them in tension is the discipline Aquinas described — and it is yours, not the model's.",
        aiLab: { setup: "After finding the conflict.", childDoes: "Ask the model to present both sides of the conflict. Then ask: 'Where might the misunderstanding be?' Evaluate its answer.", evaluate: ["Can they state Aquinas's principle?", "Did they find a real conflict or a generic one?"] },
      },
      adult: {
        title: "The Synthesis That Won't Die",
        dek: "Aquinas said faith and reason are compatible. Galileo and Darwin challenged it. It's been revised repeatedly. Does it survive — and how do you teach it?",
        objective: "The adult can evaluate whether Aquinas's faith-reason synthesis survives Galileo and Darwin and identify how to teach it as a living tradition, not a settled answer.",
        parentBriefing: "The parent theological humility note: Aquinas's synthesis is a Catholic achievement. Other traditions have different accounts. The academy teaches it as the most systematic attempt to reconcile faith and reason — not as the only possible account. A parent from a different tradition (or no tradition) should feel free to teach this as intellectual history while offering their own account.",
        hardEdges: ["Don't present the synthesis as settled. It has been challenged repeatedly — Galileo, Darwin, biblical criticism. It survives in revised form. Whether the revision holds is a live question.", "If you are a secular parent, don't dismiss the synthesis because you reject faith. The principle — truth cannot contradict truth — is a logical claim available to anyone. The application to faith is optional. The principle is not."],
        reading: [{ heading: "The synthesis after the challenges", body: "Aquinas's synthesis: faith and reason are two wings of one flight. Truth cannot contradict truth. When they conflict, look for the misunderstanding. This synthesis has been challenged repeatedly. Galileo challenged a particular interpretation of Scripture, not the principle itself. Darwin challenged a particular reading of Genesis, not the claim that faith and reason are compatible. Biblical criticism challenged literal readings, not the methodological rule. The synthesis has been revised each time — and it survives in revised form. The adult question: does it survive in a form worth teaching? Most philosophers say some form of compatibility is possible. The warfare thesis (faith vs. reason) is one option. The synthesis is another. The separatist option (faith and reason address different domains, never interact) is a third. Teaching your child all three — and letting them choose — is the academy's stance. The parent's job: present the options honestly, including the one you don't hold." }],
        bigIdea: "The synthesis has been challenged and revised. It survives in modified form. Teaching the options — including the ones you reject — is the discipline.",
        tryThis: [{ title: "Present the options", minutes: 10, steps: ["Name the three options: warfare (faith vs. reason), synthesis (two wings), separation (different domains).", "Which do you hold? Which do you reject?", "Can you present the one you reject honestly to your child?", "One conversation: ask your child which option makes sense to them. Listen."] }],
        dinnerQuestion: "Are faith and reason at war, in sync, or on different tracks — and how do we teach our child to hold the question?",
        transfer: [{ label: "Parenting", note: "Presenting options you reject, honestly, is the hardest and most important teaching move in this unit." }],
        ifTheySay: [
          { heard: "The faith-reason synthesis collapsed with Galileo and Darwin.", reply: "It was challenged, not collapsed. Galileo challenged a particular interpretation of Scripture, not the principle that truth cannot contradict truth. Darwin challenged a particular reading of Genesis, not the claim that faith and reason are compatible. The synthesis has been revised repeatedly. Whether it survives in its Aquinas form is a live question. Whether some form of compatibility is possible is a different question — and most philosophers say yes." },
        ],
        integrity: "If the synthesis evaluation is generated, you've let the model choose your epistemology. The choice of how faith and reason relate is yours.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they present all three options honestly?", "Is their preferred option chosen, not inherited?"] },
      },
    },
  }),
  ...expand({
    slug: "natural-law",
    subject: "philosophy",
    unit: "Faith & Reason",
    number: 6,
    bands: ["emerging", "adult"],
    variants: {
      emerging: {
        title: "What Is a Human For?",
        dek: "Aquinas said morality is not arbitrary — it's embedded in human nature. If you know what a human is for, you know what a human should do. But what is a human for?",
        objective: "The student can state Aquinas's natural law theory, identify one objection from the variability of human nature, and evaluate whether the theory survives.",
        parentBriefing: "This is intellectual history, not catechism. Natural law: human beings can, by reason alone, discover moral principles embedded in human nature. The first principle: good is to be done and evil avoided. Everything else follows from what we are. The critique: human nature is not fixed. The student must grapple with this honestly.",
        hardEdges: ["Natural law is the most contested part of Aquinas today. The critique: 'human nature' is not fixed — it evolves, varies across cultures, includes cruelty. If nature includes both, which part is 'natural law'?", "Don't present natural law as 'Catholic morality.' Aquinas derived it from Aristotle and Stoic law, not from Scripture. The method is available to anyone."],
        reading: [{ heading: "The nature in the law", body: "Aquinas's natural law: human beings can, by reason alone, discover moral principles embedded in human nature. The first principle is self-evident: good is to be done and evil avoided. Everything else follows from what we are: rational beings whose nature points toward certain goods — life, knowledge, society, procreation, truth. If human beings have a nature, then some actions fulfill that nature and some frustrate it. The question 'what should I do?' becomes 'what is a human being for?' — which is Aristotle's final cause applied to ethics. The critique: human nature is not fixed. It evolves. It varies across cultures. It includes capacities for cruelty as well as kindness. If nature includes both, which part is 'natural law'? Aquinas's response: natural law is not 'what humans do' but 'what fulfills what humans are.' Violence is common; it does not fulfill our rational nature. The gap between what is common and what is fulfilling is the argument. Whether the gap holds is the question." }],
        bigIdea: "Morality is not arbitrary if human beings have a nature. The question 'what should I do?' becomes 'what is a human for?'",
        tryThis: [{ title: "Test the law", minutes: 16, steps: ["State Aquinas's first principle: good is to be done, evil avoided. Is this self-evident or circular?", "Name one human capacity that points at a good (reason → knowledge, sociability → community).", "Name one human capacity that is common but not fulfilling (violence, deception).", "Practice/Reflect: is natural law 'what humans do' or 'what fulfills what humans are'? Does the distinction hold?"] }],
        dinnerQuestion: "If human nature includes both kindness and cruelty, which part is 'natural law' — and how do you decide?",
        transfer: [{ label: "Civics", note: "Natural law is the foundation of human rights language — universal moral principles discoverable by reason." }, { label: "Greeks", note: "Aquinas's natural law is Aristotle's final cause applied to ethics. 'What is a human for?' connects the two units." }],
        ifTheySay: [
          { heard: "If morality comes from human nature, and human nature includes violence, then violence is natural and therefore moral.", reply: "Aquinas distinguishes between what is natural (fulfills the human essence as rational being) and what is merely common (happens frequently). Violence is common; it does not fulfill our rational nature. Natural law is not 'what humans do' but 'what fulfills what humans are.' The gap between the two is the argument." },
        ],
        integrity: "Do not ask the model what natural law requires. The model can explain the theory. Applying it to real moral questions is your judgment.",
        aiLab: { setup: "After the test.", childDoes: "Ask the model: 'What is the strongest objection to natural law theory?' Evaluate it. Then ask: 'What is the strongest defense?'", evaluate: ["Did they distinguish common from fulfilling?", "Is the objection real, not a strawman?"] },
      },
      adult: {
        title: "Natural Law and the Parent",
        dek: "Aquinas said morality is embedded in human nature. But whose account of human nature? And how do you teach it without imposing your conclusions?",
        objective: "The adult can evaluate whether natural law provides a usable moral framework for parenting and identify how to teach it without dictating conclusions.",
        parentBriefing: "The parent theological humility note: natural law theory is a living tradition in Catholic social teaching. It is also invoked in secular debates (human rights, just war, bioethics). The academy teaches the structure of the argument, not the policy conclusions. A parent who disagrees with Catholic social teaching can still engage the argument. The method is not proprietary to Catholicism.",
        hardEdges: ["Don't present natural law conclusions as settled. The structure — reason discovers moral principles in human nature — is the method. The specific conclusions (contraception, same-sex marriage, economic justice) are contested even within the tradition.", "If your child asks a specific moral question, don't use natural law as a trump card. Use it as a framework: what does human nature point at? Let the child reason."],
        reading: [{ heading: "The framework, not the conclusion", body: "Aquinas's natural law: reason discovers moral principles embedded in human nature. The first principle: good is to be done, evil avoided. The adult question: how do you use this framework without imposing your conclusions? The answer: teach the method, not the results. The method: identify what human nature points at (life, knowledge, society, truth). Ask whether a specific action fulfills or frustrates that nature. Reason from the nature to the action. The results: contested — even within Catholicism, different thinkers reach different conclusions on specific issues. The framework's strength: it grounds morality in something beyond preference. The framework's weakness: 'human nature' is contested, and the contest is where the real work happens. Your child needs the framework so they can do the work — not so you can hand them the answers. The parent's job: teach the method. Let the child reason. Accept that their conclusions may differ from yours." }],
        bigIdea: "Teach the method, not the conclusions. Natural law gives a framework for moral reasoning. The specific answers are the child's to reason toward.",
        tryThis: [{ title: "Use the framework", minutes: 10, steps: ["Pick a moral question your family faces (screen time, honesty, treatment of others).", "Apply natural law: what does human nature point at? Does this action fulfill or frustrate it?", "Did you reach your existing conclusion — or a new one?", "One conversation: ask your child to apply the framework. Let them reason. Don't correct."] }],
        dinnerQuestion: "If morality is embedded in human nature, what does our nature point at — and are we fulfilling it?",
        transfer: [{ label: "Parenting", note: "Teaching a framework and letting your child reach their own conclusions is the hardest and most honest form of moral education." }],
        ifTheySay: [
          { heard: "Natural law is just Catholic morality in philosophical clothing.", reply: "It is both. Aquinas derived it from Aristotle and Stoic law, not from Scripture. The Catholic Church adopted it. The structure — reason discovers moral principles in human nature — is available to anyone. Whether you accept the specific conclusions depends on your account of human nature. The method is not proprietary to Catholicism." },
        ],
        integrity: "If the moral conclusion is generated, you've let the model do the moral reasoning. Natural law is a framework for human reasoning, not machine reasoning.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they separate framework from conclusions?", "Is the moral question real, not abstract?"] },
      },
    },
  }),
  ...expand({
    slug: "recapitulation",
    subject: "philosophy",
    unit: "Faith & Reason",
    number: 7,
    bands: ["emerging", "adult"],
    variants: {
      emerging: {
        title: "Christ as the New Adam",
        dek: "Irenaeus said salvation is not a deal — it is a restoration. Christ walks through every stage of human life and redeems each one. Is that theology or a philosophy of history?",
        objective: "The student can state Irenaeus's recapitulation theory, distinguish it from legal models of salvation, and evaluate it as a philosophical claim about history.",
        parentBriefing: "This is intellectual history, not catechism. Irenaeus's recapitulation: Christ sums up and restores all of creation. Where Adam failed, Christ succeeded. This is a theology of cosmic restoration — not just personal salvation. A secular student can engage it as a philosophy of history: human beings fall short, and the restoration is fulfillment, not escape.",
        hardEdges: ["Irenaeus wrote against Gnostics who said the material world was evil. His answer: creation is good, the body is good, Christ redeems the body. This anti-dualist stance is philosophically significant regardless of theological commitment.", "Don't present recapitulation as 'Christian mythology.' It is a theological argument with a portable structure: fall and restoration as the pattern of reality."],
        reading: [{ heading: "Restoration, not escape", body: "Irenaeus's recapitulation: Christ 'recapitulates' — sums up, gathers, restores — all of creation. Where Adam failed, Christ succeeded. Where death entered through a tree (the cross of Adam's fall), life entered through a tree (the cross of Christ). Salvation is not a legal transaction (debt paid, punishment absorbed). It is a restoration: Christ walks through every stage of human life — birth, childhood, temptation, suffering, death — and redeems each one. Irenaeus wrote against Gnostics who said the material world was evil and salvation was escape from the body. His answer: creation is good, the body is good, and Christ came to redeem the body, not abandon it. This is the most important argument for the goodness of creation in the early Church. The philosophical structure: human beings fall short of what they are made for, and the restoration is not escape but fulfillment. That structure exists outside Christianity — the Stoic return to nature, the Buddhist path, the secular narrative of progress. Irenaeus gives it a specific Christian shape. The structure is wider than the theology." }],
        bigIdea: "Salvation is not a deal; it is a restoration. The structure — fall and restoration — is wider than any single theology.",
        tryThis: [{ title: "Find the structure", minutes: 16, steps: ["State Irenaeus's recapitulation: Christ restores what Adam broke. Salvation is restoration, not transaction.", "Find the same structure outside Christianity (Stoic return to nature, Buddhist path, secular progress).", "What makes Irenaeus's version different? What makes it the same?", "Practice/Reflect: is 'fall and restoration' a theological claim or a philosophical pattern? Can it be both?"] }],
        dinnerQuestion: "Is 'fall and restoration' a Christian story — or a human story that Christianity tells in one specific way?",
        transfer: [{ label: "Greeks", note: "Irenaeus's anti-dualism (creation is good, body is good) echoes Aristotle's final cause — the physical world has a purpose." }, { label: "AI", note: "The anti-dualist stance matters for AI: if the physical world is good, then embodied AI (robotics) is not a corruption but a continuation." }],
        ifTheySay: [
          { heard: "This is just Christian mythology — Adam and Christ as opposing characters.", reply: "It is a story, but it is also a theological argument: the pattern of fall-and-restoration is the structure of reality, not an accident. Whether you read it as theology or as a philosophical claim about history and purpose, the structure is worth understanding." },
        ],
        integrity: "Do not ask the model to evaluate whether recapitulation is true. The model can explain the argument. Whether the pattern is real is your judgment.",
        aiLab: { setup: "After finding the structure.", childDoes: "Ask the model: 'What is the difference between Irenaeus's restoration and the Stoic return to nature?' Evaluate the answer.", evaluate: ["Did they find the structure outside Christianity?", "Can they distinguish Irenaeus's version from others?"] },
      },
      adult: {
        title: "The Pattern of Falling and Rising",
        dek: "Irenaeus said the pattern of reality is fall and restoration. As a parent, you live this pattern daily. Is it theology — or just what life does?",
        objective: "The adult can identify the fall-and-restoration pattern in their own family life and evaluate whether it is a theological claim or a phenomenological observation.",
        parentBriefing: "The parent theological humility note: Irenaeus's recapitulation is a theology of cosmic restoration. A secular parent can teach it as the Christian alternative to dualism — a frame that says the physical world matters, bodies matter, history matters. Whether you accept the theology, the anti-dualist stance is philosophically significant.",
        hardEdges: ["Don't impose the theology on your family's experience. The pattern (fall and restoration) is observable. What it means is contested.", "If your family is in a 'fall' phase — crisis, loss, conflict — don't use theology to promise restoration. Use presence. The pattern may hold, but the timeline is not yours to guarantee."],
        reading: [{ heading: "The family pattern", body: "Irenaeus's recapitulation: Christ restores what Adam broke. The pattern: fall and restoration. The adult version: your family lives this pattern. A child fails (the fall). The family works through it (the restoration). A marriage hits a crisis (the fall). The couple rebuilds (the restoration). A career collapses (the fall). A new path emerges (the restoration). Irenaeus says this pattern is the structure of reality — not an accident, but the shape of how things work. You can read that theologically (God is in the restoration) or phenomenologically (the pattern is observable in human life). Either way, the pattern is real. The parenting question: do you name the pattern for your children? When they fall, do you say 'this is the fall, and the restoration is coming' — or do you just help them through it? Irenaeus would say: naming the pattern gives the fall meaning. The secular version: naming the pattern gives the fall context. Either way, the child learns that falling is not the end of the story." }],
        bigIdea: "The pattern of fall and restoration is observable in every family. Naming it gives the falling meaning — theologically or phenomenologically.",
        tryThis: [{ title: "Name the pattern", minutes: 10, steps: ["Name one 'fall' in your family's history (a crisis, a loss, a failure).", "Name the 'restoration' that followed — or is still in progress.", "Was the restoration something you made, something that happened, or both?", "One conversation: tell your child about the fall and the restoration. Name the pattern."] }],
        dinnerQuestion: "When has our family fallen and been restored — and was the restoration something we made or something that came to us?",
        transfer: [{ label: "Parenting", note: "Naming the pattern of fall and restoration teaches children that falling is not final. That is the practical wisdom of Irenaeus." }],
        ifTheySay: [
          { heard: "Irenaeus's theology is pre-modern — recapitulation doesn't make sense without the Adam-Christ typology.", reply: "The typology is the Christian form, but the underlying claim is portable: human beings fall short of what they are made for, and the restoration is not escape but fulfillment. That structure exists outside Christianity. Irenaeus gives it a specific Christian shape. The structure is wider than the theology." },
        ],
        integrity: "If the pattern interpretation is generated, you've let the model name your family's story. That story is yours to tell.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they identify a real fall and restoration?", "Is the pattern named honestly, not imposed?"] },
      },
    },
  }),
  ...expand({
    slug: "the-hazelnut",
    subject: "philosophy",
    unit: "Faith & Reason",
    number: 8,
    bands: ["emerging", "adult"],
    variants: {
      emerging: {
        title: "The Hazelnut and the Whole World",
        dek: "Julian of Norwich saw something the size of a hazelnut and understood it was all that is made. 'All shall be well.' She said this during the Black Death. Not optimism — something harder.",
        objective: "The student can state Julian's hazelnut vision, explain her claim that 'all shall be well,' and distinguish hope from optimism.",
        parentBriefing: "This is intellectual history, not catechism. Julian of Norwich is the first woman to write a book in English. She is a mystic, not a systematic theologian. Her argument is experiential — from visions, not premises. Teach her as a serious thinker whose experiential theology complements Augustine's philosophical theology and Aquinas's systematic theology. Different modes of knowing.",
        hardEdges: ["Julian's 'all shall be well' is not naïve optimism. She lived through the Black Death. Her claim is 'the worst is not the end,' not 'everything is fine.' The distinction between optimism and hope is the sitting.", "Julian says sin is behovely — necessary for the process of redemption. This does not mean sin is good. It means God uses it for good. The distinction is the argument."],
        reading: [{ heading: "The smallest thing, the hardest claim", body: "Julian of Norwich, in her Revelations of Divine Love, describes a vision: she saw something the size of a hazelnut in her hand. She asked what it was. The answer: 'It is all that is made.' Three properties: God made it, God loves it, God keeps it. The whole universe, small enough to fit in a hand. From this vision — the radical smallness of creation and the radical tenderness of God — Julian builds her answer to the problem of evil: 'All shall be well, and all shall be well, and all manner of thing shall be well.' She said this in the 14th century, during the Black Death, through a century of plague, war, and famine. This is not optimism. It is hope — the claim that the worst is not the last word. She calls sin behovely — necessary, useful — not because evil is good, but because the fall creates the conditions for a deeper redemption. A broken bone that heals stronger is not good because it broke. The breaking was bad; the healing is the good. Julian says God works through the breaking toward a healing that would not have been possible without it. Whether you accept that is your call. The distinction between 'sin is good' and 'God uses sin for good' is the argument." }],
        bigIdea: "The smallest thing, held in love, is the whole universe. And the worst thing is not the end. Hope is not optimism — it is the claim that the worst is not the last word.",
        tryThis: [{ title: "Distinguish hope from optimism", minutes: 16, steps: ["Write Julian's claim: 'All shall be well.' She said this during the Black Death.", "Optimism says: 'Everything is fine.' Hope says: 'The worst is not the end.' Which is Julian claiming?", "Apply the distinction to something hard in your life. Is optimism possible? Is hope?", "Practice/Reflect: is 'the worst is not the end' a theological claim, a psychological claim, or both?"] }],
        dinnerQuestion: "Is 'all shall be well' optimism or hope — and what is the difference when things are actually hard?",
        transfer: [{ label: "AI", note: "A model generates optimistic text by default. Hope — the claim that the worst is not final — requires a perspective the model doesn't have." }, { label: "Thinking", note: "The distinction between optimism and hope is the most practical philosophical tool in this unit." }],
        ifTheySay: [
          { heard: "'All shall be well' is just toxic positivity.", reply: "Julian said it while looking at a crucifix, in a century of plague. This is not positivity. It is the claim that the worst thing that can happen — death, torture, sin — is not the last word. The distinction between 'everything is fine' (which is false) and 'the worst is not the end' (which is a theological claim) is the whole sitting. If you collapse the two, you've missed her." },
          { heard: "How can sin be 'necessary'? That makes evil a good thing.", reply: "Julian says sin is behovely — necessary for the process of redemption, not good in itself. The analogy: a broken bone that heals stronger is not 'good because it broke.' The breaking was bad; the healing is the good. Julian says God works through the breaking toward a healing that would not have been possible without it. Whether you accept that is your call." },
        ],
        integrity: "Do not ask the model to generate devotional content about hope. Ask it to explain Julian's argument. The model explains; the human hopes (or doesn't).",
        aiLab: { setup: "After the distinction exercise.", childDoes: "Ask the model: 'What is the difference between optimism and hope, philosophically?' Evaluate its answer against Julian's.", evaluate: ["Did they distinguish optimism from hope?", "Can they see Julian's claim as more than positivity?"] },
      },
      adult: {
        title: "Julian's Hope",
        dek: "Your family will go through hard things. Julian's claim — 'the worst is not the end' — is not optimism. It is the hardest kind of hope. How do you teach it?",
        objective: "The adult can distinguish hope from optimism, evaluate Julian's claim in the context of their own family's suffering, and identify how to teach hope without false comfort.",
        parentBriefing: "The parent theological humility note: Julian is a mystic, not a systematic theologian. Her argument is experiential. A secular parent can engage her claim — that the worst is not the end — as a phenomenological observation about resilience and meaning-making, without accepting the theological frame (God's love as the guarantee). The distinction between hope and optimism is portable. The theology is optional.",
        hardEdges: ["Don't use Julian's hope to dismiss your family's suffering. 'All shall be well' is a claim about the end, not about the middle. In the middle, things are not well, and saying they are is toxic.", "If your family is in crisis, Julian's claim may feel impossible. That is fair. Hope is not required — it is offered. The sitting is about understanding the offer, not accepting it on command."],
        reading: [{ heading: "Hope in the middle", body: "Julian of Norwich: 'All shall be well, and all shall be well, and all manner of thing shall be well.' She said this during the Black Death. She saw the whole world as a hazelnut — small, held, loved. Her claim is not 'everything is fine.' It is 'the worst is not the end.' The adult version: your family will go through hard things — illness, loss, conflict, failure. Julian's claim is that the hard thing is not the last word. Not that it will be fixed. Not that it will make sense. That it is not the end. The difference between optimism ('things will get better') and hope ('the worst is not final') is the difference between a prediction and a stance. Optimism is a prediction about outcomes. Hope is a stance toward reality — a refusal to let the worst be the last word, regardless of outcomes. The parenting question: how do you teach hope without false comfort? By being honest about the middle: things are hard, they may not get better, and the worst is still not the end. That is Julian's position. It is not easy. It is not optimism. It is the hardest kind of hope — the kind that survives the Black Death." }],
        bigIdea: "Hope is not a prediction that things will improve. It is a refusal to let the worst be the last word. That is what Julian teaches — and it is teachable with or without the theology.",
        tryThis: [{ title: "Find your hope", minutes: 10, steps: ["Name one hard thing your family is in the middle of right now.", "Optimism says: 'It will get better.' Hope says: 'The worst is not the end.' Which can you honestly offer?", "Julian's claim: the hard thing is not the last word. Can you hold that — or does it feel false right now?", "One conversation: tell your child honestly. Things are hard. They may not get better soon. And the worst is not the end. That is hope, not comfort."] }],
        dinnerQuestion: "What is the hardest thing our family is facing — and is 'the worst is not the end' honest hope or false comfort right now?",
        transfer: [{ label: "Parenting", note: "Teaching the difference between optimism and hope is one of the most important things you can give your child." }],
        ifTheySay: [
          { heard: "This is mysticism, not philosophy. Why is it in the academy?", reply: "Because the question Julian addresses — how can a good God permit evil? — is the hardest question in the philosophy of religion, and Julian's answer is different from Augustine's (evil is privation) and Aquinas's (evil is permitted for greater good). Julian says evil is behovely — woven into the process of redemption itself. That is a third option. Whether it works is a live question. The academy teaches options, not answers." },
        ],
        integrity: "If the hope is generated, you've let the model manufacture a stance. Hope is a position you take, not a text you generate.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they distinguish hope from optimism?", "Is the family's hard thing real and named?"] },
      },
    },
  }),
  ...expand({
    slug: "the-trinity-debate",
    subject: "philosophy",
    unit: "Faith & Reason",
    number: 9,
    bands: ["emerging", "adult"],
    variants: {
      emerging: {
        title: "One What, Three Whos",
        dek: "The Trinity is not 1+1+1=1. The Cappadocians said: one essence, three persons — where 'person' means mode of existence, not individual. Is that metaphysics or mysticism?",
        objective: "The student can state the Cappadocian formula (one ousia, three hypostases), explain why 'person' does not mean 'individual,' and evaluate the philosophical claim that reality is relational.",
        parentBriefing: "This is intellectual history, not catechism. The Trinity is the hardest doctrine in Christianity. The Cappadocians gave the framework: one essence, three persons. 'Person' here means 'mode of existence,' not 'individual.' The philosophical claim: reality is fundamentally relational. A non-Christian student can engage this as metaphysics — the question of whether relationship is prior to substance.",
        hardEdges: ["Don't pretend the Trinity is simple. The Cappadocians spent decades arguing about one letter (homoousios vs homoiousios). Serious ideas require serious precision.", "The Trinity is specifically Christian doctrine. A non-Christian student can engage it as metaphysics. Don't force the theology. Present the philosophical question."],
        reading: [{ heading: "The debate that shaped a civilization", body: "The Trinity: one God, three persons — Father, Son, Spirit. The Cappadocian Fathers (Basil, Gregory Nazianzus, Gregory of Nyssa) gave the framework: one ousia (essence), three hypostases (persons). The key insight: 'person' in Trinitarian theology does not mean 'individual' (as in modern usage). It means 'mode of existence.' The Trinity is not three gods; it is one God existing in three relational modes. The debate took 300 years. They argued about one preposition: homoousios ('of one being') vs homoiousios ('of similar being'). The difference is one letter — iota — and it determined the shape of Western civilization. The philosophical claim beneath the theology: reality is fundamentally relational. If God is relational in God's own being, then relationship is not an addition to reality — it is the structure of reality. Substance is not prior to relationship; relationship is prior to substance. Whether you accept the theological framing, the philosophical question is real: is relationship the basic structure of reality, or is it secondary?" }],
        bigIdea: "The Trinity is a metaphysical claim: reality is fundamentally relational. Relationship is not an addition to reality — it is the structure.",
        tryThis: [{ title: "Test the claim", minutes: 16, steps: ["State the Cappadocian formula: one ousia (essence), three hypostases (persons/modes).", "The philosophical claim: relationship is prior to substance. Do you agree?", "Find one example where relationship seems more fundamental than the thing itself (a conversation, a family, a ecosystem).", "Practice/Reflect: is the Trinity a metaphysics of relationship? Can you engage it without accepting the theology?"] }],
        dinnerQuestion: "Is relationship the basic structure of reality — or is it something that happens between things that already exist?",
        transfer: [{ label: "AI", note: "Is a model a substance or a set of relations? The Cappadocian question applies: is the model's 'identity' in its weights (substance) or in its interactions (relations)?" }, { label: "Greeks", note: "The Cappadocians are doing metaphysics — the relationship between unity and plurality, substance and relation. Same questions as Parmenides and Heraclitus, in theological language." }],
        ifTheySay: [
          { heard: "The Trinity doesn't make sense — 1+1+1=3, not 1.", reply: "That is the math the Cappadocians rejected. They are not saying 1+1+1=1. They are saying: God is one what (essence) and three whos (persons). 'Person' here does not mean 'individual' — it means 'mode of existence.' The Trinity is one God existing in three relational modes, not three gods who agree. Whether that makes sense is the question. But '1+1+1=3' is not the claim." },
          { heard: "This is just theology — it has nothing to do with philosophy.", reply: "The Cappadocians were doing metaphysics: they were asking about the relationship between essence and existence, between unity and plurality, between substance and relation. These are philosophical questions that the Trinity frames in theological language. The question 'is relationship prior to substance?' is a live question in metaphysics. The Cappadocians answered yes. Whether you accept their answer, the question is philosophical." },
        ],
        integrity: "Do not ask the model to explain 'the Trinity' as if it's settled. Ask it to explain the debate. The model can present the arguments. Whether they make sense is your judgment.",
        aiLab: { setup: "After the test.", childDoes: "Ask the model: 'Is relationship prior to substance?' Compare its answer to the Cappadocian claim. Find the gap.", evaluate: ["Can they state the one-essence-three-persons formula?", "Did they engage the philosophical question about relationality?"] },
      },
      adult: {
        title: "The Metaphysics of Relationship",
        dek: "The Trinity says God is fundamentally relational. If that's true, relationship is the structure of reality — not an add-on. What does that mean for your family?",
        objective: "The adult can evaluate the Cappadocian claim that relationship is prior to substance and identify one implication for how they understand their family.",
        parentBriefing: "The parent theological humility note: the Trinity is specifically Christian doctrine. A non-Christian student can engage it as metaphysics — the claim that reality is fundamentally relational. A secular philosopher can ask: is relationship prior to substance? The Cappadocians say yes. Whether you accept their theological framing, the philosophical question is real.",
        hardEdges: ["Don't force the theology. The philosophical question — is relationship the structure of reality? — is available without the Trinity.", "If your family is struggling relationally, the claim that 'relationship is the structure of reality' may feel either comforting or impossible. Let it be either."],
        reading: [{ heading: "The family as Trinity", body: "The Cappadocian claim: God is one essence, three persons — and 'person' means 'mode of existence,' not 'individual.' The philosophical implication: reality is fundamentally relational. Relationship is not an add-on to substance; it is the substance. The adult version: what does this mean for your family? If relationship is the structure of reality, then your family is not a collection of individuals who happen to be together. It is a set of relationships that constitutes the individuals. You are not a parent who has relationships. You are a parent because of relationships. Your child is not a person who has a family. They are a person constituted by family. This is a radical claim. It says the relationships are more real than the individuals — because the individuals only exist as persons within the relationships. Whether you accept the Trinity, the philosophical claim is live: are we substances that enter relationships, or are we relationships that crystallize as substances? The Cappadocians say the latter. Your family is the evidence." }],
        bigIdea: "If relationship is the structure of reality, then your family is not individuals who happen to be together. It is relationships that constitute the individuals.",
        tryThis: [{ title: "Test the family as relationship", minutes: 10, steps: ["Ask: am I a person who has relationships, or am I a person because of relationships?", "Name one relationship that constitutes who you are (parent, partner, child, friend). Without it, would you be the same person?", "If the Cappadocians are right — relationship is prior — what changes about how you treat your family?", "One action: invest in one constituting relationship this week. Not because it's nice. Because it's who you are."] }],
        dinnerQuestion: "Are we individuals who happen to be family — or are we family that happens to look like individuals?",
        transfer: [{ label: "Parenting", note: "If relationship constitutes personhood, then how you relate to your child is not just formative — it is constitutive. You are making them a person." }],
        ifTheySay: [
          { heard: "The Trinity is a doctrine, not an argument. You either believe it or you don't.", reply: "The Cappadocians would disagree. They spent decades arguing for it — against the Arians, the Sabellians, the Eunomians. The Trinity is a doctrine that emerged from argument, not a doctrine imposed without argument. The argument is what we study." },
        ],
        integrity: "If the relational ontology is generated, you've let the model describe your family's deepest structure. That description is yours to make.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they engage the relationship-vs-substance question?", "Is the family application honest, not abstract?"] },
      },
    },
  }),
  ...expand({
    slug: "contemplation-and-action",
    subject: "philosophy",
    unit: "Faith & Reason",
    number: 10,
    bands: ["emerging", "adult"],
    variants: {
      emerging: {
        title: "Thinking and Doing",
        dek: "Gregory the Great said the contemplative life and the active life are not rivals. The goal is action flowing from reflection and returning to it. How is your balance?",
        objective: "The student can state Gregory's framework for the integrated life and evaluate their own balance between contemplation and action.",
        parentBriefing: "This is intellectual history, not catechism. Gregory's framework: the active life is necessary, the contemplative life is superior, but the integrated life — action flowing from contemplation and returning to it — is the goal. The AI connection: the student who asks the model for answers without reflecting is all action, no contemplation. The student who reads philosophy without applying it is all contemplation, no action.",
        hardEdges: ["Contemplation is not 'doing nothing.' Gregory says it is the hardest work — facing reality without distraction.", "Don't present this as 'monastic spirituality.' Gregory was Pope — he administered hospitals, negotiated with invaders, managed a diocese. His argument is for people with jobs, not for monks."],
        reading: [{ heading: "The integrated life", body: "Gregory the Great's framework: the active life (serving in the world) and the contemplative life (seeking truth in silence) are not opposites. The active life is necessary — faith without works is dead. The contemplative life is superior — Mary chose the better part. But the integrated life is the goal: action flowing from contemplation and returning to it. You serve because you have reflected. You reflect because you have served. The movement between them is the discipline. The AI connection: the student who asks the model for answers without reflecting is all action, no contemplation — reactive, ungrounded. The student who reads philosophy without applying it is all contemplation, no action — abstract, inert. The sitting asks: where is your balance? The integrity rule: do not let the model replace either the thinking or the doing. The model can help with both. It cannot be either." }],
        bigIdea: "Thinking and doing are not rivals. The integrated life moves between them — action grounded in reflection, reflection tested in action.",
        tryThis: [{ title: "Audit your balance", minutes: 16, steps: ["Name one way you are all action (reacting, doing, responding) without reflection.", "Name one way you are all contemplation (thinking, reading, planning) without action.", "Where is the balance? What would 'action flowing from reflection and returning to it' look like?", "Practice/Reflect: is the model replacing your contemplation (you ask it instead of thinking) or your action (you read its output instead of doing)?"] }],
        dinnerQuestion: "Where are we all doing and no thinking — or all thinking and no doing?",
        transfer: [{ label: "AI", note: "The model is the temptation to skip contemplation (just ask) and skip action (just read). The integrated life requires both." }, { label: "Stoics", note: "Gregory's active-contemplative balance echoes Marcus Aurelius — the emperor who journaled before acting. Same structure, different theology." }],
        ifTheySay: [
          { heard: "Contemplation sounds like doing nothing.", reply: "Gregory would say contemplation is the hardest work — it is facing reality without distraction. Most people can serve the poor for an hour. Few can sit in silence for an hour and face what they actually believe. The active life feels productive; the contemplative life is productive in a way that does not feel like it." },
          { heard: "I'm a practical person — I don't need contemplation.", reply: "Gregory's answer: the active life without contemplation becomes reactive — you respond to every crisis without asking whether your response serves the good or just relieves your anxiety. Contemplation is what keeps action honest. Without it, you are not serving; you are managing your discomfort." },
        ],
        integrity: "Do not let the model replace either the thinking or the doing. The model can help with both. It cannot be either. That boundary is the sitting.",
        aiLab: { setup: "After the audit.", childDoes: "Ask the model to help with one side you're missing. If you're all action, ask it for a question to sit with. If you're all contemplation, ask it for one action to take.", evaluate: ["Did they identify their imbalance?", "Is the correction specific?"] },
      },
      adult: {
        title: "The Parent's Integrated Life",
        dek: "Gregory was Pope — hospitals, invaders, diocese, and still 'the contemplative life is the better part.' For a parent: ten minutes before the phone. The scale changes; the principle does not.",
        objective: "The adult can evaluate their balance between contemplation and action and identify one practice that restores the integration.",
        parentBriefing: "The parent theological humility note: Gregory and Bonaventure write within a Christian frame (the goal of both contemplation and action is God). A secular parent can translate: reflection and action are both necessary, and the discipline is in the movement between them. The structure is available without the theology. The theology gives it a specific aim; the philosophy gives it a general shape.",
        hardEdges: ["Don't prescribe monastic practices. Gregory was Pope, not a monk. His argument is for people with obligations — which includes every parent.", "If the parent is all action (reactive, overwhelmed), the prescription is not 'go on retreat.' It's: find the silence that keeps your action honest. Ten minutes. Before the phone."],
        reading: [{ heading: "The Pope's practice", body: "Gregory the Great was Pope — he administered hospitals, negotiated with invaders, managed a diocese, wrote biblical commentaries, and still said 'the contemplative life is the better part.' His argument is not 'go to a monastery.' It is: 'find the silence that keeps your action honest.' For a parent: ten minutes before the phone, five minutes before the email, one minute before the response to your child. The scale changes; the principle does not. The integrated life is not a luxury for people without obligations. It is a discipline for people with too many — which is every parent. The question: what is your practice? Not a grand practice. A small one, repeated daily, that keeps your action grounded in reflection. The model can help with the reflection (ask it for a question to sit with). It cannot do the sitting. That is yours. The active life without contemplation becomes reactive — you respond to every crisis without asking whether your response serves the good or just relieves your anxiety. The contemplative life without action becomes abstract — you think about parenting without parenting. The discipline is the movement between them. Gregory's integrated life, for a parent: act, reflect, act better. Repeat. Forever." }],
        bigIdea: "The integrated life is not a luxury for people without obligations. It is a discipline for people with too many. Ten minutes. Before the phone. The scale changes; the principle does not.",
        tryThis: [{ title: "Find your practice", minutes: 10, steps: ["Ask: am I all action (reactive, overwhelmed) or all contemplation (thinking, not doing)?", "What is one small practice that restores the balance? (Ten minutes of silence before the phone. One reflective question before responding to your child.)", "Commit to it for one week. Not a grand practice. A small one, repeated.", "The test: does the action that follows feel more grounded — or just slower?"] }],
        dinnerQuestion: "What is one small practice that would keep our action honest — and can we commit to it for one week?",
        transfer: [{ label: "Parenting", note: "Your children learn the integrated life by watching you. If you are all action, they learn reactivity. If you are all reflection, they learn paralysis. The movement between is the lesson." }],
        ifTheySay: [
          { heard: "This is monastic spirituality — it doesn't apply to parents with jobs.", reply: "Gregory was Pope — he administered hospitals, negotiated with invaders, managed a diocese, and still wrote 'the contemplative life is the better part.' His argument is not 'go to a monastery.' It is 'find the silence that keeps your action honest.' For a parent: ten minutes before the phone, five minutes before the email. The scale changes; the principle does not." },
        ],
        integrity: "If the practice is generated, you've let the model design your contemplative life. The practice is yours to choose and yours to keep.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they identify their imbalance honestly?", "Is the practice small enough to actually do?"] },
      },
    },
  }),
];