import { expand } from "./factory";

const UNIT = "Voice";

export const languageSpeakLessons = [
  ...expand({
    slug: "hear-then-say",
    subject: "language",
    unit: UNIT,
    number: 2,
    variants: {
      little: {
        title: "Hear It, Then You Say It",
        dek: "Ears first. Mouth second. A tool may be the second listen, never the only mouth.",
        objective: "The child hears a short phrase from a human, says it twice, and only then may hear a tool once.",
        parentBriefing: "One phrase. You say it. They say it. Tool last. You do not need to be fluent. Mocking accent is out.",
        hardEdges: ["Don't mock accent.", "The tool does not speak instead of the child."],
        reading: [{ heading: "Ears, then mouth", body: "You hear a word. Then your mouth has to try it. A talking tool can make a pretty sound. Pretty is not practice. Practice is the air leaving your own mouth. We hear a person first. We say it. We say it again. The tool may listen second." }],
        bigIdea: "If you only heard a tool, you did not practice with a person.",
        tryThis: [{ title: "Person first", minutes: 18, steps: ["Grown-up says one phrase (hello, thank you, a food).", "Child says it. Grown-up says it with them.", "Child says it alone.", "Ask a Grown-Up: did both mouths move?", "Optional: hear the guide once. Then mute and say it again."] }],
        dinnerQuestion: "What phrase did a person say first today?",
        transfer: [{ label: "AI", note: "Try first. Tool second." }],
        ifTheySay: [{ heard: "The tool sounds better.", reply: "Better is not the point. Your mouth is the point." }],
        integrity: "We do not let the tool be the only speaker in the house.",
        aiLab: { setup: "After two human says.", childDoes: "One listen. Then mute. Say it.", evaluate: ["Human first?", "Mouth moved twice?", "Tool not instead?"] },
      },
      young: {
        title: "Listen Once, Speak Twice",
        dek: "A model can model a sound. It cannot take the exam of being understood.",
        objective: "The student hears a phrase, produces it twice without looking, then uses a tool only to compare one sound.",
        parentBriefing: "House rule: mouth first. Language apps wait.",
        hardEdges: ["No generated 'my sentence' as the utterance they will turn in.", "Don't mock accent."],
        reading: [{ heading: "Second listen, not first mouth", body: "You will be tempted to let the tool speak and then nod. Nodding is not language. Hear a human or a short recording. Pause. Say it. Say it again. Then, if you want, compare one vowel. Teachers can tell a generated paragraph. Grandmothers can tell a mouth that never moved." }],
        bigIdea: "The target is a human ear, not a pretty waveform.",
        tryThis: [{ title: "Twice before compare", minutes: 18, steps: ["One useful phrase. Hear it once from a person or class audio — not a chatbot.", "Say it twice with the screen down.", "Optional: one compare. Then mute and say it a third time."] }],
        dinnerQuestion: "Who are we saying this to, if not a speaker in a phone?",
        transfer: [{ label: "English", note: "Ugly draft. Mouth first." }],
        ifTheySay: [{ heard: "I'll just play it at them.", reply: "Playing is not speaking. They still have to answer a person." }],
        integrity: "No generated oral assignments unlabeled as drill.",
        aiLab: { setup: "After two says.", childDoes: "Ask about one sound, not a full rewrite.", evaluate: ["Two unaided says?", "Compare second?"] },
      },
      emerging: {
        title: "The First Take Is the Practice",
        dek: "Conversation does not wait while you craft a perfect subjunctive.",
        objective: "The student does a one-take repeat of a heard line, then drills holes — not a scripted second take that is just reading the model.",
        parentBriefing: "Timer. One take. Tools after.",
        hardEdges: ["Medical/legal interpreting: human interpreter, not a model.", "Don't humiliate accent."],
        reading: [{ heading: "One take", body: "A model will wait forever. A person will not. Hear a line. Pause. Speak it in one take. Then look. The second take should still be yours, not a reading of the model's transcript." }],
        bigIdea: "One-take speech is the skill. Polished generation is a costume.",
        tryThis: [{ title: "Timer, one take", minutes: 18, steps: ["Hear one sentence. Timer 20 seconds. Speak. No typing first.", "Mark what died.", "Drill that hole only.", "Second one-take."] }],
        dinnerQuestion: "What still dies when the chat is closed?",
        transfer: [{ label: "English", note: "Reproduce, don't paste." }],
        ifTheySay: [{ heard: "I'll be fluent with tools in my ear.", reply: "Until the earpiece is gone, rude, or wrong. Own a core." }],
        integrity: "No oral-exam cheating. If that needed saying, here it is.",
        aiLab: { setup: "After first take.", childDoes: "Drill holes. No full script for take two.", evaluate: ["True one-take?", "Second take still theirs?"] },
      },
      adult: {
        title: "Hear Them, Then Try",
        dek: "Your imperfect mouth next to theirs beats an app they use alone.",
        objective: "The adult hears the child's phrase and says it with them, badly if needed, before any TTS.",
        parentBriefing: "You may be worse. That is the gift.",
        hardEdges: ["Don't police heritage register with a model's correctness.", "Don't take over homework in a language you don't have."],
        reading: [{ heading: "Cover for trying", body: "Language survives in houses. Hear them. Try the phrase. Let them correct you. A model can drill later. It cannot replace the social fact that this family is trying out loud." }],
        bigIdea: "Effort at the table gives them cover. Perfection teaches silence.",
        tryThis: [{ title: "Both mouths", minutes: 8, steps: ["Child teaches one phrase.", "Adult says it.", "Both say it at dinner. No generated speech."] }],
        dinnerQuestion: "What phrase did we both actually say?",
        transfer: [{ label: "Parenting", note: "Model risk." }],
        ifTheySay: [{ heard: "I'll embarrass them.", reply: "Perfection embarrasses them into silence. Effort gives cover." }],
        integrity: "Don't let a tool speak to a relative as the child.",
        aiLab: { setup: "Pronunciation second listen optional.", childDoes: "Both repeat. Mute.", evaluate: ["Hit the table?", "Tool instead?"] },
      },
    },
  }),

  ...expand({
    slug: "one-phrase-yours",
    subject: "language",
    unit: UNIT,
    number: 3,
    variants: {
      little: {
        title: "One Phrase That Is Yours",
        dek: "Pick one phrase. Use it for real. A tool may not say it to grandma for you.",
        objective: "The child chooses one phrase, says it to a person in the house, and does not let a tool speak for them.",
        parentBriefing: "Thank you, please, a food, hello. Real use. Not a recitation contest.",
        hardEdges: ["Don't mock.", "Tool does not answer a person for the child."],
        reading: [{ heading: "Used, not displayed", body: "A phrase on a screen is a sticker. A phrase you say when you want water is yours. Today we pick one. We use it. The tool does not get to be polite for us." }],
        bigIdea: "A phrase you used is language. A phrase you only heard is a costume.",
        tryThis: [{ title: "Use it once", minutes: 18, steps: ["Pick one phrase.", "Say it when it is true (please, thank you, more, hello).", "Ask a Grown-Up: did a person hear it?", "Tool stays closed during the use."] }],
        dinnerQuestion: "What phrase did we actually use, not just practice?",
        transfer: [{ label: "English", note: "Your own words." }],
        ifTheySay: [{ heard: "Can the tool say it to them?", reply: "No. You say it. The tool can wait." }],
        integrity: "We do not let the tool answer a person for us.",
        aiLab: { setup: "After a real use.", childDoes: "Optional second listen. Then you say it.", evaluate: ["Used with a person?", "Tool not the speaker?"] },
      },
      young: {
        title: "Three Sentences You Can Say",
        dek: "Write them. Say them. A generator may not be the paragraph you turn in.",
        objective: "The student produces three original sentences, speaks them, and uses a tool only to correct one pattern.",
        parentBriefing: "Mouth first. Generator is drill, labeled, not 'my work.'",
        hardEdges: ["No generated oral assignments as their work.", "Don't record other people's voices as yours."],
        reading: [{ heading: "Original, then out loud", body: "Three sentences you made. Not a chatbot's weekend. Say them. Record if you like. Ask for one pattern, not a rewrite of all three. Then say them again." }],
        bigIdea: "If you could not say it with the chat closed, it is not yours yet.",
        tryThis: [{ title: "Write, say, one pattern", minutes: 18, steps: ["Three original sentences. No generator.", "Say them.", "One pattern question to the guide.", "Say them again."] }],
        dinnerQuestion: "Which of the three could you still say if the phone died?",
        transfer: [{ label: "English", note: "Ugly draft." }],
        ifTheySay: [{ heard: "The tool sounds more native.", reply: "You are growing a mouth, not casting a voice actor." }],
        integrity: "Generated paragraphs in the target language are drill, labeled — not 'my paragraph.'",
        aiLab: { setup: "After three sentences exist.", childDoes: "One grammar pattern. Reject a full rewrite.", evaluate: ["Original?", "Second saying?"] },
      },
      emerging: {
        title: "Closed-Book Three Minutes",
        dek: "If you cannot speak for three minutes with the chat closed, you have composition, not conversation.",
        objective: "The student speaks three minutes on a simple topic with no typing first, then drills holes.",
        parentBriefing: "Timer. Person if possible. Model only after, with rules.",
        hardEdges: ["Live medical/legal interpreting: human.", "Don't humiliate accent."],
        reading: [{ heading: "Time-bounded", body: "Conversation is timed and human. Crafting a perfect paragraph in a chat is composition. Both have a place. Only one transfers to the street, the interview, the border." }],
        bigIdea: "Closed chat is the exam. Open chat is rehearsal if you already spoke.",
        tryThis: [{ title: "Three minutes", minutes: 18, steps: ["Timer. Speak. No typing first.", "Drill holes.", "Second one-take. Compare.", "Reflect: what still dies closed?"] }],
        dinnerQuestion: "What can I actually say if the network is down?",
        transfer: [{ label: "CS", note: "Closed-book explain." }],
        ifTheySay: [{ heard: "Tools in my ear are enough.", reply: "Until they are gone, rude, or wrong. Own a core." }],
        integrity: "No oral exam cheating.",
        aiLab: { setup: "After one-take.", childDoes: "Drill holes. No script that is just reading the model.", evaluate: ["True one-take?", "Second take theirs?"] },
      },
      adult: {
        title: "A Phrase That Hits the Table",
        dek: "Pick one. Use it at dinner. Nobody generates a speech.",
        objective: "The adult and child use one shared phrase at the table this week.",
        parentBriefing: "Thank you, please, a food. Both say it.",
        hardEdges: ["Don't police home register.", "Don't generate a toast."],
        reading: [{ heading: "Ours this week", body: "One phrase is a house fact. An app they use alone is not. Say it badly. Let them correct you." }],
        bigIdea: "A house that never speaks will not get a language from an app.",
        tryThis: [{ title: "Dinner phrase", minutes: 5, steps: ["Pick one.", "Both say it at the table.", "No generated speech."] }],
        dinnerQuestion: "What phrase is ours this week?",
        transfer: [{ label: "Parenting", note: "Risk in public." }],
        ifTheySay: [{ heard: "The app is better.", reply: "The app is not sitting at this table." }],
        integrity: "Don't let a tool speak to a relative as the child.",
        aiLab: { setup: "Optional second listen.", childDoes: "Both repeat. Mute.", evaluate: ["Hit the table?"] },
      },
    },
  }),

  ...expand({
    slug: "ask-out-loud",
    subject: "language",
    unit: UNIT,
    number: 4,
    variants: {
      little: {
        title: "Ask Out Loud",
        dek: "A question you can say is worth more than a list of words you only heard.",
        objective: "The child learns one question (what is that, can I have, where is) and asks a person — not a tool first.",
        parentBriefing: "One question. Real object. They ask you. You answer. Tool second listen only.",
        hardEdges: ["Don't mock.", "Tool does not ask for them."],
        reading: [{ heading: "Questions are mouths too", body: "Words you can say include questions. 'What is that?' 'Can I have water?' Ask a person. A tool can wait. Asking is language." }],
        bigIdea: "If you cannot ask, you can only wait to be spoken at.",
        tryThis: [{ title: "One question, one person", minutes: 18, steps: ["Learn one question with a grown-up.", "Ask it about a real thing in the room.", "Ask a Grown-Up: did you ask a person, not a screen?", "Optional: hear the question once from a tool, then ask it again yourself."] }],
        dinnerQuestion: "What question did we actually ask a person?",
        transfer: [{ label: "Thinking", note: "Ask, then check." }],
        ifTheySay: [{ heard: "I'll type it.", reply: "Typing is not asking. Ask with your mouth." }],
        integrity: "The child asks. The tool does not ask for them.",
        aiLab: { setup: "After a real ask.", childDoes: "Second listen optional.", evaluate: ["Asked a person?", "Mouth moved?"] },
      },
      young: {
        title: "Ask, Don't Paste",
        dek: "A question you can say to a human is the skill. A chatbot Q&A is not conversation.",
        objective: "The student prepares two questions, asks them out loud, and refuses to let a model be the other speaker in a graded oral.",
        parentBriefing: "Pair with a sibling or you. Not a chatbot interview as the whole sitting.",
        hardEdges: ["No earpiece fantasies.", "Don't record others without consent."],
        reading: [{ heading: "The other person", body: "Language is for someone. Write two questions. Ask them. Listen to the answer. A model that answers forever is not that someone." }],
        bigIdea: "Questions you can ask a person transfer. Pasted interviews do not.",
        tryThis: [{ title: "Two questions", minutes: 18, steps: ["Write two questions. No generator.", "Ask a person. Listen.", "One pattern check with a tool if needed.", "Ask them again, better, still yours."] }],
        dinnerQuestion: "Who answered us — a person or a tab?",
        transfer: [{ label: "English", note: "Questions before essays." }],
        ifTheySay: [{ heard: "The bot is easier to ask.", reply: "Easier is the trap. The exam is a person." }],
        integrity: "No generated interview as 'I spoke.'",
        aiLab: { setup: "After two human asks.", childDoes: "One pattern. Not a script of new questions to read.", evaluate: ["Asked a person?", "Second ask still theirs?"] },
      },
      emerging: {
        title: "Ask and Stay",
        dek: "Ask. Hear the answer. Follow up once — without typing a perfect reply first.",
        objective: "The student asks, listens, and follows up in one take.",
        parentBriefing: "Partner or closed-book voice note to a human who will answer later.",
        hardEdges: ["Interpreter for medical/legal: human.", "Don't humiliate."],
        reading: [{ heading: "Follow-up is the language", body: "Anyone can read a question. Staying for the answer and asking the next thing is conversation. Do it with the chat closed." }],
        bigIdea: "Follow-up without a draft window is the skill.",
        tryThis: [{ title: "Ask, hear, one more", minutes: 18, steps: ["One question out loud.", "Hear the answer.", "One follow-up, no typing.", "Then drill holes."] }],
        dinnerQuestion: "Did we stay for the answer?",
        transfer: [{ label: "Thinking", note: "Listen before the next claim." }],
        ifTheySay: [{ heard: "I'll write the follow-up first.", reply: "Then it is composition. Try one take." }],
        integrity: "No oral cheating.",
        aiLab: { setup: "After follow-up.", childDoes: "Drill the hole. Don't replace the follow-up with a model line.", evaluate: ["Follow-up unaided?"] },
      },
      adult: {
        title: "Ask Them in Their Words",
        dek: "Ask the child a real question in the target language, badly. Let them answer.",
        objective: "The adult asks one real question at the table in the language they are learning.",
        parentBriefing: "What did you eat. How was school. Simple. You may be worse.",
        hardEdges: ["Don't take over.", "Don't correct every sound."],
        reading: [{ heading: "You ask", body: "If only the app asks, the house is silent. Ask one thing. Wait. Their answer is the curriculum." }],
        bigIdea: "A parent who asks gives the language a job in the house.",
        tryThis: [{ title: "One real question", minutes: 5, steps: ["Ask one question in the target language.", "Wait for their answer.", "Nobody generates the question."] }],
        dinnerQuestion: "What did we ask — not what did the app ask?",
        transfer: [{ label: "Parenting", note: "Wait." }],
        ifTheySay: [{ heard: "They'll laugh.", reply: "Then laugh together. Silence is worse." }],
        integrity: "Don't let a tool ask a relative as the child.",
        aiLab: { setup: "Optional pronunciation after.", childDoes: "You asked. Mute.", evaluate: ["Did you ask?", "Did you wait?"] },
      },
    },
  }),

  ...expand({
    slug: "catch-the-ghost-speaker",
    subject: "language",
    unit: UNIT,
    number: 5,
    variants: {
      little: {
        title: "You Say It, Not the Speaker",
        dek: "If a tool talks to grandma for you, you did not speak.",
        objective: "The child can refuse letting a tool talk to a person in their place.",
        parentBriefing: "Name the rule out loud. Practice a hello without the speaker.",
        hardEdges: ["Don't mock.", "No tool as the child's voice to a relative."],
        reading: [{ heading: "Not instead", body: "A speaker in a phone can say the word. It cannot be you. If someone is in the room, your mouth does the work. The tool may help you practice. It may not take your turn." }],
        bigIdea: "A tool that talks instead of you is a ghost. Ghosts don't learn.",
        tryThis: [{ title: "Your turn", minutes: 18, steps: ["Practice hello with a grown-up.", "Say it to a person.", "If a tool starts to talk, stop it.", "Ask a Grown-Up: whose mouth was it?"] }],
        dinnerQuestion: "Did a speaker try to take our turn today?",
        transfer: [{ label: "AI", note: "Guide second." }],
        ifTheySay: [{ heard: "It's easier if the phone says it.", reply: "Easier is skipping. We still say it." }],
        integrity: "The tool does not speak to a person as the child.",
        aiLab: { setup: "After a human hello.", childDoes: "Do not ask the tool to greet anyone.", evaluate: ["Human heard them?", "Tool not instead?"] },
      },
      young: {
        title: "Catch the Ghost-Speaker",
        dek: "Generated speech in your name is a costume. Catch it before you turn it in.",
        objective: "The student labels drill vs their work and refuses to submit generated oral as theirs.",
        parentBriefing: "Make the house rule explicit: labeled drill is ok. 'My paragraph' that a model spoke is not.",
        hardEdges: ["No pasting other voices.", "Oral exams: no earpiece."],
        reading: [{ heading: "Costume", body: "A generated paragraph in Spanish is a costume. A sentence you can say to a human is the language. Catch the moment you were about to let the tool be the speaker. That catch is the sitting." }],
        bigIdea: "If you could not say it, do not sign it.",
        tryThis: [{ title: "Label the work", minutes: 18, steps: ["Make two columns: MINE / DRILL.", "Three sentences you said go in MINE.", "Anything a model produced goes in DRILL, labeled.", "Say the MINE column again, chat closed."] }],
        dinnerQuestion: "What almost got signed that we did not say?",
        transfer: [{ label: "English", note: "Name on the work." }],
        ifTheySay: [{ heard: "Nobody will know.", reply: "You will know. The grandmother will know. Teachers often know." }],
        integrity: "No generated oral as 'my work.'",
        aiLab: { setup: "After MINE exists.", childDoes: "Ask one pattern. Reject a full spoken paragraph to submit.", evaluate: ["MINE column real?", "DRILL labeled?"] },
      },
      emerging: {
        title: "No Earpiece",
        dek: "If the line only works with a model in your ear, you do not have it yet.",
        objective: "The student identifies one utterance they can do closed-book and one they cannot — and does not fake the second.",
        parentBriefing: "Jobs, orals, borders. Contempt for the earpiece fantasy.",
        hardEdges: ["Interpreting: human.", "Don't humiliate."],
        reading: [{ heading: "The earpiece fails", body: "Ghost-speakers fail at the border, the interview, and the dinner. Own a core you can say with the network down. Tools around it, not instead of it." }],
        bigIdea: "Closed-book speech is the core. Earpiece fluency is a costume.",
        tryThis: [{ title: "Core vs costume", minutes: 18, steps: ["List five things you can say closed-book.", "List two you only have with a chat open.", "Practice one from the second list, one-take, then check.", "Do not submit the chat version as speech."] }],
        dinnerQuestion: "What still needs an earpiece — and will we admit it?",
        transfer: [{ label: "CS", note: "Explain without the tab." }],
        ifTheySay: [{ heard: "In the real world we have phones.", reply: "Until you don't, or it's wrong. Own a core." }],
        integrity: "No oral exam cheating.",
        aiLab: { setup: "After the closed-book list.", childDoes: "Drill one hole. Don't replace the list with a generated speech.", evaluate: ["Honest split?", "One-take on a hole?"] },
      },
      adult: {
        title: "Don't Let It Speak for Them",
        dek: "A tool that greets family 'as' the child teaches the wrong lesson.",
        objective: "The adult stops one ghost-speaker moment this week and has the child say it.",
        parentBriefing: "Relatives, restaurants, voicemail. The child speaks. You may help. The phone does not take the turn.",
        hardEdges: ["Heritage: don't overwrite home register.", "Medical/legal: interpreter, not TTS as the child."],
        reading: [{ heading: "Their turn", body: "It is kind to want them understood. It is not kind to erase their mouth. Help them say it. Do not let a speaker be them." }],
        bigIdea: "Understanding is the goal. Substitution is not help.",
        tryThis: [{ title: "Catch one substitution", minutes: 8, steps: ["Notice a moment you would hand the phone the turn.", "Have them say it.", "You backup, not the speaker."] }],
        dinnerQuestion: "Where did we almost let a tool take their turn?",
        transfer: [{ label: "Parenting", note: "Cover, don't replace." }],
        ifTheySay: [{ heard: "I just want them understood.", reply: "Then help them say it. Don't say it as them." }],
        integrity: "Don't let a tool speak to a relative as the child.",
        aiLab: { setup: "After they said it.", childDoes: "Optional pronunciation. Mute before any greeting.", evaluate: ["Their mouth?", "No substitution?"] },
      },
    },
  }),

  ...expand({
    slug: "speak-first-capstone",
    subject: "language",
    unit: UNIT,
    number: 6,
    variants: {
      little: {
        title: "Mouth First, Then the Tool",
        dek: "The last sitting: hear a person, say it, use it, then maybe a second listen. The tool never takes the turn.",
        objective: "The child completes hear → say → use with a person, tool last.",
        parentBriefing: "Capstone of the Voice little arc. You are in the room. Five to ten: grown-up present.",
        hardEdges: ["Try This on mouths before any model.", "If the tool speaks instead, that turn is a miss."],
        reading: [{ heading: "The whole little arc", body: "You heard a person. You said it. You used a phrase. You asked. You did not let a speaker be you. Now we do the three-beat in one sitting: person, mouth, then maybe a tool. This is the language we needed: a house where mouths move." }],
        bigIdea: "Hear. Say. Use. Then the tool. A person is still the judge.",
        tryThis: [{ title: "Full three-beat", minutes: 18, steps: ["Grown-up says the week's phrase.", "Child says it twice.", "Child uses it for real (please, thank you, hello).", "Ask a Grown-Up: whose mouth?", "Only then a tool may be a second listen. Mute and say it again."] }],
        dinnerQuestion: "Did our mouths move before any speaker today?",
        transfer: [{ label: "AI", note: "Try first." }, { label: "English", note: "Your own words." }],
        ifTheySay: [{ heard: "The tool already knows how to say it.", reply: "Then it can wait. We still say it." }],
        integrity: "The child's mouth is the work. A played phrase is not a sitting.",
        aiLab: { setup: "After use with a person.", childDoes: "Second listen. Mute. Say it.", evaluate: ["Person first?", "Used?", "Tool not instead?"] },
      },
      young: {
        title: "Speak First Capstone",
        dek: "Three original sentences, said twice, one pattern check, no ghost-speaker.",
        objective: "The student runs the full Voice rule in one sitting and can explain why the tool is second.",
        parentBriefing: "This closes the six-sitting young arc. Same house rule as sitting 1.",
        hardEdges: ["No generated oral as theirs.", "Mouth first."],
        reading: [{ heading: "The rule in one sitting", body: "Write. Say. Compare one pattern. Say again. If a tool offers to be the speaker, catch it. The grandmother is still the exam." }],
        bigIdea: "The mouth has to move. Everything else is drill around that fact.",
        tryThis: [{ title: "Full rule", minutes: 18, steps: ["Three original sentences.", "Say them twice, screen down.", "One pattern from a guide.", "Say them again.", "Label anything generated as DRILL, not MINE."] }],
        dinnerQuestion: "What did we say that a tool did not say for us?",
        transfer: [{ label: "English", note: "Name on the work." }],
        ifTheySay: [{ heard: "We're done; the tool can finish.", reply: "Finishing is saying it. The tool can wait." }],
        integrity: "No generated oral as my work.",
        aiLab: { setup: "After MINE is spoken.", childDoes: "One pattern. Reject a rewrite of all three.", evaluate: ["Original?", "Twice unaided?", "DRILL labeled?"] },
      },
      emerging: {
        title: "Closed Chat, Then Drill",
        dek: "Capstone: three-minute one-take, then holes, then a second take that is still yours.",
        objective: "The student proves a core they can say with the chat closed.",
        parentBriefing: "Timer. Person if you can. Model after.",
        hardEdges: ["No earpiece.", "Interpreter when required: human."],
        reading: [{ heading: "Core you own", body: "This sitting is the Voice exam-hall. Speak. Close the chat. Drill. Speak again. If the second take is reading the model, it failed." }],
        bigIdea: "Own a core. Tools around it, not instead of it.",
        tryThis: [{ title: "Exam-hall three minutes", minutes: 18, steps: ["Three minutes, one take, no typing.", "Drill holes only.", "Second one-take.", "Write one sentence you can still say if the network is down."] }],
        dinnerQuestion: "What is in the core now that was costume last month?",
        transfer: [{ label: "English", note: "Reproduce the paragraph." }],
        ifTheySay: [{ heard: "I'll be fine with tools.", reply: "Then prove one core without them tonight." }],
        integrity: "No oral cheating.",
        aiLab: { setup: "After take one.", childDoes: "Holes only. No full script.", evaluate: ["One-take?", "Second take theirs?", "Core sentence written?"] },
      },
      adult: {
        title: "The House Speaks",
        dek: "Capstone: one phrase used, one question asked, no ghost-speaker. You are allowed to be worse.",
        objective: "The adult and child use language out loud at the table this week without a tool taking the turn.",
        parentBriefing: "This is the adult close of Voice. Trying in public is the curriculum.",
        hardEdges: ["Don't police heritage.", "Don't let TTS be the child."],
        reading: [{ heading: "Public trying", body: "A phrase at dinner from your imperfect mouth beats an app they use alone. Ask. Say. Do not hand the speaker their turn." }],
        bigIdea: "Language survives in houses that speak, not in perfect TTS.",
        tryThis: [{ title: "Table close", minutes: 8, steps: ["One phrase both say.", "One question you ask.", "If a tool reaches for the turn, stop it."] }],
        dinnerQuestion: "Did this house speak before any speaker today?",
        transfer: [{ label: "Parenting", note: "Cover." }],
        ifTheySay: [{ heard: "The app is enough.", reply: "The app is not a relative. We still speak." }],
        integrity: "Don't let a tool speak as the child.",
        aiLab: { setup: "After the table.", childDoes: "Optional pronunciation. Mute before greetings.", evaluate: ["Phrase used?", "Question asked?", "No substitution?"] },
      },
    },
  }),
];
