import { expand } from "./factory";
import type { Lesson } from "../types";

export const philosophyLessons: Lesson[] = [
  ...expand({
    slug: "circle-you-control",
    subject: "philosophy",
    unit: "Character — The Stoics",
    number: 1,
    variants: {
      little: {
        title: "The Circle You Control",
        dek: "Some things are up to you. Some are not. Knowing the difference is the beginning of wisdom.",
        objective: "The child can sort three worries into inside the circle and outside the circle.",
        parentBriefing: "This is Epictetus for small hands. Do not lecture on enslavement in detail; the briefing: he was not free on the outside and found a freedom no one could take. If they ask, answer plainly and stop. Stay with the circle.",
        hardEdges: ["Enslavement and a broken leg are in the story of his life — tell the truth without graphic detail.", "Do not use the circle to shut down feelings. Pain is inside the first arrow; the story we add is the second."],
        reading: [{ heading: "Inside and outside", body: "Epictetus was a boy who was not free. People could move his body. They could not move the part of him that chooses: kind or cruel, brave or giving up. He drew a circle. Inside: what I choose, how I speak, the try I give. Outside: weather, other people's moods, whether the game is fair. The work is to spend our strength inside the circle. A talking tool sits outside the circle too. It can hint. It cannot be your try." }],
        bigIdea: "Your try is yours. The rest of the world is not a failure of yours.",
        tryThis: [{ title: "Draw the circle", minutes: 8, steps: ["Draw a circle. Write three worries.", "Sort inside / outside.", "Ask a grown-up about one outside worry: what inside move is still yours?"] }],
        dinnerQuestion: "What was inside your circle today?",
        transfer: [{ label: "AI", note: "The model's answer is outside. Your check is inside." }, { label: "SEL", note: "Feelings can be true and still sit next to a choice." }],
        ifTheySay: [{ heard: "That's just telling me not to be sad.", reply: "You may be sad. The circle is about where you put your next try, not about pretending the hurt isn't there." }],
        integrity: "We do not ask the tool to sort the circle for us until we have drawn it.",
        aiLab: { setup: "After the drawing.", childDoes: "Ask for one question that helps sort a worry — not the sort itself.", evaluate: ["Did they draw first?", "Did a grown-up stay in the room?"] },
      },
      young: {
        title: "The Boy with a Borrowed Name",
        dek: "What happens to you and what you make of it are not the same job.",
        objective: "The student can apply the dichotomy of control to one real scenario (grades, group chat, sport) without using it as a shutdown.",
        parentBriefing: "Identity and control land hard at this age. The booklet on the original site is the longer text. This sitting is the assist: one scenario, one project, Talk About It.",
        hardEdges: ["Don't weaponize 'that's outside your control' against a child who needs protection — bullying is not a Stoic homework.", "Enslavement: name it; don't turn it into a metaphor only."],
        reading: [{ heading: "Borrowed names, real choice", body: "Epictetus means 'acquired.' Even his name was not originally his. The teaching is severe and useful: some things are up to us (judgments, aims, the next act) and some are not (body, reputation, other people's posts). Peace is not numbness. It is refusing to spend the whole night inside a comment you cannot edit. A model that writes your comeback is not helping you practice choice. It is borrowing your mouth." }],
        bigIdea: "You do not control the feed. You control the next judgment and the next act.",
        tryThis: [{ title: "One scenario", minutes: 12, steps: ["Pick grades, sport, or a group chat.", "Two columns: UP TO ME / NOT.", "Write the next act in one sentence.", "Talk About It: where is this sitting next to injustice that needs an adult, not a circle?"] }],
        dinnerQuestion: "Where did you spend strength outside your circle this week?",
        transfer: [{ label: "English", note: "Agency in narrative." }, { label: "AI", note: "Ghostwritten comebacks are not your prohairesis." }],
        ifTheySay: [{ heard: "Stoicism is for people who don't feel.", reply: "Epictetus felt. He refused to let feeling write the whole script. That's different." }],
        integrity: "Do not have a model write the 'next act' sentence.",
        aiLab: { setup: "After the columns.", childDoes: "Ask: 'Question me about whether this is really up to me.' No pep talk.", evaluate: ["Did they keep injustice in the adult column when needed?", "Is the next act theirs?"] },
      },
      emerging: {
        title: "Prohairesis",
        dek: "The unbreakable center is the faculty of choice. Guard it from both tyrants and tools.",
        objective: "The student can explain prohairesis in their own words and apply it to academic integrity and agent permissions.",
        parentBriefing: "This is the philosophical hinge of the whole academy. If they get this, ghostwriting and unattended agents look like what they are: handing over the center.",
        hardEdges: ["Do not skip the historical enslavement. It is not a TED-talk origin story.", "If they are in a situation of real coercion, this sitting is not a lecture to endure it silently — get a human."],
        reading: [{ heading: "The center that cannot be owned", body: "Prohairesis is the reasoned choice that Epictetus said was truly ours. Bodies can be chained. Reputations can be smeared. A model can finish your paragraph. None of that is the center unless you agree to move the center into the paragraph, the like count, or the agent. The Seneca problem of AI is preaching inner freedom while shipping work you could not reproduce. The circle is not a mood. It is a refuse-list for your own will." }],
        bigIdea: "If a tool can do the choosing, you have already moved house.",
        tryThis: [{ title: "Center and permissions", minutes: 16, steps: ["Define prohairesis in four sentences without the reading.", "List two ways a model could steal the next choice this week.", "Write a refuse that protects the center.", "Practice: one assignment done with try-first, hint, cite."] }],
        dinnerQuestion: "Where did I almost hand over a choice to a tool or a crowd?",
        transfer: [{ label: "AI", note: "Ghostwriter ethics is this sitting in modern clothes." }, { label: "Civics", note: "What is up to a citizen." }],
        ifTheySay: [{ heard: "The world is more complex than a circle.", reply: "Yes. Complexity is not a reason to pretend the next judgment isn't yours." }],
        integrity: "Reproduce the work on a blank page or do not claim the center.",
        aiLab: { setup: "Critique the refuse-list. Do not write it.", childDoes: "Ask where the list is theater.", evaluate: ["Can they define prohairesis?", "Is the refuse specific?"] },
      },
      adult: {
        title: "The Circle Is for You Too",
        dek: "Parents spend nights outside the circle: other drivers, other children's posts, the school's AI policy. Come back in.",
        objective: "The adult sorts one live parental worry and refuses to use Stoicism as a shutdown of a child.",
        parentBriefing: "You will be tempted to preach the circle at a child who is drowning. Don't. Use it on your own rumination. Protect them; don't philosophize them into silence.",
        hardEdges: ["Bullying, abuse, and medical fear are not 'outside the child's control, so drop it.' They are inside yours.", "Don't skip Epictetus's enslavement to keep dinner polite. One honest sentence is enough."],
        reading: [{ heading: "Two circles", body: "Yours and theirs. You cannot make them choose well by lecturing the dichotomy while you doomscroll their future. Your circle: presence, house rules, the sitting, the call to the school. Their circle: the next try. A model that parents for you is outside both. The original WisdomForge booklet remains the text. This assist is so you can sit it without bluffing." }],
        bigIdea: "Teach the circle by using it on your own night, not as a muzzle.",
        tryThis: [{ title: "Parent sort", minutes: 10, steps: ["Write the worry that stole last night.", "Inside / outside.", "One inside act for this week (a sitting, a rule, a call).", "Tell the child the circle without using it against them."] }],
        dinnerQuestion: "What is actually up to this family this week?",
        transfer: [{ label: "Parenting", note: "Protection versus rumination." }],
        ifTheySay: [{ heard: "If I don't worry, I'm not a good parent.", reply: "Worry is not the work. The inside act is." }],
        integrity: "Do not outsource the parent briefing to a model while skipping the booklet.",
        aiLab: { setup: "Optional. Ask for a question that returns you to an inside act. No child names.", childDoes: "Close after one question.", evaluate: ["Did you protect rather than preach?", "Is there a real inside act?"] },
      },
    },
  }),
  ...expand({
    slug: "inner-citadel",
    subject: "philosophy",
    unit: "Character — The Stoics",
    number: 2,
    variants: {
      little: {
        title: "The Quiet Notebook",
        dek: "Marcus was an emperor who whispered to himself so he could choose well when the day was loud.",
        objective: "The child can keep a three-line evening notebook for two days: kind, try, next.",
        parentBriefing: "Plague and war are in his life. For this band: he had hard days and a little book. The notebook is the practice. You write too.",
        hardEdges: ["Death can be named as 'people he loved died' without a lecture.", "Do not turn the notebook into a behavior chart for your convenience."],
        reading: [{ heading: "The emperor's whisper", body: "Marcus Aurelius ruled a huge world and still needed a quiet page. He wrote to himself: be decent, do the work, remember you will not be here forever. We do not need a throne to need a page. A talking tool can remind you. It cannot be the whisper. The whisper has to be yours, in your handwriting or your voice to a grown-up." }],
        bigIdea: "A small honest page can hold you when the day is loud.",
        tryThis: [{ title: "Three lines", minutes: 6, steps: ["Tonight: one kind thing, one try, one next.", "Tomorrow night: again.", "Ask a grown-up to do it too."] }],
        dinnerQuestion: "What would you whisper to yourself after a hard day?",
        transfer: [{ label: "English", note: "Journal as practice, not performance." }, { label: "AI", note: "A generated journal is not a whisper." }],
        ifTheySay: [{ heard: "I don't want to write.", reply: "Then say the three lines out loud to me. The mouth counts. A model speaking them does not." }],
        integrity: "The notebook is not shown to a tool.",
        aiLab: { setup: "Off for the notebook itself.", childDoes: "If stuck on the word 'kind,' ask for examples of kind acts, then close.", evaluate: ["Did they produce three lines without a generated diary?", "Did you write too?"] },
      },
      young: {
        title: "The Notebook in the Tent",
        dek: "Leadership, pressure, anger — and the private writing that kept him steady.",
        objective: "The student keeps a five-day morning or evening practice and reviews it without performing for an audience.",
        parentBriefing: "Anger and reputation are the live wires. The model is not their journal. If they want a prompt, it may ask a question, not write the entry.",
        hardEdges: ["Don't read the notebook unless they offer. Privacy is part of the citadel.", "Plague and war: name historically; don't traumatize."],
        reading: [{ heading: "Private, not secret-from-help", body: "Marcus wrote for himself, not for Rome's feed. That is why the book still works: no audience to perform for. Your citadel is the same. A shared doc with a chatbot is an audience. A page no model sees is a practice. Anger will still come. The notebook is where you meet it before you meet the group chat." }],
        bigIdea: "A citadel with an audience is a stage. Keep one page that is not a stage.",
        tryThis: [{ title: "Five nights", minutes: 10, steps: ["Choose morning aim or evening review.", "Five lines max. No audience. No paste.", "On night five, Talk About It: what repeated?", "Do not show the pages to the guide."] }],
        dinnerQuestion: "Where do you still perform instead of practice?",
        transfer: [{ label: "English", note: "Voice without audience." }, { label: "SEL", note: "Anger delay." }],
        ifTheySay: [{ heard: "It's cringe.", reply: "Cringe is an audience word. This page has no audience. That's the point." }],
        integrity: "Do not paste journal entries into a model. Ever.",
        aiLab: { setup: "Questions only, no journal text.", childDoes: "Ask: 'What is a good evening question for anger?' Use it on paper.", evaluate: ["Did the pages stay offline?", "Did they last more than one night?"] },
      },
      emerging: {
        title: "The Inner Citadel",
        dek: "Rule yourself before you try to rule anything else — including an agent.",
        objective: "The student can connect Marcus's inner citadel to self-command over tools, anger, and reputation.",
        parentBriefing: "Mortality and duty will come up. Let them. The assist is not a sermon. The original Meditations booklet is the longer text.",
        hardEdges: ["Suicide and death: if they go dark, stop the philosophy and get a human professional. This sitting is not treatment.", "Don't let 'citadel' become emotional isolation."],
        reading: [{ heading: "Command and tools", body: "Marcus returns to the same commands: do not be yanked by impression; do the work of a human; remember death so that vanity shrinks. An unattended agent is a way to be yanked by someone else's impression at scale. The citadel is not a bunker against people. It is the place from which you can be just to them. If a tool writes your justice, you are not in the citadel. You are in a demo." }],
        bigIdea: "Self-command is the prerequisite for every other command — including the command of tools.",
        tryThis: [{ title: "Morning and refuse", minutes: 15, steps: ["Write a morning command in your voice (not Marcus's antique English).", "Name one impression (anger, status, a model) that yanks you.", "A refuse for this week.", "Evening: did you keep it?"] }],
        dinnerQuestion: "What yanked you out of yourself this week, and what would self-command have looked like?",
        transfer: [{ label: "AI", note: "Permissions map." }, { label: "Civics", note: "Duty to the whole without vanity." }],
        ifTheySay: [{ heard: "This is just journaling with extra steps.", reply: "Journaling that changes the next permission on a tool is not extra. It is the work." }],
        integrity: "Do not generate a fake Meditations in your voice and call it practice.",
        aiLab: { setup: "Ask it to pressure-test the refuse, not to write the command.", childDoes: "If it writes a pastiche of Marcus, throw it out.", evaluate: ["Is the command in their English?", "Did they connect it to a tool?"] },
      },
      adult: {
        title: "Duty Without Performance",
        dek: "You already run a small empire: a house. The notebook is how you do not become a tyrant in it.",
        objective: "The adult keeps three evenings of review aimed at how they used power at home, including tools.",
        parentBriefing: "Marcus is useful to parents because he had power and still needed a page. Your power is real even if it feels like chaos. The sitting is how you notice.",
        hardEdges: ["Do not use Meditations to spiritually bypass a marriage or a child's pain.", "Grief: if it opens, stay human. Close the curriculum."],
        reading: [{ heading: "The house is the province", body: "You will not journal like an emperor. You might write: I snapped; I outsourced the sitting; I confused my anxiety with their character. That page is the citadel. A model that tells you that you are a great parent is flattery. Marcus did not need flattery. He needed reminders. So do you." }],
        bigIdea: "Power without a private page turns into performance. Including parental power.",
        tryThis: [{ title: "Three nights", minutes: 8, steps: ["Each night: where I used power well / poorly / a tool I should not have.", "No posting. No pasting.", "Change one behavior on night four."] }],
        dinnerQuestion: "Where did I use power in this house today?",
        transfer: [{ label: "Parenting", note: "Authority with a review." }],
        ifTheySay: [{ heard: "I don't have time to journal.", reply: "Three lines. If three lines are impossible, the empire is already running you." }],
        integrity: "The page is not content.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Three nights or honest skip.", "Did a behavior change?"] },
      },
    },
  }),
  ...expand({
    slug: "shortest-thing",
    subject: "philosophy",
    unit: "Character — The Stoics",
    number: 3,
    variants: {
      little: {
        title: "The Shortest Thing We Have",
        dek: "Time is small. We spend it on purpose — including time with tools.",
        objective: "The child can name one way they spent time today that they chose and one that just happened.",
        parentBriefing: "Seneca on time, without the death-obsession. Screens are the live example. You will be implicated. Tell the truth about your own time.",
        hardEdges: ["Illness is in his story (the boy who could not breathe). Keep it gentle.", "Don't shame a child's rest. Rest is not wasted time."],
        reading: [{ heading: "How a day goes", body: "Seneca said we think we have a lot of time and then give it away to things we did not choose. A talking tool can eat a day in small bites that feel like nothing. So can a grown-up's phone. We practice putting time where we mean: a story, a try, a person. Then we close the tool. The shortest thing we have is this afternoon. It is enough for one sitting." }],
        bigIdea: "Time we do not choose still gets spent. Choose a little on purpose.",
        tryThis: [{ title: "Two piles", minutes: 7, steps: ["Draw CHOSE and JUST HAPPENED.", "Put today's bits in piles, including tool time.", "Choose one thing for tomorrow's CHOSE pile.", "Ask a grown-up to share theirs."] }],
        dinnerQuestion: "What did we mean to spend time on today?",
        transfer: [{ label: "Math", note: "Duration." }, { label: "AI", note: "Open-ended chat has no clock. You bring the clock." }],
        ifTheySay: [{ heard: "It's my time.", reply: "Yes. That's why we practice choosing it, not watching it leak." }],
        integrity: "We do not hide how long we were on a tool.",
        aiLab: { setup: "A timer on the sitting. Close when it rings.", childDoes: "Ask one hint, then stop even if it wants to continue.", evaluate: ["Did you close on time?", "Did you tell the truth about JUST HAPPENED?"] },
      },
      young: {
        title: "The Island Nobody Wanted",
        dek: "Exile, wasted time, anger as a choice — and staying good under pressure.",
        objective: "The student logs a day's time including tool use and names one anger they delayed.",
        parentBriefing: "The Seneca problem (wealth, Nero) can wait one sitting or get one honest sentence: he did not always live the letters. That honesty is the lesson.",
        hardEdges: ["Nero, cruelty, death: don't graphic-novel it. Don't erase it.", "Anger: not 'never feel.' Delay and choose."],
        reading: [{ heading: "Time and the short madness", body: "Seneca called anger a short madness. He also wasted time while telling others not to. Both things are true. Your sitting is not to become a Roman moralist. It is to see a day: where time went, where anger spent you, where a model offered to write the hours away. Exile in his life was an island. Yours might be a Sunday that vanished into a feed. Count it." }],
        bigIdea: "A day you do not count will be counted for you — by a product.",
        tryThis: [{ title: "Day log", minutes: 12, steps: ["Block the last 24 hours in 30-minute chunks. Include tools.", "Star one anger. Write the delay you used or failed to use.", "Talk About It: what would Seneca's letter say, and where would we not trust the man?"] }],
        dinnerQuestion: "Where did a short madness or a leaky hour get us?",
        transfer: [{ label: "History", note: "Hypocrisy as a historical problem, not a gotcha." }, { label: "AI", note: "Infinite chat is a time thief with a kind voice." }],
        ifTheySay: [{ heard: "Seneca was a hypocrite, so skip him.", reply: "Then you will skip every adult. Read him as a mirror, not a saint." }],
        integrity: "Log honestly. A model cannot count your hours for you.",
        aiLab: { setup: "After the log.", childDoes: "Ask one question about delaying anger. Do not paste the log.", evaluate: ["Is the log real?", "Did they name the Seneca gap without cheap cynicism?"] },
      },
      emerging: {
        title: "The Seneca Problem",
        dek: "Preach simplicity from a palace — or preach responsible AI while shipping ghostwritten work. Same gap.",
        objective: "The student can state the Seneca problem and locate their own version in tool use, time, and anger.",
        parentBriefing: "This is the uncomfortable sitting. Let them indict Seneca. Then ask for the mirror. The original adult booklet is the deeper text.",
        hardEdges: ["Matricide, tyranny, wealth: historically named, not sensationalized.", "If they use it only to dunk on a teacher or parent, return the mirror."],
        reading: [{ heading: "The gap is the curriculum", body: "Scholars call it the Seneca problem: the letters praise poverty and time well spent; the life served a tyrant and held fortunes. It is not a puzzle to solve so you can discard him. It is a mirror. You will praise try-first and paste a prompt at 11 p.m. You will praise presence and leave a sitting to an agent. The work is not to become consistent by lowering the letters. It is to feel the gap and close it one hour at a time." }],
        bigIdea: "The gap between the letter and the life is where character actually is.",
        tryThis: [{ title: "Mirror", minutes: 16, steps: ["Write Seneca's gap in six sentences.", "Write yours in six (tools, time, anger, money, status).", "One closeable gap this week.", "Practice/Reflect: what would make this theater?"] }],
        dinnerQuestion: "Where is our family Seneca problem with AI or time?",
        transfer: [{ label: "AI", note: "Ghostwriter ethics." }, { label: "Civics", note: "Public virtue, private exemption." }],
        ifTheySay: [{ heard: "Then no one can teach.", reply: "People can teach from the gap if they admit it. Saints are optional. Honesty is not." }],
        integrity: "If the six sentences are generated, you just restaged the problem.",
        aiLab: { setup: "Critique the mirror for flattery.", childDoes: "Ask: 'Where am I going easy on myself?'", evaluate: ["Is the personal gap specific?", "Is the closeable action this week, not 'someday'?"] },
      },
      adult: {
        title: "Time, Anger, and the Device",
        dek: "You cannot teach Seneca on time while the phone eats the sitting. Be the boring example.",
        objective: "The adult measures one evening of attention and makes one device rule that applies to them first.",
        parentBriefing: "The children already know if your phone is the household emperor. This sitting is you. The letters can wait.",
        hardEdges: ["Don't announce a grand digital Sabbath you will break by Thursday.", "Anger at the child after a workday is the live wire — delay is the practice."],
        reading: [{ heading: "The shortest evening", body: "Seneca: it is not that we have a short time, but that we waste much of it. You will not recover their childhood with a productivity system. You might recover Tuesday by putting the device in another room for a 20-minute sitting. That is the whole philosophy, applied. The Seneca problem for parents is quoting presence and living on a lock screen." }],
        bigIdea: "A rule that does not bind the adult is a sermon, not a house.",
        tryThis: [{ title: "One evening", minutes: 5, steps: ["Tonight: device in another room for one sitting or one meal.", "Note anger delayed or not.", "Keep the rule if it held. Shrink it if you lied."] }],
        dinnerQuestion: "When did a device spend our evening without being chosen?",
        transfer: [{ label: "Parenting", note: "Modeling time." }],
        ifTheySay: [{ heard: "Work follows me home.", reply: "Then work is in your circle too. Name one fence. A fence of zero is a wish." }],
        integrity: "Do not post the device-free meal. Just have it.",
        aiLab: { setup: "Off during the evening.", childDoes: "None.", evaluate: ["Did the fence hold?", "Did anger get a delay?"] },
      },
    },
  }),
  ...expand({
    slug: "shipwreck",
    subject: "philosophy",
    unit: "Character — The Stoics",
    number: 4,
    variants: {
      little: {
        title: "The Shipwreck",
        dek: "A man lost everything in a storm and found something nothing could take.",
        objective: "The child can tell the shipwreck story and name one thing a storm cannot take.",
        parentBriefing: "This is the founding story of Stoicism. Zeno was a merchant whose ship sank. He lost his cargo, his money, everything. Then he found a book about Socrates and started asking what really matters. Keep it simple: he lost his stuff and found something bigger. Don't dramatize drowning.",
        hardEdges: ["Don't make the shipwreck scary — he survived and walked to Athens.", "Don't say 'everything happens for a reason.' Zeno didn't mean that. He meant: what you keep inside matters more than what you lose outside."],
        reading: [{ heading: "The man who lost everything", body: "Zeno was a trader. He carried purple dye on a ship — the most valuable thing in the ancient world. The ship sank. He walked to Athens with nothing. In a bookshop he read about Socrates and asked: where can I find someone like that? The bookseller pointed to a barefoot philosopher walking by. Zeno followed him. That day, Stoicism began. A storm took his cargo. It could not take the part of him that chose what to do next." }],
        bigIdea: "A storm can take your stuff. It cannot take your next choice.",
        tryThis: [{ title: "What a storm can't take", minutes: 8, steps: ["Name three things a storm could take from your house.", "Name three things a storm could NOT take from you.", "Ask a grown-up: have you ever lost something and found something else?"] }],
        dinnerQuestion: "What is something nobody could take from you?",
        transfer: [{ label: "AI", note: "A tool can lose data. Your judgment is yours." }, { label: "SEL", note: "Loss and what remains." }],
        ifTheySay: [{ heard: "Did he die?", reply: "No! He survived. That's the point. He lost his stuff and kept himself. Then he started something that lasted 500 years." }],
        integrity: "We do not ask the tool to tell us what matters. We name it ourselves first.",
        aiLab: { setup: "After the drawing.", childDoes: "Ask: 'What's one question about what matters?' Not the answer — the question.", evaluate: ["Did they name things a storm can't take?", "Did a grown-up stay in the room?"] },
      },
      young: {
        title: "The Merchant and the Storm",
        dek: "Losing everything and finding philosophy — but is that really wisdom or just survival?",
        objective: "The student can retell the shipwreck story and distinguish between what happened to Zeno and what Zeno made of it.",
        parentBriefing: "The temptation at this age is to reduce it to a motivational story. It's not. Zeno didn't 'bounce back.' He changed what he cared about. The harder question: is that wisdom or just coping? Let them push on that.",
        hardEdges: ["Don't turn this into a 'fail forward' TED talk. Zeno lost something real and it hurt.", "Crates smashing the lentil soup pot is part of the story — Zeno's first teacher was trying to cure his shame. Mention it if they're curious, but don't make it the focus."],
        reading: [{ heading: "From wreck to wisdom", body: "Zeno of Citium was a Phoenician merchant carrying purple dye — the most expensive cargo in the ancient world. His ship wrecked off Athens. He arrived with nothing. In a bookshop he read Xenophon's memoir of Socrates and asked where to find someone like that. The bookseller pointed to Crates the Cynic, barefoot and unconventional, walking past. Zeno followed. He studied with three teachers — a Cynic, a logician, a Platonist — and synthesized them into something new: a philosophy that says what you choose matters more than what you lose. But here's the honest question: did the shipwreck teach him wisdom, or did it just break him enough to listen? Both might be true." }],
        bigIdea: "What happens to you and what you make of it are not the same thing.",
        tryThis: [{ title: "Two columns", minutes: 12, steps: ["Two columns: WHAT HAPPENED / WHAT I MADE OF IT.", "Fill in three rows from Zeno's life (shipwreck, lentil soup, founding the Stoa).", "Now one row from your life.", "Talk About It: where did 'what happened' try to become 'what I am'?"] }],
        dinnerQuestion: "What's a time something happened to you that you turned into something else?",
        transfer: [{ label: "English", note: "Narrative agency — who tells the story of your loss?" }, { label: "AI", note: "A model can generate a comeback. It cannot make meaning for you." }],
        ifTheySay: [{ heard: "Losing everything isn't wisdom, it's just bad luck.", reply: "The bad luck is real. The question is: after the luck runs out, what do you build? Zeno built a school. What would you build?" }],
        integrity: "Do not have a model write your 'what I made of it' column. The meaning is yours to make.",
        aiLab: { setup: "After the columns.", childDoes: "Ask: 'What's a question a survivor would ask that a tourist wouldn't?' Don't answer it.", evaluate: ["Did they distinguish happening from meaning?", "Is the personal row honest?"] },
      },
      emerging: {
        title: "The Founding Catastrophe",
        dek: "Stoicism begins not in a classroom but in a shipwreck. What does it mean to build a philosophy from loss?",
        objective: "The student can explain how Zeno's biography shapes Stoic ethics and evaluate whether a philosophy born of catastrophe is universally applicable or only a crisis response.",
        parentBriefing: "This is where the biographical meets the philosophical. Zeno's claim that externals are indifferent isn't abstract — it comes from a man who lost everything external. Let them ask whether that makes it more honest or more suspicious. The Seneca problem (hypocrisy) is the mirror image: Zeno lived what he taught. But does that make the teaching true, or just personally authentic?",
        hardEdges: ["Don't romanticize catastrophe. The shipwreck is not a blessing in disguise.", "If they're going through real hardship, don't turn their life into a Stoic case study. The philosophy serves them, not the other way around."],
        reading: [{ heading: "Philosophy from the wreckage", body: "Stoicism's founding story is a merchant ruined by the sea. Zeno of Citium lost his cargo of Tyrian purple — worth its weight in silver — and arrived in Athens with nothing. He read about Socrates, followed Crates the Cynic, studied with a logician and a Platonist, and built a school on the Painted Porch. The ethics he developed — virtue is the only good, externals are indifferent — maps directly onto his biography: a man who had been stripped of externals and found himself still standing. The question this raises is uncomfortable: does Stoicism work because it's true, or because its founder was forced to find a truth that made his loss bearable? Both can be the case. A philosophy born of catastrophe is not less true for that. But it must be tested against lives that haven't been wrecked." }],
        bigIdea: "A philosophy born from loss is honest about loss. It must also answer to lives that haven't been wrecked.",
        tryThis: [{ title: "Test the founding", minutes: 16, steps: ["Write the shipwreck story in three sentences. Mark what is biography vs. what is philosophy.", "Name one claim that only makes sense if you've lost everything.", "Name one claim that works whether or not you've lost anything.", "Practice/Reflect: is 'externals are indifferent' a coping strategy or an ethical insight? Argue both sides."] }],
        dinnerQuestion: "Does a philosophy work differently when it was built by someone who had nothing?",
        transfer: [{ label: "History", note: "How biographies shape philosophies." }, { label: "AI", note: "Is 'try first' an ethics or a coping skill? Both?" }],
        ifTheySay: [{ heard: "A shipwreck isn't a philosophical argument. It's just trauma.", reply: "It's both. The trauma is real. What he built from it is an argument. The question is whether the argument holds beyond the trauma — and that's what the next 500 years tested." }],
        integrity: "If the three sentences are generated, you've replaced the founding story with a summary. That's what the tool does. The meaning is in the writing.",
        aiLab: { setup: "Critique the 'both sides' argument.", childDoes: "Ask: 'Where is this argument letting itself off easy?' Don't accept the first answer.", evaluate: ["Can they separate biography from philosophy?", "Did they test the claim against an unwrecked life?"] },
      },
      adult: {
        title: "What Remains After the Wreck",
        dek: "You don't need a shipwreck to learn what Zeno learned. But it helps to ask whether the teaching survives without the catastrophe.",
        objective: "The adult can evaluate whether Stoic indifference to externals is a universal ethics or a situational wisdom, and apply it to one real parenting or career decision.",
        parentBriefing: "This sitting is for you. Zeno's insight — that externals don't define your good — is easy to preach from safety and hard to live in a mortgage. The question isn't whether you'd be Stoic in a shipwreck. It's whether you're Stoic in a performance review.",
        hardEdges: ["Don't use Stoicism to tell a child their pain is 'external.' Their pain is theirs, and your job is protection, not philosophy.", "Financial hardship is real. 'Externals are indifferent' does not mean 'don't feed your family.' It means: don't make your soul depend on the portfolio."],
        reading: [{ heading: "The test of comfort", body: "Zeno built a philosophy from wreckage. Most of us live in comfort and borrow his conclusion. The test of Stoicism is not whether it works in a crisis — it does. The test is whether it works on a Tuesday when the portfolio is up and the children are fine and the only thing threatening your virtue is boredom. Zeno's claim is that virtue is the only good. He earned that claim in a shipwreck. You inherit it. The question is whether you can live it without the storm — or whether comfort has already taken the center without your noticing. The original WisdomForge booklet on Zeno is the longer text. This assist is for the adult who is safe and wonders if the philosophy still applies." }],
        bigIdea: "The real test of 'externals are indifferent' is not the shipwreck. It's the comfort.",
        tryThis: [{ title: "The Tuesday test", minutes: 10, steps: ["Name one external your happiness currently depends on (job, reputation, savings).", "Ask: if it were gone tomorrow, what inside move is still yours?", "One rule for this week that protects the inside move before the external fails.", "Be honest: are you practicing Stoicism or quoting it?"] }],
        dinnerQuestion: "What is one thing we have right now that we'd still be ourselves without?",
        transfer: [{ label: "Parenting", note: "Modeling resilience vs. preaching it." }],
        ifTheySay: [{ heard: "This is easy to say when you have a roof over your head.", reply: "Yes. Zeno said it after he lost his. The question is whether you can hold it before you lose yours — or whether you need to lose it first. Most people do. That's not a failure. It's the order of things." }],
        integrity: "Do not generate the 'inside move.' If a model writes your resilience, you have already lost the center Zeno found.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they name a real external?", "Is the rule for this week specific or generic?"] },
      },
    },
  }),
  ...expand({
    slug: "virtue-only-good",
    subject: "philosophy",
    unit: "Character — The Stoics",
    number: 5,
    variants: {
      little: {
        title: "Good Is What You Choose",
        dek: "Zeno said only one thing is truly good: being kind, brave, and fair. Everything else is just stuff.",
        objective: "The child can name one good thing that is a choice (kind, brave, fair) and one thing that is just stuff (toys, cookies, a trophy).",
        parentBriefing: "Keep it concrete. 'Good' for Zeno means how you choose to act — kind, fair, brave, honest. 'Stuff' is everything else — toys, weather, winning the game. Stuff isn't bad. It just isn't what makes you good. The trap at this age: thinking 'good' means 'getting things.' It doesn't.",
        hardEdges: ["Don't say stuff is bad. Zeno said it's indifferent — it can be used well or badly. A toy isn't bad. Lying to get it is.", "Don't skip the counterexample: health is good, right? Zeno said no — health can make you cruel if you use it to bully. Only how you choose can't be misused."],
        reading: [{ heading: "What is truly good?", body: "Zeno asked a big question: what is truly good? Not what feels good. Not what you want. What is good no matter what? He said: being kind. Being brave. Being fair. Being honest. These are good because you choose them, and nobody can make you use them badly. A toy can be shared or grabbed. A cookie can be a gift or a bribe. But kindness is always kind. That's what 'good' means for Zeno: the choice you make that can't go wrong." }],
        bigIdea: "Good is how you choose, not what you get.",
        tryThis: [{ title: "Good or stuff?", minutes: 8, steps: ["Make two piles: GOOD (things you choose) and STUFF (things you get).", "Sort: toy, kindness, cookie, bravery, trophy, fairness.", "Ask a grown-up: can stuff be used well or badly? Can good?", "Try this: choose one GOOD thing to do today."] }],
        dinnerQuestion: "What is something good you chose today?",
        transfer: [{ label: "AI", note: "A model can give you an answer. Being honest about whether it's right is your good." }, { label: "SEL", note: "Choosing kind vs. being told to be kind." }],
        ifTheySay: [{ heard: "But being healthy IS good!", reply: "Health is great! But can you be healthy and mean? Zeno said yes. Can you be sick and kind? Also yes. So which one is truly good — the health or the kindness?" }],
        integrity: "We name what is good before we ask the tool to help.",
        aiLab: { setup: "After sorting.", childDoes: "Ask: 'Is the model's answer good or stuff?' A model giving you an answer is stuff. You checking it is good.", evaluate: ["Did they sort choices vs. things?", "Can they explain why kindness can't be misused?"] },
      },
      young: {
        title: "The Only Good",
        dek: "Zeno said virtue is the only good. Everything else — health, wealth, grades — is indifferent. Is that wisdom or just being a goody-two-shoes?",
        objective: "The student can state Zeno's claim that virtue is the only good and give one counterexample that challenges it.",
        parentBriefing: "This is the most counterintuitive claim in Stoicism. Everything they've been told — get good grades, be healthy, have friends — Zeno puts in the 'indifferent' pile. That doesn't mean those things don't matter. It means they can be used well or badly. Only virtue — the choice itself — can't be misused. Let them push back. The pushback is the lesson.",
        hardEdges: ["Don't weaponize 'grades are indifferent' against a child who cares about school. The point isn't that grades don't matter. It's that they're not the good.", "Indifferent ≠ worthless. Zeno called health a 'preferred indifferent' — worth having, not worth your soul."],
        reading: [{ heading: "The hardest claim", body: "Zeno's founding axiom: virtue is the only good. Everything else — health, wealth, reputation, pleasure, even life — is indifferent. Not worthless. Indifferent. Capable of being used well or badly. A strong body can protect or bully. A good grade can inspire or inflate. Wealth can feed or corrupt. Only virtue — the rational choice to act wisely, justly, courageously, moderately — cannot be misused, because virtue IS the disposition to use everything well. This is why Zeno said it's the only good. Not the highest good among many. The only one. The pushback is obvious and fair: so health doesn't matter? Of course it matters. It's just not what makes you good." }],
        bigIdea: "Virtue is the only thing that can't be used badly. Everything else can.",
        tryThis: [{ title: "Test the claim", minutes: 12, steps: ["Write Zeno's claim: 'Virtue is the only good.'", "Name three things people call 'good' that Zeno calls indifferent.", "For each: can it be used badly? Can virtue?", "Talk About It: is this wisdom or self-denial?"] }],
        dinnerQuestion: "What is something everyone calls 'good' that might not be?",
        transfer: [{ label: "AI", note: "A model can be fluent and wrong. Fluency is indifferent. Truth is a choice." }, { label: "History", note: "Aristotle disagreed — he said external goods matter. The debate is 2,300 years old." }],
        ifTheySay: [{ heard: "That's just being a goody-two-shoes.", reply: "A goody-two-shoes follows rules to look good. Zeno is talking about the choice itself being the good — even when nobody sees and no rule exists. Different thing." }],
        integrity: "Do not generate the counterexample. If a model gives you the pushback, you've outsourced the thinking that Zeno said is the only good.",
        aiLab: { setup: "After testing.", childDoes: "Ask: 'Can you find one thing Zeno got wrong?' Don't help — let them search.", evaluate: ["Did they distinguish indifferent from worthless?", "Is the counterexample real or generic?"] },
      },
      emerging: {
        title: "The Founding Axiom",
        dek: "Virtue is the only good. The claim that made Stoicism — and the claim most likely to be rejected by anyone who lives in a world of systems, not just souls.",
        objective: "The student can reconstruct Zeno's argument for virtue as the only good and locate one place where systemic analysis challenges the individual-ethics frame.",
        parentBriefing: "This is the philosophical core. Zeno's argument: only virtue can't be misused, so only virtue is good. The emerging student will see the gap: systemic injustice means individual virtue can be structurally futile. Don't resolve it for them. Let them sit in the tension.",
        hardEdges: ["Don't let 'virtue is the only good' become 'so systemic change doesn't matter.' The Stoics didn't say that — they said virtue INCLUDES working for justice.", "If they're cynical about systems, that's the right instinct. Don't fix it with a slogan. Ask what virtue looks like inside a broken system."],
        reading: [{ heading: "The axiom and its test", body: "Zeno's argument, reconstructed from Cicero and Diogenes Laërtius: a good must always benefit its possessor. Health, wealth, and pleasure can harm — they can be misused. Only virtue — the disposition to use everything well — cannot be misused, because it IS good use. Therefore only virtue is good. The reasoning is rigorous. The problem is that it locates the good entirely in the individual soul. A student living in a world of structural inequality will ask: what good is individual virtue when the system is unjust? The Stoic answer is that working for justice IS virtue — justice is one of the four cardinal virtues. But the tension between an ethics of the soul and an ethics of systems is real, and Zeno doesn't fully resolve it. That gap is your curriculum." }],
        bigIdea: "Virtue is the only good — but the Stoics never said systemic justice doesn't matter. They said it's a virtue.",
        tryThis: [{ title: "Axiom vs. system", minutes: 16, steps: ["Reconstruct Zeno's argument in four steps (a good must always benefit; externals can harm; virtue can't harm; therefore virtue is the only good).", "Name one systemic problem where individual virtue seems insufficient.", "Argue: what does Stoic justice look like inside that system?", "Practice/Reflect: where does the individual-ethics frame break down, and what do you do there?"] }],
        dinnerQuestion: "Where does 'be a good person' feel like not enough?",
        transfer: [{ label: "Civics", note: "Individual virtue vs. structural justice — 2,300-year-old debate." }, { label: "AI", note: "A model can analyze a system. Choosing to act justly is yours." }],
        ifTheySay: [{ heard: "Systemic incentives make individual virtue irrelevant.", reply: "They make it harder. Not irrelevant. Zeno founded his school after losing everything to a system that didn't care. The question isn't whether the system is fair. It's whether you stay yourself inside an unfair one." }],
        integrity: "If the four-step reconstruction is generated, you've shown that the model can do philosophy. The question is whether you can.",
        aiLab: { setup: "Critique the reconstruction, don't write it.", childDoes: "Ask: 'Where does this argument cheat?' Make them find the gap.", evaluate: ["Can they state the argument without the reading?", "Did they find a real systemic challenge, not a slogan?"] },
      },
      adult: {
        title: "The Only Good and the Real World",
        dek: "Zeno said virtue is the only good. You have a mortgage. Let's talk about whether that's wisdom or a luxury belief.",
        objective: "The adult can evaluate whether Zeno's claim survives contact with adult responsibilities — bills, career, dependents — and identify one place where 'virtue is the only good' changes a real decision.",
        parentBriefing: "This is the test. It's easy to admire Zeno's rigor from a comfortable chair. It's harder when 'externals are indifferent' meets a tuition bill. Don't resolve the tension. Live in it. The Stoic answer is not 'don't care about money.' It's: don't make money your good. Provide, protect, plan — and don't sell the soul in the process.",
        hardEdges: ["'Virtue is the only good' does not mean 'quit your job.' It means: don't let the job become your good.", "Financial hardship is not a character test. It's a hardship. Stoicism doesn't ask you to enjoy it. It asks you not to lose yourself in it."],
        reading: [{ heading: "The adult test", body: "Zeno's claim that virtue is the only good is the most demanding proposition in ancient ethics. It means that your worth — your actual good — does not depend on your salary, your title, your home, your health, or your reputation. It depends on how you choose. This is not self-help. It's a redefinition of what 'good' means. The adult question is whether that redefinition is livable. Can you be a parent, a professional, a provider, and still hold that externals are indifferent? The Stoic answer: yes, because 'indifferent' doesn't mean 'ignore them.' It means: use them well, don't depend on them. Provide for your family — that's virtue. Don't make the provision your identity — that's the trap. The original WisdomForge booklet on Zeno is the longer text. This assist is for the adult who has everything and wonders if the philosophy still applies." }],
        bigIdea: "The hardest version of 'virtue is the only good' is not the shipwreck. It's the mortgage.",
        tryThis: [{ title: "The bill test", minutes: 10, steps: ["Name one external your self-worth depends on (income, title, reputation, the house).", "Ask: if it were gone, what inside move is still yours?", "One rule for this week: use that external well without treating it as your good.", "Be honest: are you providing for your family or proving yourself through them?"] }],
        dinnerQuestion: "What is one thing we're treating as 'good' that Zeno would call 'indifferent'?",
        transfer: [{ label: "Parenting", note: "What you model as 'good' is what they learn to chase." }],
        ifTheySay: [{ heard: "That's easy to say when you're not struggling.", reply: "Zeno said it after losing everything. The question is whether you can hold it before you lose everything — or whether you need to. Most people do. The practice is not waiting for the wreck." }],
        integrity: "If the 'inside move' is generated, you've outsourced the only thing Zeno said is good.",
        aiLab: { setup: "Off.", childDoes: "None.", evaluate: ["Did they name a real external?", "Is the rule specific enough to live this week?"] },
      },
    },
  }),
];
