import { expand } from "./factory";
import type { Lesson } from "../types";

export const thinkingLessons: Lesson[] = [
  ...expand({
    slug: "claim-and-check",
    subject: "thinking",
    unit: "How to Think",
    number: 1,
    variants: {
      little: {
        title: "A Claim Is a Sentence You Can Check",
        dek: "Someone said it. That is not the same as it is true.",
        objective: "The child can turn a sentence into a check: look, ask a grown-up, or try.",
        parentBriefing: "Use ordinary claims ('there are no more apples,' 'it always rains on Tuesdays'). The model is a second speaker, not the villain. You are teaching the pause before belief.",
        hardEdges: ["Do not mock them for believing a story. Teach the check.", "Skip conspiracy talk."],
        reading: [{ heading: "Said versus checked", body: "A claim is a sentence that wants you to believe it. 'The cat is on the roof.' You can look. 'This tool always knows.' You can test. At WisdomForge we do not collect opinions like stickers. We ask: how would we know? If we cannot know yet, we say we do not know yet. That sentence is a kind of strength." }],
        bigIdea: "Belief without a check is just a sentence you liked.",
        tryThis: [{ title: "Three claims", minutes: 8, steps: ["Write three claims from today (a person, an ad, a tool).", "Mark LOOK / ASK / TRY / NOT YET.", "Do one look or try before the guide speaks."] }],
        dinnerQuestion: "What is one thing we heard today that we have not checked?",
        transfer: [{ label: "Science", note: "Hypothesis is a claim you intend to test." }, { label: "AI", note: "Fluent claims still need a check." }],
        ifTheySay: [{ heard: "Checking is for school.", reply: "Checking is for not being fooled in the grocery aisle either." }],
        integrity: "We do not repeat a claim we have not checked as if we knew.",
        aiLab: { setup: "After one real check.", childDoes: "Ask the guide to give a claim about the room. Check it with eyes.", evaluate: ["Did they check before arguing?", "Did they use NOT YET?"] },
      },
      young: {
        title: "Claim, Evidence, Check",
        dek: "A paragraph can hide the claim. Pull it out. Then ask what would count.",
        objective: "The student can extract a claim from a paragraph and name the evidence that would confirm or break it.",
        parentBriefing: "Bring a real paragraph: news headline, textbook, or model summary. Talk About It without winning.",
        hardEdges: ["No culture-war bait as the first paragraph.", "Do not grade their politics. Grade the check."],
        reading: [{ heading: "Pull the sentence", body: "People bury claims in tone. 'Everyone knows,' 'studies show,' 'a source told us.' Your job is to write the claim as one sentence that can be false. Then: what evidence would count, and what would break it? A model is trained to sound like evidence. Sounding is not showing. Write the claim first, or you will argue with fog." }],
        bigIdea: "If you cannot write the claim in one sentence, you are not thinking yet. You are swimming.",
        tryThis: [{ title: "One paragraph, one claim", minutes: 12, steps: ["Pick a paragraph (human or model).", "Write CLAIM / EVIDENCE NAMED / WHAT WOULD BREAK IT.", "Talk About It: did the paragraph earn the claim?"] }],
        dinnerQuestion: "What claim did we swallow this week because it was well written?",
        transfer: [{ label: "English", note: "Topic sentence versus proof." }, { label: "History", note: "A source is not a vibe." }],
        ifTheySay: [{ heard: "It's obvious.", reply: "Then it is cheap to write the claim and the breaker. Obvious claims still break." }],
        integrity: "Do not paste a classmate's post as your example without consent. Invent a generic headline instead.",
        aiLab: { setup: "Ask the guide for a short 'news' paragraph on a low-stakes topic (a sport, a weather claim).", childDoes: "Extract claim and breaker. Verify with a second source if it is factual.", evaluate: ["Is the claim falsifiable?", "Did they treat the model paragraph as a draft?"] },
      },
      emerging: {
        title: "Burden of Proof",
        dek: "The person who wants you to change your map carries the weight. Fluency does not move the weight.",
        objective: "The student can assign burden of proof and refuse a fluent argument that never picked it up.",
        parentBriefing: "Useful before college seminars and comment sections. Let them apply it to a model and to you.",
        hardEdges: ["Health/legal claims: burden includes a professional, not a thread.", "Do not use this sitting to win a family fight."],
        reading: [{ heading: "Who has to show what", body: "If I say a bridge is safe, I carry the proof. If I say a model 'basically knows,' I carry the proof. Online, the loudest map pretends the listener must disprove it. That inversion is how fluent systems win. Write: whose claim, what would count, who pays if we are wrong. Then decide whether a model is even allowed at the table." }],
        bigIdea: "Fluency cannot pick up a burden. Only evidence can.",
        tryThis: [{ title: "Burden card", minutes: 16, steps: ["Take one live disagreement (school, news, a model claim).", "Write WHO CLAIMS / BURDEN / WHAT COUNTS / COST OF ERROR.", "Ask the guide to argue the other side. Do not let it become the judge.", "Reflect: did anyone try to shift the burden onto you?"] }],
        dinnerQuestion: "Who owed proof this week, and did they pay?",
        transfer: [{ label: "Civics", note: "Courts exist because shouting is not proof." }, { label: "Science", note: "Null results are allowed." }],
        ifTheySay: [{ heard: "If you can't disprove it, it might be true.", reply: "That is how you rent your map to every fluent speaker. Might is not must." }],
        integrity: "Do not outsource the burden to a model and then cite 'AI said.'",
        aiLab: { setup: "The guide argues; you judge. It does not get to declare victory.", childDoes: "Ask it to defend a weak claim. Interrupt when it shifts burden.", evaluate: ["Did they keep the burden on the claimant?", "Did they name cost of error?"] },
      },
      adult: {
        title: "Make Checking Domestic",
        dek: "A house that never says 'how do we know?' will believe the most finished paragraph in the room.",
        objective: "The adult installs one daily check question and uses it on themselves once in front of the child.",
        parentBriefing: "This is culture, not a worksheet. Your mouth is the curriculum. If you mock their questions, they will stop bringing claims to you and will take them to a model that never sighs.",
        hardEdges: ["Do not use the check as a gotcha against the child.", "Apply it to ads and your own rants first."],
        reading: [{ heading: "The household question", body: "'How do we know?' is small enough for a Tuesday. It works on homework, headlines, and 'the model said.' If you only ask it when you already disagree, it becomes a weapon and they will hide. Ask it when you are curious. Ask it of yourself. WisdomForge can print the prompt. Only you can make it ordinary." }],
        bigIdea: "The check becomes a habit when the adult uses it on their own mouth.",
        tryThis: [{ title: "Install the question", minutes: 10, steps: ["Choose the exact wording for your band.", "Use it once today on something you said.", "Write it on the family rule card next to AI disclosure."] }],
        dinnerQuestion: "How do we know?",
        transfer: [{ label: "All subjects", note: "Same question travels." }],
        ifTheySay: [{ heard: "They'll think I don't trust them.", reply: "Trust is not the same as skipping the map. You can trust a person and still check a claim." }],
        integrity: "Do not demand a check of them that you will not run on your own feed.",
        aiLab: { setup: "Optional. Model the check on a fluent paragraph you almost believed.", childDoes: "You, not the child, ask 'how do we know?' of the guide.", evaluate: ["Did you use it on yourself?", "Is the wording actually spoken at home?"] },
      },
    },
  }),
  ...expand({
    slug: "steel-man",
    subject: "thinking",
    unit: "How to Think",
    number: 2,
    variants: {
      little: {
        title: "Say It the Kind Way First",
        dek: "Before we argue, we try to say the other person's idea so they would nod.",
        objective: "The child can restate a simple disagreement in words the other person would accept.",
        parentBriefing: "Sibling fights are the lab. You are not asking them to agree. You are asking them to hear. The guide can offer kind words; it cannot replace the nod from a real person.",
        hardEdges: ["Do not force this in a moment of tears. Wait until bodies are calm.", "Adults go first."],
        reading: [{ heading: "The nod test", body: "It is easy to make the other person sound silly. Anyone can do that. Harder: say their idea so they would nod — 'yes, that is what I mean.' Then you may say why you think something else. At WisdomForge we practice the nod test before the comeback. A talking tool can help us find kind words. It cannot nod for a brother." }],
        bigIdea: "If they would not nod, you have not heard them yet.",
        tryThis: [{ title: "Nod test", minutes: 8, steps: ["Pick a small disagreement (who left the shoes).", "Each person says the other's view until a nod.", "Only then a reply. The guide stays closed unless you need a word."] }],
        dinnerQuestion: "Who did we actually hear today?",
        transfer: [{ label: "English", note: "Retelling." }, { label: "AI", note: "A model will happily straw-man if you ask it to win." }],
        ifTheySay: [{ heard: "They're wrong, so why bother?", reply: "Because you might be arguing with a cartoon you drew. Cartoons are easy. People are not." }],
        integrity: "We do not ask the tool to write a mean version of someone in the house.",
        aiLab: { setup: "Only if a word is stuck. Parent present.", childDoes: "Ask: 'Help me say their idea kindly.' Do not name the sibling.", evaluate: ["Was there a real nod from a person?", "Did the tool stay out of the fight?"] },
      },
      young: {
        title: "Steel-Man, Then Speak",
        dek: "The strongest version of the other view is the only one worth answering.",
        objective: "The student can write a steel-man a disagreeing person would sign, then a reply that still has a spine.",
        parentBriefing: "Use a school issue, not a wound. If they use the guide, it may not be the author of the steel-man — only a checker of fairness.",
        hardEdges: ["No targeting a classmate by name.", "Steel-man is not surrender."],
        reading: [{ heading: "Win the wrong fight", body: "A straw man is a dummy you stuffed so you could knock it down. It feels like victory and teaches nothing. A steel-man is the other view in its best clothes: the evidence they would cite, the value they are protecting. You do this for two reasons. First, you might be wrong. Second, if you are right, you have earned it. Models are good at sounding like steel and still stuffing a dummy. You still have to get the nod." }],
        bigIdea: "Answer the strongest version, or you answered no one.",
        tryThis: [{ title: "Signed steel-man", minutes: 14, steps: ["Pick a disagreement you actually have.", "Write their view in ten lines they could sign.", "Talk About It with a person, not only a model.", "Then write your reply in ten lines."] }],
        dinnerQuestion: "What is the best point on the other side of something we care about?",
        transfer: [{ label: "Civics", note: "Deliberation." }, { label: "English", note: "Counterargument." }],
        ifTheySay: [{ heard: "That's just both-sides-ism.", reply: "Steel-man is not 'both are equal.' It is 'I will not lie about them to feel tall.'" }],
        integrity: "Do not paste a person's private message into a model to steel-man them.",
        aiLab: { setup: "After your draft. Ask the guide: 'Where am I still unfair?' Not: 'Write the steel-man.'", childDoes: "Revise from the critique. Keep your spine.", evaluate: ["Would the other person sign it?", "Did the model write it for them?"] },
      },
      emerging: {
        title: "Charity Without Surrender",
        dek: "Intellectual charity is a discipline. It is not niceness, and it is not a trick to look fair.",
        objective: "The student can steel-man a view they dislike, name the value underneath, and still argue.",
        parentBriefing: "This is the sitting that prevents them from becoming a fluent troll — or a model that will troll for them. Let them pick the view. Do not pick it for them.",
        hardEdges: ["Hate as a toy is out of bounds; pick a real policy or interpretation fight.", "Do not require them to steel-man abuse."],
        reading: [{ heading: "The value under the claim", body: "People rarely fight about the sentence on the table. They fight about safety, fairness, loyalty, freedom, the sacred. If you cannot name the value, you are still punching a dummy. Charity is the work of naming it accurately. Then you may say the value does not justify the claim. A model will offer a fake value if you want to look kind. Check it against a real person or a primary text." }],
        bigIdea: "Charity names the real value. It does not hand over the conclusion.",
        tryThis: [{ title: "Value, then argument", minutes: 18, steps: ["Pick a view you dislike.", "Steel-man in a paragraph a holder would sign.", "Name the value (one word).", "Argue without mocking the value.", "Ask the guide only to hunt leftover mockery."] }],
        dinnerQuestion: "What value is the other side protecting in a fight we are in?",
        transfer: [{ label: "Philosophy", note: "Socratic charity." }, { label: "History", note: "Past people were not born as our punchlines." }],
        ifTheySay: [{ heard: "Some views don't deserve charity.", reply: "Some acts don't. Views still have to be stated fairly before you refuse them, or you are performing, not thinking." }],
        integrity: "Do not generate a parody of a group and call it analysis.",
        aiLab: { setup: "Critique only.", childDoes: "Paste your steel-man. Ask where a holder would object. Do not name a classmate.", evaluate: ["Is the value real?", "Did they keep a spine in the argument?"] },
      },
      adult: {
        title: "Do Not Outsource the Nod",
        dek: "A model can imitate charity. Only a person can tell you that you heard them.",
        objective: "The adult practices one steel-man with a real person this week and keeps the model out of that conversation.",
        parentBriefing: "Family disagreements are the curriculum. If you use a model to draft your reply to your child, you are teaching them that people are prompts. Don't.",
        hardEdges: ["Not in the middle of a blow-up.", "No using the guide to 'win' parenting."],
        reading: [{ heading: "The fake nod", body: "Parents under fatigue ask a model how to talk to a teenager. Sometimes a phrase helps. Often it produces a speech that sounds like listening and is not. The nod test cannot be simulated. WisdomForge will give you hint language. It will not sit at your table and receive the look on your child's face. That look is the data." }],
        bigIdea: "Charity is a human loop. Do not close it inside a tool.",
        tryThis: [{ title: "One real nod", minutes: 15, steps: ["This week, restate a child's or partner's view until they nod.", "No device in the conversation.", "Afterward, write what you almost got wrong."] }],
        dinnerQuestion: "When did someone in this house feel actually heard?",
        transfer: [{ label: "Parenting", note: "Presence." }],
        ifTheySay: [{ heard: "I need a script or I'll say the wrong thing.", reply: "A short pause is better than a generated speech. Hint from a briefing, then use your own mouth." }],
        integrity: "Do not paste family transcripts into a model to steel-man your own kid.",
        aiLab: { setup: "Optional phrase help only, before the conversation, no names.", childDoes: "Ask: 'Give me three ways to ask someone to say more.' Then close it.", evaluate: ["Did a real person nod?", "Did a transcript stay off the tool?"] },
      },
    },
  }),
  ...expand({
    slug: "change-your-mind",
    subject: "thinking",
    unit: "How to Think",
    number: 3,
    variants: {
      little: {
        title: "It's Brave to Change",
        dek: "New evidence is allowed. Changing your mind is not losing.",
        objective: "The child can tell a short story of a time they changed their mind and what they saw.",
        parentBriefing: "Praise the change, not the original error. If you punish 'I was wrong,' they will hide inside a model that never admits it.",
        hardEdges: ["Do not use this to force them to agree with you.", "Keep examples small: foods, rules of a game, a story ending."],
        reading: [{ heading: "The brave sentence", body: "'I thought that, then I saw this, so now I think this.' That sentence is brave. Some people never say it. Talking tools almost never say it unless you make them. People can. At WisdomForge we practice the brave sentence so that a fluent wrong answer cannot trap us in the first thing we liked." }],
        bigIdea: "Changing your mind when you see more is a kind of strength.",
        tryThis: [{ title: "Brave sentence", minutes: 7, steps: ["Draw then / saw / now.", "Tell the story out loud.", "Ask a grown-up for their brave sentence too."] }],
        dinnerQuestion: "What did you change your mind about this week?",
        transfer: [{ label: "Science", note: "New data." }, { label: "AI", note: "Models don't mind being wrong unless you check." }],
        ifTheySay: [{ heard: "Changing means I was stupid.", reply: "Staying wrong on purpose is the only stupid we care about here." }],
        integrity: "We do not pretend we always knew.",
        aiLab: { setup: "After their story.", childDoes: "Ask the guide if it can be wrong. If it cannot admit it, that is a miss.", evaluate: ["Did they tell a real then/saw/now?", "Did you praise the change?"] },
      },
      young: {
        title: "What Would Change Your Mind?",
        dek: "If nothing could, you are not thinking. You are defending a jersey.",
        objective: "The student names a belief and the evidence that would move it — before the fight starts.",
        parentBriefing: "This is the vaccine against identity-fused opinions and against treating a model as an oracle. Write the breaker first.",
        hardEdges: ["Don't pick a core identity (faith, sexuality) as the first drill. Pick a school or factual belief.", "You must name a breaker for one of your own beliefs too."],
        reading: [{ heading: "Write the breaker first", body: "A belief you cannot imagine revising is a jersey. Jerseys are for games. Maps are for the world. Before you argue, write: what would I have to see to move? If the answer is 'nothing,' stop arguing — you are performing. Models will help you perform. They will also, if you ask well, help you name a breaker. You still have to mean it." }],
        bigIdea: "A mind that cannot move is not strong. It is stuck.",
        tryThis: [{ title: "Breaker first", minutes: 12, steps: ["Write one belief you hold.", "Write the breaker (evidence that would move you).", "Talk About It: is the breaker actually possible, or a fake?", "Optional: ask the guide to propose a breaker; you decide if it's real."] }],
        dinnerQuestion: "What would change your mind about something you posted or said this month?",
        transfer: [{ label: "Science", note: "Falsification." }, { label: "Civics", note: "Partisanship as jersey." }],
        ifTheySay: [{ heard: "That's a gotcha question.", reply: "It is a map question. Jerseys hate it. Maps need it." }],
        integrity: "Do not ask a model to fake a breaker so you look open-minded.",
        aiLab: { setup: "You write the belief first.", childDoes: "Ask: 'What evidence would a careful person want?' Compare to your breaker.", evaluate: ["Is the breaker real?", "Did they write it before the guide spoke?"] },
      },
      emerging: {
        title: "Update, Don't Perform",
        dek: "Changing your mind in public is rarer than generating a humble paragraph. Do the rare thing.",
        objective: "The student updates one belief in writing, with the evidence, and does not outsource the update.",
        parentBriefing: " Capstone for thinking. A short written update is the artifact. If they use a model, it may only ask questions.",
        hardEdges: ["No humiliation. An update is not a confession ritual.", "Don't force a political conversion."],
        reading: [{ heading: "The generated apology", body: "The internet taught a fake update: a fluent paragraph of humility with no change in the map. Models are excellent at that genre. A real update is boring: I believed X because Y; I saw Z; I now believe X' ; here is what I will do differently. If you cannot name the behavior, you performed. WisdomForge will not clap for the performance." }],
        bigIdea: "An update that does not change what you do is theater.",
        tryThis: [{ title: "Written update", minutes: 18, steps: ["Pick a belief that actually moved in the last year (even a small one).", "Write: THEN / BECAUSE / SAW / NOW / DO DIFFERENTLY.", "Ask the guide only: 'Where is this still theater?'", "Keep the piece. It is yours."] }],
        dinnerQuestion: "What do we do differently because we learned we were wrong?",
        transfer: [{ label: "Philosophy", note: "Epictetus: impressions can be refused. So can old conclusions." }, { label: "Science", note: "Revision is the method." }],
        ifTheySay: [{ heard: "I'll look weak.", reply: "Jerseys look strong and lose the world. Maps look like they moved and then work." }],
        integrity: "Do not generate the update. If the sentences aren't yours, it didn't happen.",
        aiLab: { setup: "Critique only, after the draft.", childDoes: "Paste the five lines. Ask where it's theater. Revise yourself.", evaluate: ["Is DO DIFFERENTLY specific?", "Could they say it without the doc?"] },
      },
      adult: {
        title: "Let Them See You Update",
        dek: "Children will not practice a move they have never seen an adult make without shame.",
        objective: "The adult tells one true update story at the table this week, including what they will do differently.",
        parentBriefing: "This is the most expensive sitting for adult pride. Do it small and true. If you cannot, they will learn that 'changing your mind' is for children and that models that never recant are the grown-ups.",
        hardEdges: ["Don't dump adult failures that aren't theirs to carry.", "Don't make them comfort you."],
        reading: [{ heading: "Visible revision", body: "You can lecture about growth mindset while never revising a household rule, a political line, or a take on a tool. They are watching. One true update — 'I thought phones at dinner were fine; I was wrong; here is the new rule' — teaches more than a unit on epistemology. WisdomForge is not a personality transplant. It is a chance to be seen changing." }],
        bigIdea: "Unseen updates do not teach. Seen ones do.",
        tryThis: [{ title: "One story", minutes: 8, steps: ["Pick a small true update.", "Tell THEN / SAW / NOW / DO at the table.", "Do not ask the child to applaud."] }],
        dinnerQuestion: "What did I change my mind about, and what will I do?",
        transfer: [{ label: "Parenting", note: "Modeling." }],
        ifTheySay: [{ heard: "They need me to be consistent, not uncertain.", reply: "Consistency of values is not the same as never updating a map. Frozen maps are how families lose teenagers to oracles." }],
        integrity: "Do not invent a cute update for pedagogy. True or skip.",
        aiLab: { setup: "Off, unless you need a calmer phrasing with no names.", childDoes: "If used: 'Help me say this without making it their job to comfort me.' Then close.", evaluate: ["Was it true?", "Did behavior actually change?"] },
      },
    },
  }),
];
