import type { CatalogUnit } from "./types";

export const catalog: CatalogUnit[] = [
  {
    id: "ai-spine",
    subject: "ai",
    title: "Education in the Age of AI",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "6 sittings",
    blurb: "Tool vs person, try first, fluent error, permissions, privacy, a full sitting with a guide.",
  },
  {
    id: "ai-agents-2",
    subject: "ai",
    title: "Building a Week with an Agent",
    status: "ready",
    bands: ["emerging", "adult"],
    weeks: "4 sittings",
    blurb: "Eval harnesses, memory hygiene, permissions audit, and when to turn the agent off.",
  },
  {
    id: "think-how",
    subject: "thinking",
    title: "How to Think",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "3 sittings",
    blurb: "Claim and check, steel-man, what would change your mind.",
  },
  {
    id: "think-bias",
    subject: "thinking",
    title: "Bias, Frames, and Missing Voices",
    status: "ready",
    bands: ["young", "emerging", "adult"],
    weeks: "3 sittings",
    blurb: "Whose data trained the room you are standing in.",
  },
  {
    id: "stoics",
    subject: "philosophy",
    title: "Character — The Stoics",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "3 sittings (full booklets live on smfwisdomforge.com)",
    blurb: "Epictetus, Marcus, Seneca — same arc, four depths. Circle, citadel, time.",
  },
  {
    id: "zeno",
    subject: "philosophy",
    title: "Zeno — The Founder",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "6 sittings",
    blurb: "Virtue as the only good. Shipwreck as curriculum. Seeds of reason, the world city, living according to nature, and the founder's legacy.",
  },
  {
    id: "greeks",
    subject: "philosophy",
    title: "How the Greeks Thought",
    status: "ready",
    bands: ["young", "emerging", "adult"],
    weeks: "10 sittings",
    blurb: "Socrates, Plato, Aristotle, the Pre-Socratics — question, form, cause. From method to metaphysics.",
  },
  {
    id: "fathers",
    subject: "philosophy",
    title: "Faith & Reason",
    status: "ready",
    bands: ["emerging", "adult"],
    weeks: "10 sittings",
    blurb: "Church Fathers through Aquinas. Belief that can think. Parent theological humility notes.",
  },
  {
    id: "ai-history",
    subject: "philosophy",
    title: "The Intellectual History of AI",
    status: "ready",
    bands: ["young", "emerging", "adult"],
    weeks: "3 sittings",
    blurb: "Turing's question, Searle's Chinese Room, Wiener's genie. The three ideas every AI user should know.",
  },
  {
    id: "math-estimate",
    subject: "math",
    title: "Estimate Before the Oracle",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "1 flagship sitting",
    blurb: "A number in the head before a tool in the hand.",
  },
  {
    id: "math-proof",
    subject: "math",
    title: "Show the Path",
    status: "ready",
    bands: ["young", "emerging", "adult"],
    weeks: "6 sittings",
    blurb: "Proof as a sentence other people can walk.",
  },
  {
    id: "sci-hyp",
    subject: "science",
    title: "Hypothesis Before Search",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "1 flagship sitting",
    blurb: "The universe is not a chatbot. Write the guess first.",
  },
  {
    id: "sci-method",
    subject: "science",
    title: "Measure Twice",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "6 sittings",
    blurb: "Error, units, and the temptation to ask a model instead of a scale.",
  },
  {
    id: "eng-write",
    subject: "english",
    title: "You Write It",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "1 flagship sitting",
    blurb: "Draft by hand. The guide is an editor who asks, not an author who signs your name.",
  },
  {
    id: "eng-rhetoric",
    subject: "english",
    title: "Rhetoric in the Age of Fluency",
    status: "ready",
    bands: ["young", "emerging", "adult"],
    weeks: "6 sittings",
    blurb: "Ethos, pathos, logos — and the machine that fakes all three.",
  },
  {
    id: "hist-source",
    subject: "history",
    title: "Source Before Summary",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "1 flagship sitting",
    blurb: "A paragraph from then, before anyone — human or model — compresses it.",
  },
  {
    id: "hist-civics",
    subject: "history",
    title: "Citizens — Constitution & Declaration",
    status: "ready",
    bands: ["young", "emerging", "adult"],
    weeks: "4–8 weeks",
    blurb: "Primary text, not storybook propaganda. A republic is a moral practice.",
  },
  {
    id: "hist-magna-carta",
    subject: "history",
    title: "Magna Carta — The Charter and the Chain",
    status: "ready",
    bands: ["young", "emerging", "adult"],
    weeks: "6 sittings",
    blurb: "A feudal contract that became the rule of law. The chain from Runnymede to your rights.",
  },
  {
    id: "art-hand",
    subject: "art",
    title: "Hand Before Generate",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "1 flagship sitting",
    blurb: "Make something imperfect. Then look at what a generator averages away.",
  },
  {
    id: "art-seeing",
    subject: "art",
    title: "Taste Is a Muscle",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "6 sittings",
    blurb: "Looking longer than the feed. Copy from life, not from a prompt.",
  },
  {
    id: "cs-spec",
    subject: "cs",
    title: "Specify the Agent",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "1 flagship sitting",
    blurb: "Soul, tools, refuse-list. Autonomy is a design choice.",
  },
  {
    id: "cs-eval",
    subject: "cs",
    title: "Eval or It Did Not Happen",
    status: "ready",
    bands: ["emerging", "adult"],
    weeks: "4 sittings",
    blurb: "Synthetic tests, CI gates, eval-driven development, and the full eval cycle. The kit's EVALS.md is the model.",
  },
  {
    id: "lang-say",
    subject: "language",
    title: "Say It Yourself",
    status: "ready",
    bands: ["little", "young", "emerging", "adult"],
    weeks: "1 flagship sitting",
    blurb: "The mouth has to move. A model can drill; it cannot be understood for you.",
  },
  {
    id: "lang-deep",
    subject: "language",
    title: "A Second Tongue, a Second Mind",
    status: "ready",
    bands: ["young", "emerging", "adult"],
    weeks: "ongoing",
    blurb: "Conversation ladders, not subtitle crutches.",
  },
];
